import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { listPlayerEntityAccess } from "@/lib/entity-visibility";
import { listPlayers } from "@/lib/players";
import { getProject } from "@/lib/projects";
import { getBaseVisibility, listStandaloneDecoys } from "@/lib/visibility-admin";
import { createDecoyAction, deleteDecoyAction, deleteVariantAction, saveVariantAction, setVisibilityAction } from "./actions";

const supported=["npc","god","character","location","group","event","relationship","map_marker","media"] as const;
export default async function PermissionsPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{entityType?:string;entityId?:string}>}){await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const [project,players,decoys]=await Promise.all([getProject(projectId),listPlayers(projectId),listStandaloneDecoys(projectId)]);if(!project)notFound();const entityType=supported.includes(search.entityType as typeof supported[number])?search.entityType:null;const entityId=search.entityId?Number.parseInt(search.entityId,10):null;let access:Awaited<ReturnType<typeof listPlayerEntityAccess>>=[];let baseVisibility:string|null=null;let lookupError:string|null=null;if(entityType&&entityId&&Number.isSafeInteger(entityId)&&entityId>0){try{baseVisibility=await getBaseVisibility(projectId,entityType,entityId);access=await listPlayerEntityAccess({projectId,entityType,entityId,baseVisibility});}catch(error){lookupError=error instanceof Error?error.message:"Entity konnte nicht geladen werden.";}}
 return <AdminShell projectId={projectId} projectName={project.name} eyebrow={`${project.name} / Players`} title="Permissions"><div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Permissions</strong></div><h1>Spieler-Wissen</h1><p>Freigaben und persönliche Varianten werden serverseitig pro Entity/Spieler gespeichert.</p></div></div><section className="panel-card"><form className="filter-bar"><select name="entityType" defaultValue={entityType??"npc"}>{supported.map((type)=><option key={type} value={type}>{type}</option>)}</select><input name="entityId" type="number" min="1" defaultValue={entityId??""} placeholder="Entity ID" required/><button>Entity laden</button></form>{lookupError?<p className="form-error">{lookupError}</p>:null}{entityType&&entityId&&baseVisibility?<><div className="table-meta"><span>Basis: <strong>{baseVisibility}</strong></span><span>{entityType} #{entityId}</span></div><div className="stack">{access.map((entry)=>{const allow=setVisibilityAction.bind(null,projectId,entityType,entityId,entry.playerId,true);const deny=setVisibilityAction.bind(null,projectId,entityType,entityId,entry.playerId,false);const save=saveVariantAction.bind(null,projectId,entityType,entityId,entry.playerId);const remove=deleteVariantAction.bind(null,projectId,entityType,entityId,entry.playerId);return <article className="panel-card nested-card" key={entry.playerId}><div className="panel-heading"><div><span className="panel-kicker">PLAYER #{entry.playerId}</span><h2>{entry.playerName}</h2></div><span className={`visibility-pill ${entry.visible?"all_players":"admin_only"}`}>{entry.visible?(entry.hasVariant?"Eigene Variante":"Echter Eintrag"):"Geheim"}</span></div><div className="row wrap-row"><form action={allow}><button className="button ghost">Freischalten</button></form><form action={deny}><button className="button ghost">Sperren</button></form></div><details><summary className="button ghost">{entry.hasVariant?"Variante bearbeiten":"Variante erstellen"}</summary><form action={save} className="stack"><label>Name-Override<input name="name" defaultValue={entry.variantName??""}/></label><label>Beschreibung-Override<textarea name="description" defaultValue={entry.variantDescription??""}/></label><label>Bild-Override<input name="image"/></label><button className="primary">Variante speichern</button></form>{entry.hasVariant?<form action={remove}><button className="danger">Variante entfernen</button></form>:null}</details></article>;})}</div></>:null}</section>
 <div className="npc-detail-grid"><section className="panel-card"><span className="panel-kicker">STANDALONE DECOYS</span><h2>Eigenständige Schein-Einträge</h2><div className="stack">{decoys.map((decoy)=><article className="panel-card nested-card" key={decoy.variant_id}><strong>{decoy.name_override}</strong><small>{decoy.player_name} · {decoy.entity_type}</small><p>{decoy.description_override}</p><form action={deleteDecoyAction.bind(null,projectId,Number(decoy.variant_id))}><button className="button ghost">Entfernen</button></form></article>)}</div></section><aside className="panel-card"><h2>Schein-Eintrag erstellen</h2><form action={createDecoyAction.bind(null,projectId)} className="stack"><label>Spieler<select name="playerId">{players.filter((p)=>p.active).map((p)=><option key={p.userId} value={p.userId}>{p.displayName}</option>)}</select></label><label>Entity Type<select name="entityType"><option value="npc">NPC</option><option value="god">God</option><option value="location">Location</option><option value="group">Group</option><option value="event">Event</option></select></label><label>Name<input name="name" required/></label><label>Beschreibung<textarea name="description"/></label><label>Bild<input name="image"/></label><button className="primary">Decoy erstellen</button></form></aside></div></AdminShell>;}
