import "server-only";

import { z } from "zod";
import { pool } from "@/lib/db";
import { clampPagination, paginatedResult, type Pagination } from "@/lib/pagination";

const characterSchema = z.object({
  name:z.string().trim().min(1).max(100), gender:z.enum(["male","female","hermaphrodite"]),
  image:z.string().trim().max(4000).optional(), publicDescription:z.string().max(100000).optional(), adminNotes:z.string().max(100000).optional(),
  locationId:z.coerce.number().int().positive(), raceId:z.coerce.number().int().positive(),
  alive:z.coerce.boolean().default(true), follower:z.coerce.boolean().default(false), className:z.string().trim().max(50).default("unknown"),
  visibilityMode:z.enum(["admin_only","all_players","selected_players"]).default("admin_only"),
});

async function assertLocation(projectId:number,locationId:number){const r=await pool.query("SELECT 1 FROM locations WHERE camp_id=$1 AND loc_id=$2 AND archived_at IS NULL",[projectId,locationId]);if(r.rowCount!==1)throw new Error("Location does not belong to this project.");}
async function canonicalRace(projectId:number,raceId:number){const r=await pool.query<{name:string}>("SELECT name FROM races WHERE project_id=$1 AND race_id=$2 AND archived_at IS NULL",[projectId,raceId]);if(r.rowCount!==1)throw new Error("Die gewählte Spezies gehört nicht zu dieser Welt oder ist archiviert.");return r.rows[0].name;}
const raceDisplay=`COALESCE(CASE n.gender WHEN 'male' THEN NULLIF(r.masculine_name,'') WHEN 'female' THEN NULLIF(r.feminine_name,'') WHEN 'hermaphrodite' THEN NULLIF(r.hermaphrodite_name,'') ELSE NULL END,NULLIF(r.name,''),NULLIF(c.race,''),'Unbekannt')`;
const characterFrom = `FROM charakters c JOIN npcs n ON n.n_id=c.n_id LEFT JOIN races r ON r.race_id=c.race_id AND r.project_id=n.camp_id JOIN locations l ON l.loc_id=c.loc_id AND l.camp_id=n.camp_id LEFT JOIN chars a ON a.n_id=n.n_id LEFT JOIN users u ON u.user_id=a.user_id AND u.camp_id=n.camp_id`;
const characterSelect = `SELECT c.char_id,n.n_id,n.name,n.image,c.race_id::int AS race_id,${raceDisplay} AS race,COALESCE(r.name,c.race,'Unbekannt') AS race_base_name,c.alive,c.class,c.age,c.birthday::text,l.name AS location_name,u.user_id AS player_id,COALESCE(u.display_name,u.name) AS player_name,n.visibility_mode ${characterFrom}`;
export type CharacterListRow={char_id:number;n_id:number;name:string;image:string;race_id:number|null;race:string;race_base_name:string;alive:boolean;class:string;age:number;birthday:string;location_name:string;player_id:number|null;player_name:string|null;visibility_mode:string};
export type CharacterListFilters={query?:string};
function queryClause(query:string|undefined,values:unknown[]){const term=query?.trim();if(!term)return "";values.push(`%${term}%`);const p=`$${values.length}`;return ` AND (n.name ILIKE ${p} OR c.race ILIKE ${p} OR COALESCE(r.name,'') ILIKE ${p} OR COALESCE(r.masculine_name,'') ILIKE ${p} OR COALESCE(r.feminine_name,'') ILIKE ${p} OR COALESCE(r.hermaphrodite_name,'') ILIKE ${p} OR c.class ILIKE ${p} OR l.name ILIKE ${p} OR COALESCE(u.display_name,u.name,'') ILIKE ${p})`;}
export async function listCharacters(projectId:number){const r=await pool.query<CharacterListRow>(`${characterSelect} WHERE n.camp_id=$1 AND n.archived_at IS NULL ORDER BY n.name,c.char_id`,[projectId]);return r.rows;}
export async function listPlayerCharacters(projectId:number){const r=await pool.query<CharacterListRow>(`${characterSelect} WHERE n.camp_id=$1 AND n.archived_at IS NULL AND a.user_id IS NOT NULL AND u.user_id IS NOT NULL ORDER BY COALESCE(u.display_name,u.name),n.name`,[projectId]);return r.rows;}
export async function listUnassignedCharacters(projectId:number){const r=await pool.query<CharacterListRow>(`${characterSelect} WHERE n.camp_id=$1 AND n.archived_at IS NULL AND a.n_id IS NULL ORDER BY n.name,c.char_id`,[projectId]);return r.rows;}
async function listCharacterSubsetPaginated(projectId:number,assigned:boolean,filters:CharacterListFilters,pagination:Pagination){const values:unknown[]=[projectId];const search=queryClause(filters.query,values);const subset=assigned?" AND a.user_id IS NOT NULL AND u.user_id IS NOT NULL":" AND a.n_id IS NULL";const count=await pool.query<{total:number}>(`SELECT count(*)::int AS total ${characterFrom} WHERE n.camp_id=$1 AND n.archived_at IS NULL${subset}${search}`,values);const total=count.rows[0]?.total??0;const page=clampPagination(total,pagination);const pageValues=[...values,page.limit,page.offset];const order=assigned?"COALESCE(u.display_name,u.name),n.name,c.char_id":"n.name,c.char_id";const rows=await pool.query<CharacterListRow>(`${characterSelect} WHERE n.camp_id=$1 AND n.archived_at IS NULL${subset}${search} ORDER BY ${order} LIMIT $${pageValues.length-1} OFFSET $${pageValues.length}`,pageValues);return paginatedResult(rows.rows,total,page);}
export function listPlayerCharactersPaginated(projectId:number,filters:CharacterListFilters,pagination:Pagination){return listCharacterSubsetPaginated(projectId,true,filters,pagination);}
export function listUnassignedCharactersPaginated(projectId:number,filters:CharacterListFilters,pagination:Pagination){return listCharacterSubsetPaginated(projectId,false,filters,pagination);}
export async function getCharacter(projectId:number,charId:number){const r=await pool.query(`SELECT c.*,${raceDisplay} AS race_display,COALESCE(r.name,c.race,'Unbekannt') AS race_base_name,n.name,n.gender,n.image,n.notes,n.public_description,n.admin_notes,n.visibility_mode,n.metadata->>'death_cause_code' AS death_cause_code,n.metadata->>'death_cause_detail' AS death_cause_detail,n.n_id AS person_id,u.user_id AS player_id,COALESCE(u.display_name,u.name) AS player_name,l.name AS location_name ${characterFrom} WHERE n.camp_id=$1 AND c.char_id=$2 AND n.archived_at IS NULL`,[projectId,charId]);return r.rows[0]??null;}
export async function createCharacter(projectId:number,input:unknown){const d=characterSchema.parse(input);const [raceName]=await Promise.all([canonicalRace(projectId,d.raceId),assertLocation(projectId,d.locationId)]);const client=await pool.connect();try{await client.query("BEGIN");const n=await client.query<{n_id:number}>(`INSERT INTO npcs(camp_id,name,notes,gender,image,public_description,admin_notes,visibility_mode,metadata,updated_at) SELECT c.camp_id,$2,$3,$4,$5,$6,$7,$8,'{}'::jsonb,now() FROM campaigns c WHERE c.camp_id=$1 AND c.status<>'archived' RETURNING n_id`,[projectId,d.name,d.adminNotes||"no notes yet",d.gender,d.image||"noimage",d.publicDescription||null,d.adminNotes||null,d.visibilityMode]);if(n.rowCount!==1)throw new Error("Project not found or archived.");const c=await client.query<{char_id:number}>(`INSERT INTO charakters(n_id,loc_id,race,race_id,alive,birthday,follower,class,age) VALUES($1,$2,$3,$4,$5,'2000-01-01',$6,$7,0) RETURNING char_id`,[n.rows[0].n_id,d.locationId,raceName,d.raceId,d.alive,d.follower,d.className]);await client.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin','character.created','person',$2,$3::jsonb)`,[projectId,n.rows[0].n_id,JSON.stringify({character_row_id:c.rows[0].char_id,race_id:d.raceId,chronology:"fantasy_dates"})]);await client.query("COMMIT");return c.rows[0].char_id;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function updateCharacter(projectId:number,charId:number,input:unknown){const d=characterSchema.parse(input);const [raceName]=await Promise.all([canonicalRace(projectId,d.raceId),assertLocation(projectId,d.locationId)]);const client=await pool.connect();try{await client.query("BEGIN");const r=await client.query<{n_id:number}>("SELECT n.n_id FROM charakters c JOIN npcs n ON n.n_id=c.n_id WHERE n.camp_id=$1 AND c.char_id=$2 AND n.archived_at IS NULL FOR UPDATE",[projectId,charId]);if(r.rowCount!==1)throw new Error("Character not found in this project.");const nId=r.rows[0].n_id;await client.query("UPDATE npcs SET name=$3,notes=$4,gender=$5,image=$6,public_description=$7,admin_notes=$8,visibility_mode=$9,updated_at=now() WHERE camp_id=$1 AND n_id=$2",[projectId,nId,d.name,d.adminNotes||"no notes yet",d.gender,d.image||"noimage",d.publicDescription||null,d.adminNotes||null,d.visibilityMode]);await client.query("UPDATE charakters SET loc_id=$3,race=$4,race_id=$5,alive=$6,follower=$7,class=$8 WHERE char_id=$2 AND n_id=$1",[nId,charId,d.locationId,raceName,d.raceId,d.alive,d.follower,d.className]);await client.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin','person.updated','person',$2,$3::jsonb)`,[projectId,nId,JSON.stringify({character_row_id:charId,race_id:d.raceId,legacy_race_shadow:raceName,legacy_age_preserved:true,legacy_birthday_preserved:true})]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function assignCharacterToPlayer(projectId:number,charId:number,playerId:number|null){const client=await pool.connect();try{await client.query("BEGIN");const c=await client.query<{n_id:number}>("SELECT n.n_id FROM charakters ch JOIN npcs n ON n.n_id=ch.n_id WHERE ch.char_id=$2 AND n.camp_id=$1 AND n.archived_at IS NULL",[projectId,charId]);if(c.rowCount!==1)throw new Error("Character not found in this project.");const nId=c.rows[0].n_id;await client.query("DELETE FROM chars WHERE n_id=$1",[nId]);if(playerId){const p=await client.query("SELECT 1 FROM users WHERE camp_id=$1 AND user_id=$2 AND active=true",[projectId,playerId]);if(p.rowCount!==1)throw new Error("Player does not belong to this project.");await client.query("DELETE FROM chars a USING npcs n WHERE a.n_id=n.n_id AND n.camp_id=$1 AND a.user_id=$2",[projectId,playerId]);await client.query("INSERT INTO chars(n_id,user_id) VALUES($1,$2)",[nId,playerId]);}await client.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin',$2,'person',$3,$4::jsonb)`,[projectId,playerId?"player.assigned":"player.unassigned",nId,JSON.stringify({player_id:playerId,character_row_id:charId})]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
export async function archiveCharacter(projectId:number,charId:number){const r=await pool.query<{n_id:number}>("UPDATE npcs n SET archived_at=now(),updated_at=now() FROM charakters c WHERE c.char_id=$2 AND c.n_id=n.n_id AND n.camp_id=$1 AND n.archived_at IS NULL RETURNING n.n_id",[projectId,charId]);if(r.rowCount!==1)throw new Error("Character not found in this project.");await pool.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin','person.archived','person',$2,$3::jsonb)`,[projectId,r.rows[0].n_id,JSON.stringify({character_row_id:charId})]);}
