import "server-only";

import { z } from "zod";
import { pool } from "@/lib/db";
import { resolveEntityReference } from "@/lib/entity-reference";

const groupSchema=z.object({name:z.string().trim().min(1).max(100),image:z.string().trim().max(4000).optional(),notes:z.string().max(100000).optional(),motto:z.string().max(10000).optional(),locationId:z.coerce.number().int().positive(),groupType:z.string().trim().max(80).optional(),visibilityMode:z.enum(["admin_only","all_players","selected_players"]).default("admin_only")});
async function assertLocation(projectId:number,locationId:number){const r=await pool.query("SELECT 1 FROM locations WHERE camp_id=$1 AND loc_id=$2 AND archived_at IS NULL",[projectId,locationId]);if(r.rowCount!==1)throw new Error("Headquarters does not belong to this project.");}

export async function listGroups(projectId:number){const r=await pool.query(`SELECT g.gr_id,g.name,g.image,g.notes,g.motto,g.loc_id,g.members,g.members AS estimated_member_count,g.group_type,g.visibility_mode,l.name AS location_name,(SELECT count(*)::int FROM group_memberships gm WHERE gm.project_id=g.camp_id AND gm.group_id=g.gr_id) AS relation_members,(SELECT count(*)::int FROM group_memberships gm WHERE gm.project_id=g.camp_id AND gm.group_id=g.gr_id) AS known_members FROM groups g JOIN locations l ON l.loc_id=g.loc_id AND l.camp_id=g.camp_id WHERE g.camp_id=$1 AND g.archived_at IS NULL ORDER BY g.name,g.gr_id`,[projectId]);return r.rows;}
export async function getGroup(projectId:number,groupId:number){const r=await pool.query(`SELECT g.*,g.members AS estimated_member_count,(SELECT count(*)::int FROM group_memberships gm WHERE gm.project_id=g.camp_id AND gm.group_id=g.gr_id) AS relation_members,(SELECT count(*)::int FROM group_memberships gm WHERE gm.project_id=g.camp_id AND gm.group_id=g.gr_id) AS known_members,l.name AS location_name FROM groups g JOIN locations l ON l.loc_id=g.loc_id AND l.camp_id=g.camp_id WHERE g.camp_id=$1 AND g.gr_id=$2 AND g.archived_at IS NULL`,[projectId,groupId]);return r.rows[0]??null;}

export async function createGroup(projectId:number,input:unknown){const d=groupSchema.parse(input);await assertLocation(projectId,d.locationId);const r=await pool.query<{gr_id:number}>(`INSERT INTO groups(loc_id,name,image,notes,members,motto,camp_id,group_type,visibility_mode,metadata,updated_at) SELECT $2,$3,$4,$5,0,$6,c.camp_id,$7,$8,'{}'::jsonb,now() FROM campaigns c WHERE c.camp_id=$1 AND c.status<>'archived' RETURNING gr_id`,[projectId,d.locationId,d.name,d.image||"noimage",d.notes||"no notes yet",d.motto||"unknown",d.groupType||null,d.visibilityMode]);if(r.rowCount!==1)throw new Error("Project not found or archived.");return r.rows[0].gr_id;}
export async function updateGroup(projectId:number,groupId:number,input:unknown){const d=groupSchema.parse(input);await assertLocation(projectId,d.locationId);const r=await pool.query(`UPDATE groups SET loc_id=$3,name=$4,image=$5,notes=$6,motto=$7,group_type=$8,visibility_mode=$9,updated_at=now() WHERE camp_id=$1 AND gr_id=$2 AND archived_at IS NULL`,[projectId,groupId,d.locationId,d.name,d.image||"noimage",d.notes||"no notes yet",d.motto||"unknown",d.groupType||null,d.visibilityMode]);if(r.rowCount!==1)throw new Error("Group not found in this project.");}
export async function archiveGroup(projectId:number,groupId:number){const r=await pool.query("UPDATE groups SET archived_at=now(),updated_at=now() WHERE camp_id=$1 AND gr_id=$2 AND archived_at IS NULL",[projectId,groupId]);if(r.rowCount!==1)throw new Error("Group not found in this project.");}

export async function setGroupMembership(args:{projectId:number;groupId:number;entityType:string;entityId:number;role?:string}){const group=await pool.query("SELECT 1 FROM groups WHERE camp_id=$1 AND gr_id=$2 AND archived_at IS NULL",[args.projectId,args.groupId]);if(group.rowCount!==1)throw new Error("Group not found in this project.");const ref=await resolveEntityReference({projectId:args.projectId,entityType:args.entityType,entityId:args.entityId});await pool.query(`INSERT INTO group_memberships(project_id,group_id,entity_type,entity_id,role) VALUES($1,$2,$3,$4,$5) ON CONFLICT(project_id,group_id,entity_type,entity_id) DO UPDATE SET role=EXCLUDED.role`,[args.projectId,args.groupId,ref.type,ref.id,args.role||null]);await pool.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin','membership.created',$2,$3,$4::jsonb)`,[args.projectId,ref.type,ref.id,JSON.stringify({group_id:args.groupId,role:args.role||null})]);}
export async function removeGroupMembership(args:{projectId:number;groupId:number;entityType:string;entityId:number}){const ref=await resolveEntityReference({projectId:args.projectId,entityType:args.entityType,entityId:args.entityId});await pool.query("DELETE FROM group_memberships WHERE project_id=$1 AND group_id=$2 AND entity_type=$3 AND entity_id=$4",[args.projectId,args.groupId,ref.type,ref.id]);await pool.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin','membership.removed',$2,$3,$4::jsonb)`,[args.projectId,ref.type,ref.id,JSON.stringify({group_id:args.groupId})]);}
