import "server-only";

import { z } from "zod";
import { pool } from "@/lib/db";
import { resolveEntityReference } from "@/lib/entity-reference";
import { clampPagination, paginatedResult, type Pagination } from "@/lib/pagination";

const groupSchema=z.object({name:z.string().trim().min(1).max(100),image:z.string().trim().max(4000).optional(),notes:z.string().max(100000).optional(),motto:z.string().max(10000).optional(),locationId:z.coerce.number().int().positive(),groupType:z.string().trim().max(80).optional(),visibilityMode:z.enum(["admin_only","all_players","selected_players"]).default("admin_only")});
export type GroupListFilters={query?:string;visibility?:"admin_only"|"all_players"|"selected_players"};

async function assertLocation(projectId:number,locationId:number){const r=await pool.query("SELECT 1 FROM locations WHERE camp_id=$1 AND loc_id=$2 AND archived_at IS NULL",[projectId,locationId]);if(r.rowCount!==1)throw new Error("Headquarters does not belong to this project.");}

function groupFilter(projectId:number,filters:GroupListFilters={}){const values:unknown[]=[projectId];const where=["g.camp_id=$1","g.archived_at IS NULL"];if(filters.query?.trim()){values.push(`%${filters.query.trim()}%`);const p=`$${values.length}`;where.push(`(g.name ILIKE ${p} OR g.group_type ILIKE ${p} OR g.motto ILIKE ${p} OR l.name ILIKE ${p})`);}if(filters.visibility){values.push(filters.visibility);where.push(`g.visibility_mode=$${values.length}`);}return{values,where};}

const groupSelect=`SELECT g.gr_id,g.name,g.image,g.notes,g.public_description,g.motto,g.loc_id,g.members,g.members AS estimated_member_count,g.group_type,g.visibility_mode,g.parent_group_id,g.founded_display,g.dissolved_display,l.name AS location_name,(SELECT count(*)::int FROM group_memberships gm WHERE gm.project_id=g.camp_id AND gm.group_id=g.gr_id) AS relation_members,(SELECT count(*)::int FROM group_memberships gm WHERE gm.project_id=g.camp_id AND gm.group_id=g.gr_id) AS known_members FROM groups g JOIN locations l ON l.loc_id=g.loc_id AND l.camp_id=g.camp_id`;

export async function listGroups(projectId:number){const r=await pool.query(`${groupSelect} WHERE g.camp_id=$1 AND g.archived_at IS NULL ORDER BY g.name,g.gr_id`,[projectId]);return r.rows;}
export async function listGroupsPaginated(projectId:number,filters:GroupListFilters,pagination:Pagination){const {values,where}=groupFilter(projectId,filters);const count=await pool.query<{total:number}>(`SELECT count(*)::int AS total FROM groups g JOIN locations l ON l.loc_id=g.loc_id AND l.camp_id=g.camp_id WHERE ${where.join(" AND ")}`,values);const total=count.rows[0]?.total??0;const page=clampPagination(total,pagination);const pageValues=[...values,page.limit,page.offset];const rows=await pool.query(`${groupSelect} WHERE ${where.join(" AND ")} ORDER BY g.name,g.gr_id LIMIT $${pageValues.length-1} OFFSET $${pageValues.length}`,pageValues);return paginatedResult(rows.rows,total,page);}
export async function getGroup(projectId:number,groupId:number){const r=await pool.query(`SELECT g.*,g.members AS estimated_member_count,(SELECT count(*)::int FROM group_memberships gm WHERE gm.project_id=g.camp_id AND gm.group_id=g.gr_id) AS relation_members,(SELECT count(*)::int FROM group_memberships gm WHERE gm.project_id=g.camp_id AND gm.group_id=g.gr_id) AS known_members,l.name AS location_name,pg.name AS parent_group_name FROM groups g JOIN locations l ON l.loc_id=g.loc_id AND l.camp_id=g.camp_id LEFT JOIN groups pg ON pg.gr_id=g.parent_group_id AND pg.camp_id=g.camp_id WHERE g.camp_id=$1 AND g.gr_id=$2 AND g.archived_at IS NULL`,[projectId,groupId]);return r.rows[0]??null;}

export async function createGroup(projectId:number,input:unknown){const d=groupSchema.parse(input);await assertLocation(projectId,d.locationId);const r=await pool.query<{gr_id:number}>(`INSERT INTO groups(loc_id,name,image,notes,members,motto,camp_id,group_type,visibility_mode,metadata,updated_at) SELECT $2,$3,$4,$5,0,$6,c.camp_id,$7,$8,'{}'::jsonb,now() FROM campaigns c WHERE c.camp_id=$1 AND c.status<>'archived' RETURNING gr_id`,[projectId,d.locationId,d.name,d.image||"noimage",d.notes||"no notes yet",d.motto||"unknown",d.groupType||null,d.visibilityMode]);if(r.rowCount!==1)throw new Error("Project not found or archived.");return r.rows[0].gr_id;}
export async function updateGroup(projectId:number,groupId:number,input:unknown){const d=groupSchema.parse(input);await assertLocation(projectId,d.locationId);const r=await pool.query(`UPDATE groups SET loc_id=$3,name=$4,image=$5,notes=$6,motto=$7,group_type=$8,visibility_mode=$9,updated_at=now() WHERE camp_id=$1 AND gr_id=$2 AND archived_at IS NULL`,[projectId,groupId,d.locationId,d.name,d.image||"noimage",d.notes||"no notes yet",d.motto||"unknown",d.groupType||null,d.visibilityMode]);if(r.rowCount!==1)throw new Error("Group not found in this project.");}
export async function archiveGroup(projectId:number,groupId:number){const r=await pool.query("UPDATE groups SET archived_at=now(),updated_at=now() WHERE camp_id=$1 AND gr_id=$2 AND archived_at IS NULL",[projectId,groupId]);if(r.rowCount!==1)throw new Error("Group not found in this project.");}

export async function setGroupMembership(args:{projectId:number;groupId:number;entityType:string;entityId:number;role?:string;rank?:string;status?:string;isLeader?:boolean;startDisplay?:string;endDisplay?:string;notes?:string}){
  const ref=await resolveEntityReference({projectId:args.projectId,entityType:args.entityType,entityId:args.entityId});
  if(ref.type!=="person")throw new Error("Group memberships are person memberships; resolve the member to person + n_id.");
  const status=["active","former","pending","honorary","unknown"].includes(args.status??"")?args.status!:"active";
  await pool.query("SELECT public.upsert_person_group_membership($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[args.projectId,args.groupId,ref.id,args.role||null,args.rank||null,status,Boolean(args.isLeader),args.startDisplay||null,args.endDisplay||null,args.notes||null]);
  await pool.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin','membership.created','person',$2,$3::jsonb)`,[args.projectId,ref.id,JSON.stringify({group_id:args.groupId,role:args.role||null,rank_label:args.rank||null,membership_status:status,is_leader:Boolean(args.isLeader)})]);
}
export async function removeGroupMembership(args:{projectId:number;groupId:number;entityType:string;entityId:number}){const ref=await resolveEntityReference({projectId:args.projectId,entityType:args.entityType,entityId:args.entityId});if(ref.type!=="person")throw new Error("Group memberships are person memberships.");await pool.query("SELECT public.delete_person_group_membership($1,$2,$3)",[args.projectId,args.groupId,ref.id]);await pool.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin','membership.removed','person',$2,$3::jsonb)`,[args.projectId,ref.id,JSON.stringify({group_id:args.groupId})]);}
