import "server-only";

import { z } from "zod";
import { pool } from "@/lib/db";
import { resolveEntityReference } from "@/lib/entity-reference";

const supportedEntityType=z.enum(["person","npc","god","character","group","location"]);
const relationshipSchema=z.object({entityAType:supportedEntityType,entityAId:z.coerce.number().int().positive(),entityBType:supportedEntityType,entityBId:z.coerce.number().int().positive(),relationshipTypeId:z.coerce.number().int().positive(),startDisplay:z.string().max(240).optional(),endDisplay:z.string().max(240).optional(),status:z.string().trim().min(1).max(30).default("active"),publicDescription:z.string().max(100000).optional(),adminNotes:z.string().max(100000).optional(),visibilityMode:z.enum(["admin_only","all_players","selected_players"]).default("admin_only")});

export async function listRelationshipTypes(){const r=await pool.query<{relationship_type_id:number;code:string;label:string;inverse_label:string|null;category:string;directed:boolean}>("SELECT relationship_type_id,code,label,inverse_label,category,directed FROM relationship_types ORDER BY category,label");return r.rows;}
export async function listRelationshipEntities(projectId:number){const r=await pool.query<{entity_type:"person"|"group"|"location";entity_id:number;name:string;badge:string}>(`SELECT 'person'::text AS entity_type,n.n_id AS entity_id,n.name,CASE WHEN g.g_id IS NOT NULL THEN 'God' WHEN EXISTS(SELECT 1 FROM chars a WHERE a.n_id=n.n_id) THEN 'Player Character' ELSE 'NPC' END AS badge FROM npcs n LEFT JOIN gods g ON g.n_id=n.n_id WHERE n.camp_id=$1 AND n.archived_at IS NULL UNION ALL SELECT 'group',gr.gr_id,gr.name,'Group' FROM groups gr WHERE gr.camp_id=$1 AND gr.archived_at IS NULL UNION ALL SELECT 'location',l.loc_id,l.name,'Location' FROM locations l WHERE l.camp_id=$1 AND l.archived_at IS NULL ORDER BY name,entity_type,entity_id`,[projectId]);return r.rows;}

export async function listRelationships(projectId:number){const r=await pool.query<{relationship_id:string;entity_a_type:string;entity_a_id:string;entity_b_type:string;entity_b_id:string;type_code:string;type_label:string;inverse_label:string|null;directed:boolean;status:string;public_description:string|null;admin_notes:string|null;visibility_mode:string;metadata:Record<string,unknown>}>(`SELECT r.relationship_id,r.entity_a_type,r.entity_a_id,r.entity_b_type,r.entity_b_id,rt.code AS type_code,rt.label AS type_label,rt.inverse_label,rt.directed,r.status,r.public_description,r.admin_notes,r.visibility_mode,r.metadata FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id WHERE r.project_id=$1 ORDER BY r.relationship_id`,[projectId]);return r.rows;}

export async function createRelationship(projectId:number,input:unknown){const d=relationshipSchema.parse(input);const [a,b]=await Promise.all([resolveEntityReference({projectId,entityType:d.entityAType,entityId:d.entityAId}),resolveEntityReference({projectId,entityType:d.entityBType,entityId:d.entityBId})]);if(a.type===b.type&&a.id===b.id)throw new Error("An entity cannot relate to itself.");const type=await pool.query<{directed:boolean;code:string}>("SELECT directed,code FROM relationship_types WHERE relationship_type_id=$1",[d.relationshipTypeId]);if(type.rowCount!==1)throw new Error("Unknown relationship type.");if(type.rows[0].code==="parent"&&a.type==="person"&&b.type==="person"){const cycle=await pool.query(`WITH RECURSIVE descendants(id) AS (SELECT $3::bigint UNION SELECT r.entity_b_id FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id JOIN descendants d ON r.entity_a_id=d.id WHERE r.project_id=$1 AND rt.code='parent' AND r.entity_a_type='person' AND r.entity_b_type='person') SELECT 1 FROM descendants WHERE id=$2 LIMIT 1`,[projectId,a.id,b.id]);if(cycle.rowCount)throw new Error("Parent relationship would create an ancestry cycle.");}
  if(!type.rows[0].directed){const duplicate=await pool.query(`SELECT 1 FROM relationships WHERE project_id=$1 AND relationship_type_id=$2 AND ((entity_a_type=$3 AND entity_a_id=$4 AND entity_b_type=$5 AND entity_b_id=$6) OR (entity_a_type=$5 AND entity_a_id=$6 AND entity_b_type=$3 AND entity_b_id=$4)) LIMIT 1`,[projectId,d.relationshipTypeId,a.type,a.id,b.type,b.id]);if(duplicate.rowCount)throw new Error("This symmetric relationship already exists.");}
  const r=await pool.query<{relationship_id:string}>(`INSERT INTO relationships(project_id,entity_a_type,entity_a_id,entity_b_type,entity_b_id,relationship_type_id,start_display,end_display,status,public_description,admin_notes,visibility_mode,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb) RETURNING relationship_id`,[projectId,a.type,a.id,b.type,b.id,d.relationshipTypeId,d.startDisplay||null,d.endDisplay||null,d.status,d.publicDescription||null,d.adminNotes||null,d.visibilityMode,JSON.stringify({source_a:{type:d.entityAType,id:d.entityAId},source_b:{type:d.entityBType,id:d.entityBId}})]);return Number(r.rows[0].relationship_id);}

export async function deleteRelationship(projectId:number,relationshipId:number){const r=await pool.query("DELETE FROM relationships WHERE project_id=$1 AND relationship_id=$2 AND NOT (metadata ? 'legacy_source')",[projectId,relationshipId]);if(r.rowCount!==1)throw new Error("Relationship not found or is a protected legacy adapter record.");}
export async function getVisibleRelationships(projectId:number,playerId:number){const r=await pool.query<{relationship_id:string;entity_a_type:string;entity_a_id:string;entity_b_type:string;entity_b_id:string;type_label:string;inverse_label:string|null;directed:boolean;public_description:string|null}>(`SELECT r.relationship_id,r.entity_a_type,r.entity_a_id,r.entity_b_type,r.entity_b_id,rt.label AS type_label,rt.inverse_label,rt.directed,r.public_description FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id LEFT JOIN entity_visibility rv ON rv.project_id=r.project_id AND rv.player_id=$2 AND rv.entity_type='relationship' AND rv.entity_id=r.relationship_id WHERE r.project_id=$1 AND COALESCE(rv.visible,r.visibility_mode='all_players') AND NOT EXISTS(SELECT 1 FROM entity_visibility ev WHERE ev.project_id=$1 AND ev.player_id=$2 AND ev.entity_type=r.entity_a_type AND ev.entity_id=r.entity_a_id AND ev.visible=false) AND NOT EXISTS(SELECT 1 FROM entity_visibility ev WHERE ev.project_id=$1 AND ev.player_id=$2 AND ev.entity_type=r.entity_b_type AND ev.entity_id=r.entity_b_id AND ev.visible=false) ORDER BY r.relationship_id`,[projectId,playerId]);return r.rows;}

export async function getFamilyTree(projectId:number){const people=await pool.query<{n_id:number;name:string;image:string;kind:string;player_character:boolean}>(`SELECT n.n_id,n.name,n.image,CASE WHEN g.g_id IS NOT NULL THEN 'god' ELSE 'character' END AS kind,EXISTS(SELECT 1 FROM chars a WHERE a.n_id=n.n_id) AS player_character FROM npcs n LEFT JOIN gods g ON g.n_id=n.n_id LEFT JOIN charakters c ON c.n_id=n.n_id WHERE n.camp_id=$1 AND n.archived_at IS NULL ORDER BY n.name`,[projectId]);const relations=await pool.query<{parent_id:number;child_id:number}>("SELECT p.parent_id,p.child_id FROM parent_child_relationships p JOIN npcs a ON a.n_id=p.parent_id JOIN npcs b ON b.n_id=p.child_id WHERE a.camp_id=$1 AND b.camp_id=$1 UNION SELECT r.entity_a_id::int,r.entity_b_id::int FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id WHERE r.project_id=$1 AND rt.code='parent' AND r.entity_a_type='person' AND r.entity_b_type='person' AND NOT (r.metadata ? 'legacy_source')",[projectId]);const partners=await pool.query<{a:number;b:number;label:string}>("SELECT r.entity_a_id::int AS a,r.entity_b_id::int AS b,rt.label FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id WHERE r.project_id=$1 AND r.entity_a_type='person' AND r.entity_b_type='person' AND rt.category='family' AND rt.code IN ('spouse','romantic','ex_partner')",[projectId]);return{people:people.rows,parentChild:relations.rows,partners:partners.rows};}
