import "server-only";

import { z } from "zod";
import { pool } from "@/lib/db";
import { resolveEntityReference } from "@/lib/entity-reference";
import { clampPagination, paginatedResult, type Pagination } from "@/lib/pagination";

const supportedEntityType=z.enum(["person","npc","god","character","group","location"]);
const houseDescentRuleSchema=z.enum(["patrilineal","matrilineal","none"]);
const relationshipSchema=z.object({entityAType:supportedEntityType,entityAId:z.coerce.number().int().positive(),entityBType:supportedEntityType,entityBId:z.coerce.number().int().positive(),relationshipTypeId:z.coerce.number().int().positive(),startDisplay:z.string().max(240).optional(),endDisplay:z.string().max(240).optional(),status:z.string().trim().min(1).max(30).default("active"),publicDescription:z.string().max(100000).optional(),adminNotes:z.string().max(100000).optional(),visibilityMode:z.enum(["admin_only","all_players","selected_players"]).default("admin_only"),houseDescentRule:houseDescentRuleSchema.optional()});

export type RelationshipListFilters={query?:string;relationshipTypeId?:number;category?:string;status?:string;personId?:number;groupId?:number;entityKind?:"character"|"god"|"player"};
export type ResolvedRelationship={relationship_id:string;entity_a_type:string;entity_a_id:string;entity_b_type:string;entity_b_id:string;a_name:string;a_kind:string;a_image:string|null;b_name:string;b_kind:string;b_image:string|null;type_code:string;type_label:string;inverse_label:string|null;category:string;directed:boolean;status:string;start_display:string|null;end_display:string|null;public_description:string|null;admin_notes:string|null;visibility_mode:string;metadata:Record<string,unknown>};

export async function listRelationshipTypes(){const r=await pool.query<{relationship_type_id:number;code:string;label:string;inverse_label:string|null;category:string;directed:boolean}>("SELECT relationship_type_id,code,label,inverse_label,category,directed FROM relationship_types ORDER BY category,label,relationship_type_id");return r.rows;}
export async function listRelationshipEntities(projectId:number){const r=await pool.query<{entity_type:"person"|"group"|"location";entity_id:number;name:string;badge:string;image:string|null}>(`SELECT 'person'::text AS entity_type,n.n_id AS entity_id,n.name,CASE WHEN g.g_id IS NOT NULL THEN 'God' WHEN EXISTS(SELECT 1 FROM chars a WHERE a.n_id=n.n_id) THEN 'Player Character' ELSE 'NPC / Character' END AS badge,NULLIF(n.image,'noimage') AS image FROM npcs n LEFT JOIN gods g ON g.n_id=n.n_id WHERE n.camp_id=$1 AND n.archived_at IS NULL UNION ALL SELECT 'group',gr.gr_id,gr.name,'Group',NULLIF(gr.image,'noimage') FROM groups gr WHERE gr.camp_id=$1 AND gr.archived_at IS NULL UNION ALL SELECT 'location',l.loc_id,l.name,'Location',NULL::text FROM locations l WHERE l.camp_id=$1 AND l.archived_at IS NULL ORDER BY name,entity_type,entity_id`,[projectId]);return r.rows;}

const resolvedSelect=`SELECT r.relationship_id,r.entity_a_type,r.entity_a_id,r.entity_b_type,r.entity_b_id,
  COALESCE(pa.name,ga.name,la.name,r.entity_a_type||' #'||r.entity_a_id::text) AS a_name,
  CASE WHEN pa.n_id IS NOT NULL THEN CASE WHEN pga.g_id IS NOT NULL THEN 'God' WHEN EXISTS(SELECT 1 FROM chars ca WHERE ca.n_id=pa.n_id) THEN 'Player Character' ELSE 'NPC / Character' END WHEN ga.gr_id IS NOT NULL THEN 'Group' WHEN la.loc_id IS NOT NULL THEN 'Location' ELSE r.entity_a_type END AS a_kind,
  COALESCE(NULLIF(pa.image,'noimage'),NULLIF(ga.image,'noimage')) AS a_image,
  COALESCE(pb.name,gb.name,lb.name,r.entity_b_type||' #'||r.entity_b_id::text) AS b_name,
  CASE WHEN pb.n_id IS NOT NULL THEN CASE WHEN pgb.g_id IS NOT NULL THEN 'God' WHEN EXISTS(SELECT 1 FROM chars cb WHERE cb.n_id=pb.n_id) THEN 'Player Character' ELSE 'NPC / Character' END WHEN gb.gr_id IS NOT NULL THEN 'Group' WHEN lb.loc_id IS NOT NULL THEN 'Location' ELSE r.entity_b_type END AS b_kind,
  COALESCE(NULLIF(pb.image,'noimage'),NULLIF(gb.image,'noimage')) AS b_image,
  rt.code AS type_code,rt.label AS type_label,rt.inverse_label,rt.category,rt.directed,r.status,r.start_display,r.end_display,r.public_description,r.admin_notes,r.visibility_mode,r.metadata
 FROM relationships r
 JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id
 LEFT JOIN npcs pa ON r.entity_a_type='person' AND pa.n_id=r.entity_a_id AND pa.camp_id=r.project_id
 LEFT JOIN gods pga ON pga.n_id=pa.n_id
 LEFT JOIN groups ga ON r.entity_a_type='group' AND ga.gr_id=r.entity_a_id AND ga.camp_id=r.project_id
 LEFT JOIN locations la ON r.entity_a_type='location' AND la.loc_id=r.entity_a_id AND la.camp_id=r.project_id
 LEFT JOIN npcs pb ON r.entity_b_type='person' AND pb.n_id=r.entity_b_id AND pb.camp_id=r.project_id
 LEFT JOIN gods pgb ON pgb.n_id=pb.n_id
 LEFT JOIN groups gb ON r.entity_b_type='group' AND gb.gr_id=r.entity_b_id AND gb.camp_id=r.project_id
 LEFT JOIN locations lb ON r.entity_b_type='location' AND lb.loc_id=r.entity_b_id AND lb.camp_id=r.project_id`;

function relationshipFilter(projectId:number,filters:RelationshipListFilters={}){const values:unknown[]=[projectId];const where=["r.project_id=$1"];if(filters.query?.trim()){values.push(`%${filters.query.trim()}%`);const p=`$${values.length}`;where.push(`(COALESCE(pa.name,ga.name,la.name,'') ILIKE ${p} OR COALESCE(pb.name,gb.name,lb.name,'') ILIKE ${p} OR rt.label ILIKE ${p})`);}if(filters.relationshipTypeId){values.push(filters.relationshipTypeId);where.push(`r.relationship_type_id=$${values.length}`);}if(filters.category){values.push(filters.category);where.push(`rt.category=$${values.length}`);}if(filters.status){values.push(filters.status);where.push(`r.status=$${values.length}`);}if(filters.personId){values.push(filters.personId);where.push(`((r.entity_a_type='person' AND r.entity_a_id=$${values.length}) OR (r.entity_b_type='person' AND r.entity_b_id=$${values.length}))`);}if(filters.groupId){values.push(filters.groupId);where.push(`((r.entity_a_type='group' AND r.entity_a_id=$${values.length}) OR (r.entity_b_type='group' AND r.entity_b_id=$${values.length}))`);}if(filters.entityKind){const kind=filters.entityKind;if(kind==="god")where.push(`((pa.n_id IS NOT NULL AND pga.g_id IS NOT NULL) OR (pb.n_id IS NOT NULL AND pgb.g_id IS NOT NULL))`);else if(kind==="player")where.push(`((pa.n_id IS NOT NULL AND EXISTS(SELECT 1 FROM chars x WHERE x.n_id=pa.n_id)) OR (pb.n_id IS NOT NULL AND EXISTS(SELECT 1 FROM chars x WHERE x.n_id=pb.n_id)))`);else where.push(`((pa.n_id IS NOT NULL AND pga.g_id IS NULL) OR (pb.n_id IS NOT NULL AND pgb.g_id IS NULL))`);}return{values,where};}

export async function listRelationships(projectId:number){const r=await pool.query<ResolvedRelationship>(`${resolvedSelect} WHERE r.project_id=$1 ORDER BY r.relationship_id`,[projectId]);return r.rows;}
export async function listRelationshipsPaginated(projectId:number,filters:RelationshipListFilters,pagination:Pagination){const {values,where}=relationshipFilter(projectId,filters);const count=await pool.query<{total:number}>(`SELECT count(*)::int AS total FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id LEFT JOIN npcs pa ON r.entity_a_type='person' AND pa.n_id=r.entity_a_id AND pa.camp_id=r.project_id LEFT JOIN gods pga ON pga.n_id=pa.n_id LEFT JOIN groups ga ON r.entity_a_type='group' AND ga.gr_id=r.entity_a_id AND ga.camp_id=r.project_id LEFT JOIN locations la ON r.entity_a_type='location' AND la.loc_id=r.entity_a_id AND la.camp_id=r.project_id LEFT JOIN npcs pb ON r.entity_b_type='person' AND pb.n_id=r.entity_b_id AND pb.camp_id=r.project_id LEFT JOIN gods pgb ON pgb.n_id=pb.n_id LEFT JOIN groups gb ON r.entity_b_type='group' AND gb.gr_id=r.entity_b_id AND gb.camp_id=r.project_id LEFT JOIN locations lb ON r.entity_b_type='location' AND lb.loc_id=r.entity_b_id AND lb.camp_id=r.project_id WHERE ${where.join(" AND ")}`,values);const total=count.rows[0]?.total??0;const page=clampPagination(total,pagination);const pageValues=[...values,page.limit,page.offset];const rows=await pool.query<ResolvedRelationship>(`${resolvedSelect} WHERE ${where.join(" AND ")} ORDER BY COALESCE(pa.name,ga.name,la.name,''),rt.label,COALESCE(pb.name,gb.name,lb.name,''),r.relationship_id LIMIT $${pageValues.length-1} OFFSET $${pageValues.length}`,pageValues);return paginatedResult(rows.rows,total,page);}

export async function createRelationship(projectId:number,input:unknown){const d=relationshipSchema.parse(input);const [a,b]=await Promise.all([resolveEntityReference({projectId,entityType:d.entityAType,entityId:d.entityAId}),resolveEntityReference({projectId,entityType:d.entityBType,entityId:d.entityBId})]);if(a.type===b.type&&a.id===b.id)throw new Error("Eine Entität kann keine Beziehung zu sich selbst haben.");const type=await pool.query<{directed:boolean;code:string}>("SELECT directed,code FROM relationship_types WHERE relationship_type_id=$1",[d.relationshipTypeId]);if(type.rowCount!==1)throw new Error("Unbekannter Beziehungstyp.");if(["parent","adoptive_parent","step_parent"].includes(type.rows[0].code)&&a.type==="person"&&b.type==="person"){const cycle=await pool.query(`WITH RECURSIVE descendants(id) AS (SELECT $3::bigint UNION SELECT r.entity_b_id FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id JOIN descendants dsc ON r.entity_a_id=dsc.id WHERE r.project_id=$1 AND rt.code IN ('parent','adoptive_parent','step_parent') AND r.entity_a_type='person' AND r.entity_b_type='person') SELECT 1 FROM descendants WHERE id=$2 LIMIT 1`,[projectId,a.id,b.id]);if(cycle.rowCount)throw new Error("Diese Elternbeziehung würde einen Zyklus erzeugen.");}
  const duplicate=type.rows[0].directed?await pool.query(`SELECT 1 FROM relationships WHERE project_id=$1 AND relationship_type_id=$2 AND entity_a_type=$3 AND entity_a_id=$4 AND entity_b_type=$5 AND entity_b_id=$6 LIMIT 1`,[projectId,d.relationshipTypeId,a.type,a.id,b.type,b.id]):await pool.query(`SELECT 1 FROM relationships WHERE project_id=$1 AND relationship_type_id=$2 AND ((entity_a_type=$3 AND entity_a_id=$4 AND entity_b_type=$5 AND entity_b_id=$6) OR (entity_a_type=$5 AND entity_a_id=$6 AND entity_b_type=$3 AND entity_b_id=$4)) LIMIT 1`,[projectId,d.relationshipTypeId,a.type,a.id,b.type,b.id]);if(duplicate.rowCount)throw new Error("Diese Beziehung existiert bereits.");
  const metadata:Record<string,unknown>={source_a:{type:d.entityAType,id:d.entityAId},source_b:{type:d.entityBType,id:d.entityBId}};
  if(type.rows[0].code==="spouse"&&a.type==="person"&&b.type==="person")metadata.house_descent_rule=d.houseDescentRule??"patrilineal";
  const r=await pool.query<{relationship_id:string}>(`INSERT INTO relationships(project_id,entity_a_type,entity_a_id,entity_b_type,entity_b_id,relationship_type_id,start_display,end_display,status,public_description,admin_notes,visibility_mode,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb) RETURNING relationship_id`,[projectId,a.type,a.id,b.type,b.id,d.relationshipTypeId,d.startDisplay||null,d.endDisplay||null,d.status,d.publicDescription||null,d.adminNotes||null,d.visibilityMode,JSON.stringify(metadata)]);await pool.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin','relationship.created','relationship',$2,$3::jsonb)`,[projectId,Number(r.rows[0].relationship_id),JSON.stringify({a:{type:a.type,id:a.id},b:{type:b.type,id:b.id},relationship_type_id:d.relationshipTypeId,house_descent_rule:metadata.house_descent_rule??null})]);return Number(r.rows[0].relationship_id);}

export async function deleteRelationship(projectId:number,relationshipId:number){const r=await pool.query("DELETE FROM relationships WHERE project_id=$1 AND relationship_id=$2 AND NOT (metadata ? 'legacy_source')",[projectId,relationshipId]);if(r.rowCount!==1)throw new Error("Relationship not found or is a protected legacy adapter record.");}
export async function getVisibleRelationships(projectId:number,playerId:number){const r=await pool.query<{relationship_id:string;entity_a_type:string;entity_a_id:string;entity_b_type:string;entity_b_id:string;type_label:string;inverse_label:string|null;directed:boolean;public_description:string|null}>(`SELECT r.relationship_id,r.entity_a_type,r.entity_a_id,r.entity_b_type,r.entity_b_id,rt.label AS type_label,rt.inverse_label,rt.directed,r.public_description FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id LEFT JOIN entity_visibility rv ON rv.project_id=r.project_id AND rv.player_id=$2 AND rv.entity_type='relationship' AND rv.entity_id=r.relationship_id WHERE r.project_id=$1 AND COALESCE(rv.visible,r.visibility_mode='all_players') AND NOT EXISTS(SELECT 1 FROM entity_visibility ev WHERE ev.project_id=$1 AND ev.player_id=$2 AND ev.entity_type=r.entity_a_type AND ev.entity_id=r.entity_a_id AND ev.visible=false) AND NOT EXISTS(SELECT 1 FROM entity_visibility ev WHERE ev.project_id=$1 AND ev.player_id=$2 AND ev.entity_type=r.entity_b_type AND ev.entity_id=r.entity_b_id AND ev.visible=false) ORDER BY r.relationship_id`,[projectId,playerId]);return r.rows;}

export async function getFamilyTree(projectId:number){const people=await pool.query<{n_id:number;name:string;image:string;kind:string;player_character:boolean}>(`SELECT n.n_id,n.name,n.image,CASE WHEN g.g_id IS NOT NULL THEN 'god' ELSE 'character' END AS kind,EXISTS(SELECT 1 FROM chars a WHERE a.n_id=n.n_id) AS player_character FROM npcs n LEFT JOIN gods g ON g.n_id=n.n_id LEFT JOIN charakters c ON c.n_id=n.n_id WHERE n.camp_id=$1 AND n.archived_at IS NULL ORDER BY n.name,n.n_id`,[projectId]);const relations=await pool.query<{parent_id:number;child_id:number}>("SELECT p.parent_id,p.child_id FROM parent_child_relationships p JOIN npcs a ON a.n_id=p.parent_id JOIN npcs b ON b.n_id=p.child_id WHERE a.camp_id=$1 AND b.camp_id=$1 UNION SELECT r.entity_a_id::int,r.entity_b_id::int FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id WHERE r.project_id=$1 AND rt.code='parent' AND r.entity_a_type='person' AND r.entity_b_type='person' AND NOT (r.metadata ? 'legacy_source')",[projectId]);const partners=await pool.query<{a:number;b:number;label:string}>("SELECT r.entity_a_id::int AS a,r.entity_b_id::int AS b,rt.label FROM relationships r JOIN relationship_types rt ON rt.relationship_type_id=r.relationship_type_id WHERE r.project_id=$1 AND r.entity_a_type='person' AND r.entity_b_type='person' AND rt.category='family' AND rt.code IN ('spouse','romantic','ex_partner')",[projectId]);return{people:people.rows,parentChild:relations.rows,partners:partners.rows};}
