import "server-only";

import { z } from "zod";
import { calendarStatus, getProjectCalendar } from "@/lib/calendar";
import { pool } from "@/lib/db";
import { resolveEntityReference } from "@/lib/entity-reference";
import { fantasyDateToOrdinalRange, formatFantasyDate, validateFantasyDate, type FantasyDate } from "@/lib/fantasy-calendar";
import { clampPagination, paginatedResult, type Pagination } from "@/lib/pagination";

const eventSchema=z.object({name:z.string().trim().min(1,"Name ist ein Pflichtfeld.").max(100,"Der Name darf höchstens 100 Zeichen enthalten."),notes:z.string().max(100000).optional(),image:z.string().trim().max(4000).optional(),locationId:z.coerce.number().int().positive().nullable().optional(),category:z.string().trim().max(80).optional(),importance:z.coerce.number().int().min(0).max(10).default(0),visibilityMode:z.enum(["admin_only","all_players","selected_players"]).default("admin_only")});
export type TimelineInput=z.input<typeof eventSchema>&{fantasyDate?:FantasyDate|null};
export type TimelineListFilters={query?:string;category?:string;visibility?:"admin_only"|"all_players"|"selected_players"};
async function assertLocation(projectId:number,locationId?:number|null){if(!locationId)return;const r=await pool.query("SELECT 1 FROM locations WHERE camp_id=$1 AND loc_id=$2 AND archived_at IS NULL",[projectId,locationId]);if(r.rowCount!==1)throw new Error("Der ausgewählte Ort gehört nicht zu dieser Welt oder ist archiviert.");}

const timelineSelect=`SELECT e.e_id,e.name,e.notes,e.image,e.image_media_id,e.loc_id,l.name AS location_name,e.display_date,e.sort_value,e.era,e.fantasy_year,e.fantasy_month,e.fantasy_day,e.calendar_id,e.date_precision,e.world_day_start,e.world_day_end,e.category,e.importance,e.visibility_mode FROM events e LEFT JOIN locations l ON l.loc_id=e.loc_id AND l.camp_id=e.camp_id`;
function timelineFilter(projectId:number,filters:TimelineListFilters={}){const values:unknown[]=[projectId];const where=["e.camp_id=$1","e.archived_at IS NULL"];if(filters.query?.trim()){values.push(`%${filters.query.trim()}%`);const p=`$${values.length}`;where.push(`(e.name ILIKE ${p} OR e.notes ILIKE ${p} OR e.display_date ILIKE ${p} OR e.era ILIKE ${p} OR e.category ILIKE ${p} OR l.name ILIKE ${p})`);}if(filters.category){values.push(filters.category);where.push(`e.category=$${values.length}`);}if(filters.visibility){values.push(filters.visibility);where.push(`e.visibility_mode=$${values.length}`);}return{values,where};}

async function chronology(projectId:number,date:FantasyDate|null|undefined){if(!date)return{calendarId:null,displayDate:null,sortValue:null,era:null,year:null,month:null,day:null,precision:null,start:null,end:null};const calendar=await getProjectCalendar(projectId);if(!calendar)throw new Error("Konfiguriere zuerst den Weltkalender.");const status=calendarStatus(calendar);if(!status.ready)throw new Error(`Kalender ist noch nicht gültig: ${status.errors.join(" ")}`);const errors=validateFantasyDate(date,calendar);if(errors.length)throw new Error(errors.join(" "));const range=fantasyDateToOrdinalRange(date,calendar);return{calendarId:calendar.calendarId,displayDate:formatFantasyDate(date,calendar),sortValue:range?.start??null,era:date.era,year:date.year,month:date.month??null,day:date.day??null,precision:date.precision,start:range?.start??null,end:range?.end??null};}

export async function listTimelineEvents(projectId:number){const r=await pool.query(`${timelineSelect} WHERE e.camp_id=$1 AND e.archived_at IS NULL ORDER BY e.world_day_start NULLS LAST,e.sort_value NULLS LAST,e.e_id`,[projectId]);return r.rows;}
export async function listTimelineEventsPaginated(projectId:number,filters:TimelineListFilters,pagination:Pagination){const {values,where}=timelineFilter(projectId,filters);const count=await pool.query<{total:number}>(`SELECT count(*)::int AS total FROM events e LEFT JOIN locations l ON l.loc_id=e.loc_id AND l.camp_id=e.camp_id WHERE ${where.join(" AND ")}`,values);const total=count.rows[0]?.total??0;const page=clampPagination(total,pagination);const pageValues=[...values,page.limit,page.offset];const rows=await pool.query(`${timelineSelect} WHERE ${where.join(" AND ")} ORDER BY e.world_day_start NULLS LAST,e.sort_value NULLS LAST,e.e_id LIMIT $${pageValues.length-1} OFFSET $${pageValues.length}`,pageValues);return paginatedResult(rows.rows,total,page);}
export async function getTimelineEvent(projectId:number,eventId:number){const r=await pool.query(`SELECT e.*,l.name AS location_name FROM events e LEFT JOIN locations l ON l.loc_id=e.loc_id AND l.camp_id=e.camp_id WHERE e.camp_id=$1 AND e.e_id=$2 AND e.archived_at IS NULL`,[projectId,eventId]);return r.rows[0]??null;}
export async function createTimelineEvent(projectId:number,input:TimelineInput){const d=eventSchema.parse(input);await assertLocation(projectId,d.locationId);const date=await chronology(projectId,input.fantasyDate);const r=await pool.query<{e_id:number}>(`INSERT INTO events(loc_id,name,notes,image,camp_id,display_date,sort_value,era,fantasy_year,fantasy_month,fantasy_day,calendar_id,date_precision,world_day_start,world_day_end,category,importance,visibility_mode,metadata,updated_at) SELECT $2,$3,$4,$5,c.camp_id,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,'{}'::jsonb,now() FROM campaigns c WHERE c.camp_id=$1 AND c.status<>'archived' RETURNING e_id`,[projectId,d.locationId||null,d.name,d.notes||"no notes yet",d.image||"noimage",date.displayDate,date.sortValue,date.era,date.year,date.month,date.day,date.calendarId,date.precision,date.start,date.end,d.category||null,d.importance,d.visibilityMode]);if(r.rowCount!==1)throw new Error("Die Welt wurde nicht gefunden oder ist archiviert.");return r.rows[0].e_id;}
export async function updateTimelineEvent(projectId:number,eventId:number,input:TimelineInput){const d=eventSchema.parse(input);const current=await pool.query<{loc_id:number|null}>("SELECT loc_id FROM events WHERE camp_id=$1 AND e_id=$2 AND archived_at IS NULL",[projectId,eventId]);if(current.rowCount!==1)throw new Error("Das Ereignis wurde nicht gefunden oder gehört nicht zu dieser Welt.");const nextLocation=d.locationId??null;if(nextLocation!==current.rows[0].loc_id)await assertLocation(projectId,nextLocation);const date=await chronology(projectId,input.fantasyDate);const r=await pool.query(`UPDATE events SET loc_id=$3,name=$4,notes=$5,image=$6,display_date=$7,sort_value=$8,era=$9,fantasy_year=$10,fantasy_month=$11,fantasy_day=$12,calendar_id=$13,date_precision=$14,world_day_start=$15,world_day_end=$16,category=$17,importance=$18,visibility_mode=$19,updated_at=now() WHERE camp_id=$1 AND e_id=$2 AND archived_at IS NULL`,[projectId,eventId,nextLocation,d.name,d.notes||"no notes yet",d.image||"noimage",date.displayDate,date.sortValue,date.era,date.year,date.month,date.day,date.calendarId,date.precision,date.start,date.end,d.category||null,d.importance,d.visibilityMode]);if(r.rowCount!==1)throw new Error("Das Ereignis wurde zwischenzeitlich archiviert oder gelöscht.");}
export async function archiveTimelineEvent(projectId:number,eventId:number){const r=await pool.query("UPDATE events SET archived_at=now(),updated_at=now() WHERE camp_id=$1 AND e_id=$2 AND archived_at IS NULL",[projectId,eventId]);if(r.rowCount!==1)throw new Error("Das Ereignis wurde nicht gefunden oder ist bereits archiviert.");}

export async function linkTimelineEntity(args:{projectId:number;eventId:number;entityType:string;entityId:number;role?:string}){const event=await pool.query("SELECT 1 FROM events WHERE camp_id=$1 AND e_id=$2 AND archived_at IS NULL",[args.projectId,args.eventId]);if(event.rowCount!==1)throw new Error("Das Ereignis wurde nicht gefunden oder gehört nicht zu dieser Welt.");const ref=await resolveEntityReference({projectId:args.projectId,entityType:args.entityType,entityId:args.entityId});await pool.query(`INSERT INTO timeline_links(project_id,event_id,entity_type,entity_id,link_role) VALUES($1,$2,$3,$4,$5) ON CONFLICT(project_id,event_id,entity_type,entity_id) DO UPDATE SET link_role=EXCLUDED.link_role`,[args.projectId,args.eventId,ref.type,ref.id,args.role||null]);}
export async function unlinkTimelineEntity(args:{projectId:number;eventId:number;entityType:string;entityId:number}){const ref=await resolveEntityReference({projectId:args.projectId,entityType:args.entityType,entityId:args.entityId});const result=await pool.query("DELETE FROM timeline_links WHERE project_id=$1 AND event_id=$2 AND entity_type=$3 AND entity_id=$4",[args.projectId,args.eventId,ref.type,ref.id]);if(result.rowCount!==1)throw new Error("Die Ereignis-Verknüpfung wurde nicht gefunden oder bereits entfernt.");}
export async function listTimelineLinks(projectId:number,eventId:number){const r=await pool.query<{entity_type:string;entity_id:string;link_role:string|null}>("SELECT entity_type,entity_id,link_role FROM timeline_links WHERE project_id=$1 AND event_id=$2 ORDER BY entity_type,entity_id",[projectId,eventId]);return r.rows;}

export async function getVisibleTimelineEvents(projectId:number,playerId:number){const r=await pool.query(`SELECT e.e_id,COALESCE(v.name_override,e.name) AS name,COALESCE(v.description_override,e.notes) AS notes,COALESCE(v.image_override,e.image) AS image,e.display_date,e.world_day_start,e.category,e.importance,l.name AS location_name FROM events e LEFT JOIN entity_visibility ev ON ev.project_id=e.camp_id AND ev.player_id=$2 AND ev.entity_type='event' AND ev.entity_id=e.e_id LEFT JOIN player_entity_variants v ON v.project_id=e.camp_id AND v.player_id=$2 AND v.entity_type='event' AND v.entity_id=e.e_id AND v.mode='override' LEFT JOIN locations l ON l.loc_id=e.loc_id AND l.camp_id=e.camp_id LEFT JOIN entity_visibility lv ON lv.project_id=e.camp_id AND lv.player_id=$2 AND lv.entity_type='location' AND lv.entity_id=l.loc_id WHERE e.camp_id=$1 AND e.archived_at IS NULL AND COALESCE(ev.visible,e.visibility_mode='all_players') AND (l.loc_id IS NULL OR COALESCE(lv.visible,l.visibility_mode='all_players')) ORDER BY e.world_day_start NULLS LAST,e.sort_value NULLS LAST,e.e_id`,[projectId,playerId]);return r.rows;}
export async function getVisibleTimelineLinks(projectId:number,eventId:number,playerId:number){const r=await pool.query(`SELECT tl.entity_type,tl.entity_id,tl.link_role FROM timeline_links tl WHERE tl.project_id=$1 AND tl.event_id=$2 AND CASE tl.entity_type WHEN 'person' THEN EXISTS(SELECT 1 FROM npcs n LEFT JOIN entity_visibility ev ON ev.project_id=n.camp_id AND ev.player_id=$3 AND ev.entity_type='person' AND ev.entity_id=n.n_id WHERE n.camp_id=$1 AND n.n_id=tl.entity_id AND n.archived_at IS NULL AND COALESCE(ev.visible,n.visibility_mode='all_players')) WHEN 'location' THEN EXISTS(SELECT 1 FROM locations l LEFT JOIN entity_visibility ev ON ev.project_id=l.camp_id AND ev.player_id=$3 AND ev.entity_type='location' AND ev.entity_id=l.loc_id WHERE l.camp_id=$1 AND l.loc_id=tl.entity_id AND l.archived_at IS NULL AND COALESCE(ev.visible,l.visibility_mode='all_players')) WHEN 'group' THEN EXISTS(SELECT 1 FROM groups g LEFT JOIN entity_visibility ev ON ev.project_id=g.camp_id AND ev.player_id=$3 AND ev.entity_type='group' AND ev.entity_id=g.gr_id WHERE g.camp_id=$1 AND g.gr_id=tl.entity_id AND g.archived_at IS NULL AND COALESCE(ev.visible,g.visibility_mode='all_players')) ELSE false END ORDER BY tl.entity_type,tl.entity_id`,[projectId,eventId,playerId]);return r.rows;}
