"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminSession } from "@/lib/auth/session";
import { createRelationship, deleteRelationship } from "@/lib/entities/relationships";
import { updateRelationship } from "@/lib/relationship-admin";

function parseRef(value:FormDataEntryValue|null){if(typeof value!=="string")throw new Error("Ungültige Entitätsreferenz.");const [type,id]=value.split(":",2);const entityId=Number.parseInt(id??"",10);if(!type||!Number.isSafeInteger(entityId)||entityId<=0)throw new Error("Ungültige Entitätsreferenz.");return{type,entityId};}
function text(value:FormDataEntryValue|null){return typeof value==="string"&&value.trim()?value.trim():undefined;}
function safeMessage(error:unknown){const message=error instanceof Error?error.message:"";const allowed=["Eine Entität kann keine Beziehung zu sich selbst haben.","Unbekannter Beziehungstyp.","Diese Elternbeziehung würde einen Zyklus erzeugen.","Diese Beziehung existiert bereits.","Person does not belong to this project.","Entity does not belong to this project.","Legacy-Beziehungen sind schreibgeschützt."];return allowed.includes(message)?message:"Beziehung konnte nicht gespeichert werden. Bitte Endpunkte und Beziehungstyp prüfen.";}
function refresh(projectId:number){revalidatePath(`/admin/projects/${projectId}/relationships`);revalidatePath(`/admin/projects/${projectId}/family-trees`);revalidatePath(`/admin/projects/${projectId}/relationship-graph`);}
export async function createRelationshipAction(projectId:number,formData:FormData){await requireAdminSession();try{const a=parseRef(formData.get("entityARef"));const b=parseRef(formData.get("entityBRef"));await createRelationship(projectId,{entityAType:a.type,entityAId:a.entityId,entityBType:b.type,entityBId:b.entityId,relationshipTypeId:formData.get("relationshipTypeId"),startDisplay:text(formData.get("startDisplay")),endDisplay:text(formData.get("endDisplay")),status:text(formData.get("status"))||"active",publicDescription:text(formData.get("publicDescription")),adminNotes:text(formData.get("adminNotes")),visibilityMode:text(formData.get("visibilityMode"))||"admin_only",houseDescentRule:text(formData.get("houseDescentRule"))});}catch(error){redirect(`/admin/projects/${projectId}/relationships?error=${encodeURIComponent(safeMessage(error))}`);}refresh(projectId);redirect(`/admin/projects/${projectId}/relationships?created=1`);}
export async function updateRelationshipAction(projectId:number,relationshipId:number,formData:FormData){await requireAdminSession();try{await updateRelationship(projectId,relationshipId,{relationshipTypeId:formData.get("relationshipTypeId"),startDisplay:text(formData.get("startDisplay")),endDisplay:text(formData.get("endDisplay")),status:text(formData.get("status"))||"active",publicDescription:text(formData.get("publicDescription")),adminNotes:text(formData.get("adminNotes")),visibilityMode:text(formData.get("visibilityMode"))||"admin_only",houseDescentRule:text(formData.get("houseDescentRule"))});}catch(error){redirect(`/admin/projects/${projectId}/relationships?error=${encodeURIComponent(safeMessage(error))}`);}refresh(projectId);redirect(`/admin/projects/${projectId}/relationships?updated=1`);}
export async function deleteRelationshipAction(projectId:number,relationshipId:number){await requireAdminSession();await deleteRelationship(projectId,relationshipId);refresh(projectId);}
