"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminSession } from "@/lib/auth/session";
import { createRelationship, deleteRelationship } from "@/lib/entities/relationships";
import { formOptionalText, formText } from "@/lib/form-data";
import { getProject } from "@/lib/projects";
import { updateRelationship } from "@/lib/relationship-admin";

function parseRef(value:FormDataEntryValue|null,label:string){if(typeof value!=="string")throw new Error(`${label} ist ein Pflichtfeld.`);const [type,id]=value.split(":",2);const entityId=Number.parseInt(id??"",10);if(!type||!Number.isSafeInteger(entityId)||entityId<=0)throw new Error(`${label}: Bitte eine gültige Entität auswählen.`);return{type,entityId};}
function safeMessage(error:unknown){const message=error instanceof Error?error.message:"";const allowed=["Eine Entität kann keine Beziehung zu sich selbst haben.","Unbekannter Beziehungstyp.","Diese Elternbeziehung würde einen Zyklus erzeugen.","Diese Beziehung existiert bereits.","Die Person gehört nicht zu dieser Welt oder ist archiviert.","Der Charakter gehört nicht zu dieser Welt oder ist archiviert.","Die Gottheit gehört nicht zu dieser Welt oder ist archiviert.","Die ausgewählte Entität gehört nicht zu dieser Welt oder existiert nicht mehr.","Die Beziehung wurde nicht gefunden oder ist als Legacy-Datensatz schreibgeschützt.","Legacy-Beziehungen sind schreibgeschützt."];if(allowed.includes(message)||message.endsWith("ist ein Pflichtfeld.")||message.includes("Bitte eine gültige Entität auswählen"))return message;return "Beziehung konnte nicht gespeichert werden. Bitte Endpunkte und Beziehungstyp prüfen.";}
async function assertProject(projectId:number){if(!Number.isSafeInteger(projectId)||projectId<=0||!(await getProject(projectId)))throw new Error("Die ausgewählte Welt wurde nicht gefunden oder ist archiviert.");}
function refresh(projectId:number){revalidatePath(`/admin/projects/${projectId}/relationships`);revalidatePath(`/admin/projects/${projectId}/family-trees`);revalidatePath(`/admin/projects/${projectId}/relationship-graph`);}
export async function createRelationshipAction(projectId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);try{const a=parseRef(formData.get("entityARef"),"Von");const b=parseRef(formData.get("entityBRef"),"Zu");const relationshipTypeId=formText(formData,"relationshipTypeId");if(!relationshipTypeId)throw new Error("Beziehungstyp ist ein Pflichtfeld.");await createRelationship(projectId,{entityAType:a.type,entityAId:a.entityId,entityBType:b.type,entityBId:b.entityId,relationshipTypeId,startDisplay:formOptionalText(formData,"startDisplay")??undefined,endDisplay:formOptionalText(formData,"endDisplay")??undefined,status:formText(formData,"status")||"active",publicDescription:formOptionalText(formData,"publicDescription")??undefined,adminNotes:formOptionalText(formData,"adminNotes")??undefined,visibilityMode:formText(formData,"visibilityMode")||"admin_only",houseDescentRule:formOptionalText(formData,"houseDescentRule")??undefined});}catch(error){redirect(`/admin/projects/${projectId}/relationships?error=${encodeURIComponent(safeMessage(error))}`);}refresh(projectId);redirect(`/admin/projects/${projectId}/relationships?created=1`);}
export async function updateRelationshipAction(projectId:number,relationshipId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);try{const relationshipTypeId=formText(formData,"relationshipTypeId");if(!relationshipTypeId)throw new Error("Beziehungstyp ist ein Pflichtfeld.");await updateRelationship(projectId,relationshipId,{relationshipTypeId,startDisplay:formOptionalText(formData,"startDisplay")??undefined,endDisplay:formOptionalText(formData,"endDisplay")??undefined,status:formText(formData,"status")||"active",publicDescription:formOptionalText(formData,"publicDescription")??undefined,adminNotes:formOptionalText(formData,"adminNotes")??undefined,visibilityMode:formText(formData,"visibilityMode")||"admin_only",houseDescentRule:formOptionalText(formData,"houseDescentRule")??undefined});}catch(error){redirect(`/admin/projects/${projectId}/relationships?error=${encodeURIComponent(safeMessage(error))}`);}refresh(projectId);redirect(`/admin/projects/${projectId}/relationships?updated=1`);}
export async function deleteRelationshipAction(projectId:number,relationshipId:number){await requireAdminSession();await assertProject(projectId);await deleteRelationship(projectId,relationshipId);refresh(projectId);}
