import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityPicker } from "@/components/entity-picker";
import { Pagination } from "@/components/pagination";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { getProjectEntityOption } from "@/lib/entity-search";
import { listRelationshipTypes, listRelationshipsPaginated, type RelationshipListFilters, type ResolvedRelationship } from "@/lib/entities/relationships";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";
import { createRelationshipAction, deleteRelationshipAction, updateRelationshipAction } from "./actions";
import styles from "./relationships.module.css";

type RelType={relationship_type_id:number;code:string;label:string;inverse_label:string|null;category:string;directed:boolean};
type HouseRule="patrilineal"|"matrilineal"|"none";
type Search=Promise<{q?:string;type?:string;category?:string;status?:string;personId?:string;groupId?:string;kind?:string;page?:string;pageSize?:string;created?:string;updated?:string;create?:string;error?:string}>;
function positive(value?:string){const n=Number.parseInt(value??"",10);return Number.isSafeInteger(n)&&n>0?n:undefined;}
function validImage(value:string|null){return Boolean(value&&value.trim()&&value!=="noimage");}
function entityHref(projectId:number,type:string,id:string,kind:string){if(type==="person")return kind==="God"?`/admin/projects/${projectId}/gods/${id}`:`/admin/projects/${projectId}/npcs/${id}`;if(type==="group")return `/admin/projects/${projectId}/groups/${id}`;if(type==="location")return `/admin/projects/${projectId}/locations/${id}`;return undefined;}
function houseRule(value:unknown):HouseRule{return value==="matrilineal"||value==="none"||value==="patrilineal"?value:"patrilineal";}
function houseRuleLabel(value:HouseRule){return value==="matrilineal"?"matrilinear · Haus der Mutter":value==="none"?"keine automatische Hauszuordnung":"väterlich · Haus des Vaters";}
function HouseRuleFields({value="patrilineal"}:{value?:HouseRule}){return <fieldset className="stack"><legend>Hausfolge bei Ehe</legend><label>In welches Haus werden gemeinsame Kinder geboren?<select name="houseDescentRule" defaultValue={value}><option value="patrilineal">Väterlich – Kinder gehören zum Haus des Vaters</option><option value="matrilineal">Matrilinear – Kinder gehören zum Haus der Mutter</option><option value="none">Keine automatische Hauszuordnung</option></select></label><p className="section-help">Wird nur für <strong>Ehe / Spouse</strong> zwischen zwei Personen gespeichert. „Alle Zweige“ nutzt diese Regel für die Haus-Blutlinie.</p></fieldset>;}
function Endpoint({projectId,type,id,name,kind,image}:{projectId:number;type:string;id:string;name:string;kind:string;image:string|null}){const href=entityHref(projectId,type,id,kind);const content=<div className={styles.endpoint}><span className={styles.avatar}>{validImage(image)?<img src={image!} alt="" loading="lazy"/>:name.slice(0,1).toUpperCase()}</span><span><strong>{name}</strong><small>{kind}</small></span></div>;return href?<Link href={href}>{content}</Link>:content;}
function RelationRow({projectId,r,types,currentType}:{projectId:number;r:ResolvedRelationship;types:RelType[];currentType:number|undefined}){const legacy=Boolean(r.metadata.legacy_source);const descent=houseRule(r.metadata.house_descent_rule);return <div className={styles.relation}><Endpoint projectId={projectId} type={r.entity_a_type} id={r.entity_a_id} name={r.a_name} kind={r.a_kind} image={r.a_image}/><div className={styles.relationType}><strong>{r.type_label}</strong><small>{r.directed?"→ gerichtet":"↔ gegenseitig"}</small></div><Endpoint projectId={projectId} type={r.entity_b_type} id={r.entity_b_id} name={r.b_name} kind={r.b_kind} image={r.b_image}/><div className={styles.meta}><span>{r.status}</span><span>{r.visibility_mode}</span>{r.type_code==="spouse"?<span>Hausfolge: {houseRuleLabel(descent)}</span>:null}{r.start_display||r.end_display?<span>{r.start_display||"?"} – {r.end_display||"heute"}</span>:null}{legacy?<small>Legacy geschützt</small>:<details><summary className="button ghost">Bearbeiten…</summary><form action={updateRelationshipAction.bind(null,projectId,Number(r.relationship_id))} className="stack" style={{minWidth:320}}><label>Beziehungstyp<select name="relationshipTypeId" defaultValue={currentType}>{types.map((type)=><option key={type.relationship_type_id} value={type.relationship_type_id}>{type.category} · {type.label}</option>)}</select></label><label>Status<select name="status" defaultValue={r.status}><option value="active">Aktiv</option><option value="ended">Beendet</option><option value="historical">Historisch</option><option value="unknown">Unbekannt</option></select></label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={r.visibility_mode}><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label><div className="field-grid two"><label>Seit<input name="startDisplay" defaultValue={r.start_display??""}/></label><label>Bis<input name="endDisplay" defaultValue={r.end_display??""}/></label></div><HouseRuleFields value={r.type_code==="spouse"?descent:"patrilineal"}/><label>Öffentliche Beschreibung<textarea name="publicDescription" defaultValue={r.public_description??""}/></label><label>Admin-Notizen<textarea name="adminNotes" defaultValue={r.admin_notes??""}/></label><SubmitButton pendingLabel="Beziehung wird gespeichert …">Änderungen speichern</SubmitButton></form></details>}{!legacy?<ConfirmAction action={deleteRelationshipAction.bind(null,projectId,Number(r.relationship_id))} title="Beziehung entfernen?" description={`${r.a_name} ↔ ${r.b_name} wird entfernt und verschwindet auch aus den Stammbäumen. Die Entitäten selbst bleiben erhalten.`} triggerLabel="Entfernen…" confirmLabel="Beziehung entfernen"/>:null}</div></div>;}

export default async function RelationshipsPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [{projectId:rawProjectId},search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(rawProjectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();
  const relationshipTypeId=positive(search.type);const personId=positive(search.personId);const groupId=positive(search.groupId);const kind=["character","god","player"].includes(search.kind??"")?search.kind as RelationshipListFilters["entityKind"]:undefined;const pagination=parsePagination(search);const filters:RelationshipListFilters={query:search.q,relationshipTypeId,category:search.category||undefined,status:search.status||undefined,personId,groupId,entityKind:kind};
  const personOptionPromise=personId?getProjectEntityOption(projectId,"person",personId):Promise.resolve(null);const groupOptionPromise=groupId?getProjectEntityOption(projectId,"group",groupId):Promise.resolve(null);
  const [project,relationships,types,personOption,groupOption]=await Promise.all([getProject(projectId),listRelationshipsPaginated(projectId,filters,pagination),listRelationshipTypes(),personOptionPromise,groupOptionPromise]);if(!project)notFound();
  const categories=[...new Set(types.map((type)=>type.category))];const path=`/admin/projects/${projectId}/relationships`;const preselected=personOption??groupOption;const preselectedRef=personOption?`person:${personOption.entityId}`:groupOption?`group:${groupOption.entityId}`:"";const typeIdByCode=new Map(types.map((type)=>[type.code,type.relationship_type_id]));const hasFilters=Boolean(search.q||search.type||search.category||search.status||search.personId||search.groupId||search.kind);
  return <AdminShell projectId={projectId} projectName={project.name} section="relationships" eyebrow={`${project.name} / Wissen`} title="Beziehungen">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Beziehungen</strong></div><h1>Relationship Hub</h1><p>Lesbare, projektgebundene Beziehungen zwischen Personen, Gruppen und Orten. Personen werden intern immer als <code>person + n_id</code> gespeichert. Ehe-Hausfolge steuert zusätzlich die Hauszweige im Stammbaum.</p></div><details className="create-dropdown" open={search.create==="1"}><summary className="button primary">＋ Beziehung</summary><div className="create-popover" style={{minWidth:620}}><form action={createRelationshipAction.bind(null,projectId)} className="stack"><div className={styles.formEndpoints}><EntityPicker projectId={projectId} name="entityARef" types={["person","group","location"]} label="Von" placeholder="Person, Gruppe oder Ort suchen …" required allowClear={false} includeTypeInValue initialValue={preselectedRef} initialLabel={preselected?.name??""} initialKind={preselected?.kind??""}/><div className={styles.arrow}>→</div><EntityPicker projectId={projectId} name="entityBRef" types={["person","group","location"]} label="Zu" placeholder="Person, Gruppe oder Ort suchen …" required allowClear={false} includeTypeInValue/></div><div className={styles.formMeta}><label>Beziehungstyp<select name="relationshipTypeId" required defaultValue=""><option value="" disabled>Typ wählen …</option>{types.map((type)=><option key={type.relationship_type_id} value={type.relationship_type_id}>{type.category} · {type.label}{type.directed?" →":""}</option>)}</select></label><label>Status<select name="status" defaultValue="active"><option value="active">Aktiv</option><option value="ended">Beendet</option><option value="historical">Historisch</option><option value="unknown">Unbekannt</option></select></label><label>Sichtbarkeit<select name="visibilityMode" defaultValue="admin_only"><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div><div className="field-grid two"><label>Seit / Start<input name="startDisplay"/></label><label>Bis / Ende<input name="endDisplay"/></label></div><HouseRuleFields/><label>Öffentliche Beschreibung<textarea name="publicDescription"/></label><label>Admin-Notizen<textarea name="adminNotes"/></label><SubmitButton className="primary" pendingLabel="Beziehung wird angelegt …">Beziehung anlegen</SubmitButton></form></div></details></div>
    {search.created?<div className={styles.notice}>Beziehung wurde erstellt und ist sofort in Relationships und Stammbäumen verfügbar.</div>:null}{search.updated?<div className={styles.notice}>Beziehung wurde aktualisiert.</div>:null}{search.error?<div className={`${styles.notice} ${styles.error}`}>{search.error}</div>:null}
    <section className="panel-card"><form className={styles.filterGrid} method="get"><input name="q" defaultValue={search.q??""} placeholder="Name oder Beziehung suchen …"/><select name="type" defaultValue={search.type??""}><option value="">Alle Typen</option>{types.map((type)=><option key={type.relationship_type_id} value={type.relationship_type_id}>{type.label}</option>)}</select><select name="category" defaultValue={search.category??""}><option value="">Alle Kategorien</option>{categories.map((category)=><option key={category} value={category}>{category}</option>)}</select><select name="kind" defaultValue={search.kind??""}><option value="">Alle Personenarten</option><option value="character">NPC / Character</option><option value="player">Player Character</option><option value="god">God</option></select><select name="status" defaultValue={search.status??""}><option value="">Alle Status</option><option value="active">Aktiv</option><option value="ended">Beendet</option><option value="historical">Historisch</option></select><EntityPicker projectId={projectId} name="personId" types={["person"]} placeholder="Person filtern …" initialValue={personOption?String(personOption.entityId):""} initialLabel={personOption?.name??""} initialKind={personOption?.kind??""}/><EntityPicker projectId={projectId} name="groupId" types={["group"]} placeholder="Gruppe filtern …" initialValue={groupOption?String(groupOption.entityId):""} initialLabel={groupOption?.name??""} initialKind="Group"/><button>Filtern</button>{hasFilters?<Link className="button ghost" href={path}>Zurücksetzen</Link>:null}</form><div className="table-meta"><span><strong>{relationships.total}</strong> Beziehungen</span><span><Link href={`/admin/projects/${projectId}/family-trees`}>Stammbäume</Link> · <Link href={`/admin/projects/${projectId}/relationship-graph`}>Graph</Link></span></div>{relationships.items.length===0?<div className="empty-state large"><strong>Keine Beziehungen gefunden</strong><span>{hasFilters?"Filter ändern oder zurücksetzen.":"Lege die erste Beziehung an."}</span></div>:<div className={styles.relationList}>{relationships.items.map((r)=><RelationRow key={r.relationship_id} projectId={projectId} r={r} types={types} currentType={typeIdByCode.get(r.type_code)}/>)}</div>}<Pagination pathname={path} searchParams={{q:search.q,type:search.type,category:search.category,status:search.status,personId:search.personId,groupId:search.groupId,kind:search.kind}} page={relationships.page} pageSize={relationships.pageSize} total={relationships.total} totalPages={relationships.totalPages}/></section>
  </AdminShell>;
}
