import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { listRelationshipTypes, listRelationships } from "@/lib/entities/relationships";
import { getProject } from "@/lib/projects";
import { createRelationshipAction, deleteRelationshipAction } from "./actions";

export default async function RelationshipsPage({params}:{params:Promise<{projectId:string}>}){
 await requireAdminSession();const projectId=Number.parseInt((await params).projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const [project,relationships,types]=await Promise.all([getProject(projectId),listRelationships(projectId),listRelationshipTypes()]);if(!project)notFound();
 return <AdminShell projectId={projectId} projectName={project.name} eyebrow={`${project.name} / Wissen`} title="Beziehungen">
  <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Beziehungen</strong></div><h1>Relationship System</h1><p>Legacy-Familie und -Partnerschaften wurden idempotent adaptiert; neue Relationen sind generisch.</p></div><details className="create-dropdown"><summary className="button primary">＋ Beziehung</summary><div className="create-popover"><form action={createRelationshipAction.bind(null,projectId)} className="stack"><div className="field-grid two"><label>Entity A Typ<select name="entityAType"><option value="npc">NPC</option><option value="god">God</option><option value="character">Character</option><option value="group">Group</option><option value="location">Location</option></select></label><label>Entity A ID<input name="entityAId" type="number" min="1" required/></label><label>Entity B Typ<select name="entityBType"><option value="npc">NPC</option><option value="god">God</option><option value="character">Character</option><option value="group">Group</option><option value="location">Location</option></select></label><label>Entity B ID<input name="entityBId" type="number" min="1" required/></label></div><label>Typ<select name="relationshipTypeId">{types.map((type)=><option key={type.relationship_type_id} value={type.relationship_type_id}>{type.label}{type.directed?" →":""}</option>)}</select></label><label>Status<input name="status" defaultValue="active"/></label><label>Öffentliche Beschreibung<textarea name="publicDescription"/></label><label>Admin-Notizen<textarea name="adminNotes"/></label><label>Sichtbarkeit<select name="visibilityMode"><option value="admin_only">Admin only</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label><button className="primary">Beziehung anlegen</button></form></div></details></div>
  <section className="panel-card"><div className="table-meta"><span><strong>{relationships.length}</strong> Beziehungen</span><span><Link href={`/admin/projects/${projectId}/family-tree`}>Family Tree</Link> · <Link href={`/admin/projects/${projectId}/relationship-graph`}>Graph</Link></span></div>{relationships.length===0?<div className="empty-state large"><strong>Keine Beziehungen</strong></div>:<div className="table-scroll"><table className="entity-table"><thead><tr><th>A</th><th>Typ</th><th>B</th><th>Status</th><th>Sichtbarkeit</th><th/></tr></thead><tbody>{relationships.map((r)=><tr key={r.relationship_id}><td>{r.entity_a_type} #{r.entity_a_id}</td><td><strong>{r.type_label}</strong>{r.directed?" →":" ↔"}</td><td>{r.entity_b_type} #{r.entity_b_id}</td><td>{r.status}</td><td>{r.visibility_mode}</td><td>{r.metadata.legacy_source?<small className="muted">Legacy geschützt</small>:<form action={deleteRelationshipAction.bind(null,projectId,Number(r.relationship_id))}><button className="button ghost">Entfernen</button></form>}</td></tr>)}</tbody></table></div>}</section>
 </AdminShell>;
}
