"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminSession } from "@/lib/auth/session";
import { savePersonFantasyDate } from "@/lib/calendar";
import { archiveCharacter, assignCharacterToPlayer, createCharacter, getCharacter, updateCharacter } from "@/lib/entities/characters";
import { entityImageCropFromForm } from "@/lib/entity-image-crop";
import { saveEntityImageProfile } from "@/lib/entity-image-profiles";
import { parseFantasyDateFields } from "@/lib/fantasy-calendar";
import { formCheckbox, formOptionalId, formOptionalText, formText } from "@/lib/form-data";
import { resolveEntityImageSource, setEntityImageReference } from "@/lib/media";
import { clearPersonDeathDate, savePersonDeathMetadata } from "@/lib/person-death";
import { getProject } from "@/lib/projects";
import { ANCESTRY_RELATION_OPTIONS, addCharacterAncestry, addPersonCulture, deleteCharacterAncestry, deletePersonCulture, type AncestryRelation } from "@/lib/species-person-identity";

function values(formData:FormData,image:string){return{name:formData.get("name"),gender:formData.get("gender"),image,publicDescription:formOptionalText(formData,"publicDescription")??undefined,adminNotes:formOptionalText(formData,"adminNotes")??undefined,locationId:formData.get("locationId"),raceId:formData.get("raceId"),alive:formCheckbox(formData,"alive"),follower:formCheckbox(formData,"follower"),className:formText(formData,"className")||"unknown",visibilityMode:formText(formData,"visibilityMode")||"admin_only"};}
function dateValues(formData:FormData,prefix:string){return Object.fromEntries(["Precision","Era","Year","Month","Day"].map((suffix)=>[`${prefix}${suffix}`,formData.get(`${prefix}${suffix}`)]));}
function refresh(projectId:number,charId:number){revalidatePath(`/admin/projects/${projectId}/characters/${charId}`);revalidatePath(`/admin/projects/${projectId}/characters`);revalidatePath(`/admin/projects/${projectId}/npcs`);revalidatePath(`/admin/projects/${projectId}/family-trees`);revalidatePath(`/player/my-character`);}
async function assertProject(projectId:number){if(!Number.isSafeInteger(projectId)||projectId<=0||!(await getProject(projectId)))throw new Error("Die ausgewählte Welt wurde nicht gefunden oder ist archiviert.");}
async function saveLifeFields(projectId:number,personId:number,alive:boolean,formData:FormData){await savePersonDeathMetadata(projectId,personId,alive,formData.get("deathCauseCode"),formData.get("deathCauseDetail"));if(alive){await clearPersonDeathDate(projectId,personId);return;}if(formData.has("deathPrecision"))await savePersonFantasyDate(projectId,personId,"death",parseFantasyDateFields(dateValues(formData,"death"),"death"));}
export async function createCharacterAction(projectId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);const source=await resolveEntityImageSource(projectId,formData,{title:String(formData.get("name")??"Charakter")});const input=values(formData,source.image);const charId=await createCharacter(projectId,input);const character=await getCharacter(projectId,charId);if(!character)throw new Error("Der Charakter wurde angelegt, konnte aber anschließend nicht geladen werden.");const personId=Number(character.person_id);if(source.uploaded)await setEntityImageReference(projectId,"person",personId,source);await saveEntityImageProfile(projectId,"person",personId,source.image,entityImageCropFromForm(formData));if(formData.has("birthPrecision"))await savePersonFantasyDate(projectId,personId,"birth",parseFantasyDateFields(dateValues(formData,"birth"),"birth"));await saveLifeFields(projectId,personId,Boolean(input.alive),formData);redirect(`/admin/projects/${projectId}/characters/${charId}`);}
export async function updateCharacterAction(projectId:number,charId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);const current=await getCharacter(projectId,charId);if(!current)throw new Error("Der Charakter wurde nicht gefunden oder gehört nicht zu dieser Welt.");const personId=Number(current.person_id);const source=await resolveEntityImageSource(projectId,formData,{current:String(current.image??""),entityType:"person",entityId:personId,title:String(current.name)});const input=values(formData,source.image);await updateCharacter(projectId,charId,input);const imageChanged=source.uploaded||source.removed||source.image!==current.image;if(imageChanged)await setEntityImageReference(projectId,"person",personId,source);if(formData.has("imageCrop")||imageChanged)await saveEntityImageProfile(projectId,"person",personId,source.image,entityImageCropFromForm(formData));if(formData.has("birthPrecision"))await savePersonFantasyDate(projectId,personId,"birth",parseFantasyDateFields(dateValues(formData,"birth"),"birth"));await saveLifeFields(projectId,personId,Boolean(input.alive),formData);refresh(projectId,charId);}
export async function assignCharacterAction(projectId:number,charId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);const playerId=formOptionalId(formData,"playerId");await assignCharacterToPlayer(projectId,charId,playerId);refresh(projectId,charId);}
export async function addCharacterAncestryAction(projectId:number,charId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);const raceId=formOptionalId(formData,"ancestryRaceId");const relation=formText(formData,"ancestryRelation") as AncestryRelation;if(!raceId||!ANCESTRY_RELATION_OPTIONS.some((option)=>option.value===relation))throw new Error("Bitte eine gültige Spezies und Abstammungsart auswählen.");await addCharacterAncestry(projectId,charId,raceId,relation,formOptionalText(formData,"ancestryNotes"),formCheckbox(formData,"ancestryVisible"));refresh(projectId,charId);}
export async function deleteCharacterAncestryAction(projectId:number,charId:number,ancestryId:number){await requireAdminSession();await assertProject(projectId);await deleteCharacterAncestry(projectId,charId,ancestryId);refresh(projectId,charId);}
export async function addCharacterCultureAction(projectId:number,charId:number,personId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);const cultureId=formOptionalId(formData,"cultureId");if(!cultureId)throw new Error("Kultur ist ein Pflichtfeld.");await addPersonCulture(projectId,personId,cultureId,formCheckbox(formData,"culturePrimary"),formOptionalText(formData,"cultureNotes"),formCheckbox(formData,"cultureVisible"));refresh(projectId,charId);}
export async function deleteCharacterCultureAction(projectId:number,charId:number,personId:number,cultureId:number){await requireAdminSession();await assertProject(projectId);await deletePersonCulture(projectId,personId,cultureId);refresh(projectId,charId);}
export async function archiveCharacterAction(projectId:number,charId:number){await requireAdminSession();await assertProject(projectId);await archiveCharacter(projectId,charId);redirect(`/admin/projects/${projectId}/characters`);}
