"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminSession } from "@/lib/auth/session";
import { savePersonFantasyDate } from "@/lib/calendar";
import { archiveCharacter, assignCharacterToPlayer, createCharacter, getCharacter, updateCharacter } from "@/lib/entities/characters";
import { parseFantasyDateFields } from "@/lib/fantasy-calendar";
import { resolveEntityImageSource, setEntityImageReference } from "@/lib/media";

function values(formData:FormData,image:string){return{name:formData.get("name"),gender:formData.get("gender")||"unknown",image,publicDescription:formData.get("publicDescription")||undefined,adminNotes:formData.get("adminNotes")||undefined,locationId:formData.get("locationId"),race:formData.get("race")||"unknown",alive:formData.get("alive")==="on",follower:formData.get("follower")==="on",className:formData.get("className")||"unknown",visibilityMode:formData.get("visibilityMode")||"admin_only"};}
function dateValues(formData:FormData){return Object.fromEntries(["birthPrecision","birthEra","birthYear","birthMonth","birthDay"].map((key)=>[key,formData.get(key)]));}
function refresh(projectId:number,charId:number){revalidatePath(`/admin/projects/${projectId}/characters/${charId}`);revalidatePath(`/admin/projects/${projectId}/characters`);revalidatePath(`/admin/projects/${projectId}/npcs`);revalidatePath(`/admin/projects/${projectId}/family-trees`);}
export async function createCharacterAction(projectId:number,formData:FormData){await requireAdminSession();const source=await resolveEntityImageSource(projectId,formData,{title:String(formData.get("name")??"Character")});const charId=await createCharacter(projectId,values(formData,source.image));const character=await getCharacter(projectId,charId);if(!character)throw new Error("Character konnte nicht geladen werden.");const personId=Number(character.person_id);if(source.uploaded)await setEntityImageReference(projectId,"person",personId,source);if(formData.has("birthPrecision"))await savePersonFantasyDate(projectId,personId,"birth",parseFantasyDateFields(dateValues(formData),"birth"));redirect(`/admin/projects/${projectId}/characters/${charId}`);}
export async function updateCharacterAction(projectId:number,charId:number,formData:FormData){await requireAdminSession();const current=await getCharacter(projectId,charId);if(!current)throw new Error("Character not found in this project.");const personId=Number(current.person_id);const source=await resolveEntityImageSource(projectId,formData,{current:String(current.image??""),entityType:"person",entityId:personId,title:String(current.name)});await updateCharacter(projectId,charId,values(formData,source.image));if(source.uploaded||source.removed||source.image!==current.image)await setEntityImageReference(projectId,"person",personId,source);if(formData.has("birthPrecision"))await savePersonFantasyDate(projectId,personId,"birth",parseFantasyDateFields(dateValues(formData),"birth"));refresh(projectId,charId);}
export async function assignCharacterAction(projectId:number,charId:number,formData:FormData){await requireAdminSession();const raw=formData.get("playerId");await assignCharacterToPlayer(projectId,charId,raw?Number(raw):null);refresh(projectId,charId);}
export async function archiveCharacterAction(projectId:number,charId:number){await requireAdminSession();await archiveCharacter(projectId,charId);redirect(`/admin/projects/${projectId}/characters`);}
