"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminSession } from "@/lib/auth/session";
import { savePersonFantasyDate } from "@/lib/calendar";
import { archiveCharacter, assignCharacterToPlayer, createCharacter, getCharacter, updateCharacter } from "@/lib/entities/characters";
import { parseFantasyDateFields } from "@/lib/fantasy-calendar";
import { resolveEntityImageSource, setEntityImageReference } from "@/lib/media";
import { clearPersonDeathDate, savePersonDeathMetadata } from "@/lib/person-death";
import { ANCESTRY_RELATION_OPTIONS, addCharacterAncestry, addPersonCulture, deleteCharacterAncestry, deletePersonCulture, type AncestryRelation } from "@/lib/species-person-identity";

function values(formData:FormData,image:string){return{name:formData.get("name"),gender:formData.get("gender"),image,publicDescription:formData.get("publicDescription")||undefined,adminNotes:formData.get("adminNotes")||undefined,locationId:formData.get("locationId"),raceId:formData.get("raceId"),alive:formData.get("alive")==="on",follower:formData.get("follower")==="on",className:formData.get("className")||"unknown",visibilityMode:formData.get("visibilityMode")||"admin_only"};}
function dateValues(formData:FormData,prefix:string){return Object.fromEntries(["Precision","Era","Year","Month","Day"].map((suffix)=>[`${prefix}${suffix}`,formData.get(`${prefix}${suffix}`)]));}
function refresh(projectId:number,charId:number){revalidatePath(`/admin/projects/${projectId}/characters/${charId}`);revalidatePath(`/admin/projects/${projectId}/characters`);revalidatePath(`/admin/projects/${projectId}/npcs`);revalidatePath(`/admin/projects/${projectId}/family-trees`);revalidatePath(`/player/my-character`);}
async function saveLifeFields(projectId:number,personId:number,alive:boolean,formData:FormData){await savePersonDeathMetadata(projectId,personId,alive,formData.get("deathCauseCode"),formData.get("deathCauseDetail"));if(alive){await clearPersonDeathDate(projectId,personId);return;}if(formData.has("deathPrecision"))await savePersonFantasyDate(projectId,personId,"death",parseFantasyDateFields(dateValues(formData,"death"),"death"));}
export async function createCharacterAction(projectId:number,formData:FormData){await requireAdminSession();const source=await resolveEntityImageSource(projectId,formData,{title:String(formData.get("name")??"Character")});const input=values(formData,source.image);const charId=await createCharacter(projectId,input);const character=await getCharacter(projectId,charId);if(!character)throw new Error("Character konnte nicht geladen werden.");const personId=Number(character.person_id);if(source.uploaded)await setEntityImageReference(projectId,"person",personId,source);if(formData.has("birthPrecision"))await savePersonFantasyDate(projectId,personId,"birth",parseFantasyDateFields(dateValues(formData,"birth"),"birth"));await saveLifeFields(projectId,personId,Boolean(input.alive),formData);redirect(`/admin/projects/${projectId}/characters/${charId}`);}
export async function updateCharacterAction(projectId:number,charId:number,formData:FormData){await requireAdminSession();const current=await getCharacter(projectId,charId);if(!current)throw new Error("Character not found in this project.");const personId=Number(current.person_id);const source=await resolveEntityImageSource(projectId,formData,{current:String(current.image??""),entityType:"person",entityId:personId,title:String(current.name)});const input=values(formData,source.image);await updateCharacter(projectId,charId,input);if(source.uploaded||source.removed||source.image!==current.image)await setEntityImageReference(projectId,"person",personId,source);if(formData.has("birthPrecision"))await savePersonFantasyDate(projectId,personId,"birth",parseFantasyDateFields(dateValues(formData,"birth"),"birth"));await saveLifeFields(projectId,personId,Boolean(input.alive),formData);refresh(projectId,charId);}
export async function assignCharacterAction(projectId:number,charId:number,formData:FormData){await requireAdminSession();const raw=formData.get("playerId");await assignCharacterToPlayer(projectId,charId,raw?Number(raw):null);refresh(projectId,charId);}
export async function addCharacterAncestryAction(projectId:number,charId:number,formData:FormData){await requireAdminSession();const raceId=Number(formData.get("ancestryRaceId"));const relation=String(formData.get("ancestryRelation")??"ancestry") as AncestryRelation;if(!Number.isSafeInteger(raceId)||raceId<=0||!ANCESTRY_RELATION_OPTIONS.some((option)=>option.value===relation))throw new Error("Ungültige Abstammung.");await addCharacterAncestry(projectId,charId,raceId,relation,String(formData.get("ancestryNotes")??"").trim()||null,formData.get("ancestryVisible")==="on");refresh(projectId,charId);}
export async function deleteCharacterAncestryAction(projectId:number,charId:number,ancestryId:number){await requireAdminSession();await deleteCharacterAncestry(projectId,charId,ancestryId);refresh(projectId,charId);}
export async function addCharacterCultureAction(projectId:number,charId:number,personId:number,formData:FormData){await requireAdminSession();const cultureId=Number(formData.get("cultureId"));if(!Number.isSafeInteger(cultureId)||cultureId<=0)throw new Error("Kultur auswählen.");await addPersonCulture(projectId,personId,cultureId,formData.get("culturePrimary")==="on",String(formData.get("cultureNotes")??"").trim()||null,formData.get("cultureVisible")==="on");refresh(projectId,charId);}
export async function deleteCharacterCultureAction(projectId:number,charId:number,personId:number,cultureId:number){await requireAdminSession();await deletePersonCulture(projectId,personId,cultureId);refresh(projectId,charId);}
export async function archiveCharacterAction(projectId:number,charId:number){await requireAdminSession();await archiveCharacter(projectId,charId);redirect(`/admin/projects/${projectId}/characters`);}
