import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { Pagination } from "@/components/pagination";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { listPlayerCharactersPaginated, listUnassignedCharactersPaginated } from "@/lib/entities/characters";
import { parsePagination } from "@/lib/pagination";
import { listPlayers } from "@/lib/players";
import { getProject } from "@/lib/projects";
import { assignCharacterAction } from "./actions";

type Search=Promise<{q?:string;assignedPage?:string;assignedPageSize?:string;unassignedPage?:string;unassignedPageSize?:string}>;
function racePath(character:{race_base_name:string;race_parent_name:string|null}){return character.race_parent_name?`${character.race_parent_name} → ${character.race_base_name}`:character.race_base_name;}
export default async function CharactersPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();
  const assignedPagination=parsePagination({page:search.assignedPage,pageSize:search.assignedPageSize});const unassignedPagination=parsePagination({page:search.unassignedPage,pageSize:search.unassignedPageSize});
  const [project,assigned,unassigned,players]=await Promise.all([getProject(projectId),listPlayerCharactersPaginated(projectId,{query:search.q},assignedPagination),listUnassignedCharactersPaginated(projectId,{query:search.q},unassignedPagination),listPlayers(projectId)]);if(!project)notFound();const path=`/admin/projects/${projectId}/characters`;const activePlayers=players.filter((p)=>p.active);
  return <AdminShell projectId={projectId} projectName={project.name} section="characters" eyebrow={`${project.name} / Welt`} title="Spielercharaktere">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Spielercharaktere</strong></div><h1>Spielercharaktere</h1><p>Spezies können in eine Ebene von Subspezies unterteilt werden. Die Listen zeigen neben der geschlechtsspezifischen Bezeichnung auch den vollständigen Spezies-Pfad.</p></div></div>
    <section className="panel-card"><form className="filter-bar" method="get"><label className="search-box"><span aria-hidden="true">⌕</span><input name="q" defaultValue={search.q??""} placeholder="Charakter, Spezies, Subspezies, Klasse, Ort oder Spieler suchen …" aria-label="Spielercharaktere durchsuchen"/></label><button type="submit">Filtern</button>{search.q?<Link className="button ghost" href={path}>Zurücksetzen</Link>:null}</form></section>
    <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">ZUGEWIESEN</span><h2>Zugewiesene Spielercharaktere</h2></div><strong>{assigned.total}</strong></div>{assigned.items.length===0?<div className="empty-state large"><strong>Keine zugewiesenen Spielercharaktere gefunden</strong></div>:<div className="table-scroll"><table className="entity-table"><thead><tr><th>Person</th><th>Spieler</th><th>Spezies / Klasse</th><th>Ort</th><th/></tr></thead><tbody>{assigned.items.map((c)=><tr key={c.n_id}><td><strong>{c.name}</strong><br/><small>Person #{c.n_id} · Charakter #{c.char_id}</small></td><td>{c.player_name}</td><td><strong>{c.race}</strong><br/><small className="muted">{racePath(c)} · {c.class}</small></td><td>{c.location_name}</td><td><Link className="table-action" aria-label={`${c.name} öffnen`} href={`/admin/projects/${projectId}/characters/${c.char_id}`}>→</Link></td></tr>)}</tbody></table></div>}<Pagination pathname={path} searchParams={{q:search.q,unassignedPage:search.unassignedPage,unassignedPageSize:search.unassignedPageSize}} page={assigned.page} pageSize={assigned.pageSize} total={assigned.total} totalPages={assigned.totalPages} pageParam="assignedPage" pageSizeParam="assignedPageSize"/></section>
    <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">VERFÜGBAR</span><h2>Nicht zugewiesene Charaktere</h2></div><strong>{unassigned.total}</strong></div>{unassigned.items.length===0?<div className="empty-state"><strong>Keine freien Charakter-Personen gefunden</strong></div>:activePlayers.length===0?<div className="empty-state"><strong>Keine aktiven Spieler vorhanden</strong><span>Lege zuerst einen aktiven Spielerzugang an.</span><Link className="button" href={`/admin/projects/${projectId}/players`}>Spieler verwalten</Link></div>:<div className="table-scroll"><table className="entity-table"><thead><tr><th>Charakter</th><th>Spezies / Klasse</th><th>Spieler zuweisen</th><th/></tr></thead><tbody>{unassigned.items.map((c)=><tr key={c.n_id}><td><strong>{c.name}</strong><br/><small>Person #{c.n_id}</small></td><td><strong>{c.race}</strong><br/><small className="muted">{racePath(c)} · {c.class}</small></td><td><form action={assignCharacterAction.bind(null,projectId,c.char_id)} className="row"><label style={{minWidth:180}}>Spieler<select name="playerId" required defaultValue=""><option value="" disabled>Bitte auswählen …</option>{activePlayers.map((p)=><option key={p.userId} value={p.userId}>{p.displayName}</option>)}</select></label><SubmitButton pendingLabel="Wird zugewiesen …">Spieler zuweisen</SubmitButton></form></td><td><Link className="table-action" aria-label={`${c.name} öffnen`} href={`/admin/projects/${projectId}/characters/${c.char_id}`}>→</Link></td></tr>)}</tbody></table></div>}<Pagination pathname={path} searchParams={{q:search.q,assignedPage:search.assignedPage,assignedPageSize:search.assignedPageSize}} page={unassigned.page} pageSize={unassigned.pageSize} total={unassigned.total} totalPages={unassigned.totalPages} pageParam="unassignedPage" pageSizeParam="unassignedPageSize"/></section>
  </AdminShell>;
}
