import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { Pagination } from "@/components/pagination";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { listPlayerCharactersPaginated, listUnassignedCharactersPaginated } from "@/lib/entities/characters";
import { parsePagination } from "@/lib/pagination";
import { listPlayers } from "@/lib/players";
import { getProject } from "@/lib/projects";
import { assignCharacterAction } from "./actions";

type Search=Promise<{q?:string;assignedPage?:string;assignedPageSize?:string;unassignedPage?:string;unassignedPageSize?:string}>;
export default async function CharactersPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();
  const assignedPagination=parsePagination({page:search.assignedPage,pageSize:search.assignedPageSize});const unassignedPagination=parsePagination({page:search.unassignedPage,pageSize:search.unassignedPageSize});
  const [project,assigned,unassigned,players]=await Promise.all([getProject(projectId),listPlayerCharactersPaginated(projectId,{query:search.q},assignedPagination),listUnassignedCharactersPaginated(projectId,{query:search.q},unassignedPagination),listPlayers(projectId)]);if(!project)notFound();const path=`/admin/projects/${projectId}/characters`;const activePlayers=players.filter((p)=>p.active);
  return <AdminShell projectId={projectId} projectName={project.name} section="characters" eyebrow={`${project.name} / World`} title="Spielercharaktere">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Spielercharaktere</strong></div><h1>Player Characters</h1><p>Ein Player Character ist <code>npcs + charakters + chars + users</code>. Beide Listen sind serverseitig paginiert und laden nicht mehr alle Character-Personen auf einmal.</p></div></div>
    <section className="panel-card"><form className="filter-bar" method="get"><label className="search-box"><span aria-hidden="true">⌕</span><input name="q" defaultValue={search.q??""} placeholder="Character, Race, Klasse, Ort oder Spieler suchen …"/></label><button>Filtern</button>{search.q?<Link className="button ghost" href={path}>Zurücksetzen</Link>:null}</form></section>
    <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">ASSIGNED</span><h2>Zugewiesene Player Characters</h2></div><strong>{assigned.total}</strong></div>{assigned.items.length===0?<div className="empty-state large"><strong>Keine zugewiesenen Player Characters gefunden</strong></div>:<div className="table-scroll"><table className="entity-table"><thead><tr><th>Person</th><th>Spieler</th><th>Race / Klasse</th><th>Ort</th><th/></tr></thead><tbody>{assigned.items.map((c)=><tr key={c.n_id}><td><strong>{c.name}</strong><br/><small>n_id #{c.n_id} · char_id #{c.char_id}</small></td><td>{c.player_name}</td><td>{c.race} / {c.class}</td><td>{c.location_name}</td><td><Link className="table-action" href={`/admin/projects/${projectId}/characters/${c.char_id}`}>→</Link></td></tr>)}</tbody></table></div>}<Pagination pathname={path} searchParams={{q:search.q,unassignedPage:search.unassignedPage,unassignedPageSize:search.unassignedPageSize}} page={assigned.page} pageSize={assigned.pageSize} total={assigned.total} totalPages={assigned.totalPages} pageParam="assignedPage" pageSizeParam="assignedPageSize"/></section>
    <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">CANDIDATES</span><h2>Nicht zugewiesene NPCs</h2></div><strong>{unassigned.total}</strong></div>{unassigned.items.length===0?<div className="empty-state"><strong>Keine freien Character-Personen gefunden</strong></div>:<div className="table-scroll"><table className="entity-table"><thead><tr><th>NPC</th><th>Race / Klasse</th><th>Spieler zuweisen</th><th/></tr></thead><tbody>{unassigned.items.map((c)=><tr key={c.n_id}><td><strong>{c.name}</strong><br/><small>Person #{c.n_id}</small></td><td>{c.race} / {c.class}</td><td><form action={assignCharacterAction.bind(null,projectId,c.char_id)} className="row"><select name="playerId" defaultValue=""><option value="">Spieler wählen …</option>{activePlayers.map((p)=><option key={p.userId} value={p.userId}>{p.displayName}</option>)}</select><SubmitButton pendingLabel="Zuweisen …">Zuweisen</SubmitButton></form></td><td><Link className="table-action" href={`/admin/projects/${projectId}/characters/${c.char_id}`}>→</Link></td></tr>)}</tbody></table></div>}<Pagination pathname={path} searchParams={{q:search.q,assignedPage:search.assignedPage,assignedPageSize:search.assignedPageSize}} page={unassigned.page} pageSize={unassigned.pageSize} total={unassigned.total} totalPages={unassigned.totalPages} pageParam="unassignedPage" pageSizeParam="unassignedPageSize"/></section>
  </AdminShell>;
}
