import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { PlayerCodeControl } from "@/components/admin/player-code-control";
import { ConfirmAction } from "@/components/confirm-action";
import { Pagination } from "@/components/pagination";
import { requireAdminSession } from "@/lib/auth/session";
import { parsePagination } from "@/lib/pagination";
import { listPlayersPaginated } from "@/lib/players";
import { getProject } from "@/lib/projects";
import { revokePlayerCodeAction, togglePlayerAction } from "./actions";
import { PlayerCreateDialog } from "./player-create-dialog";

type Search=Promise<{q?:string;page?:string;pageSize?:string}>;
export default async function PlayersPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const pagination=parsePagination(search);const [project,players]=await Promise.all([getProject(projectId),listPlayersPaginated(projectId,search.q,pagination)]);if(!project)notFound();const path=`/admin/projects/${projectId}/players`;
  return <AdminShell projectId={projectId} projectName={project.name} section="players" eyebrow={`${project.name} / Spieler`} title="Spieler">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Spieler</strong></div><h1>Spielerzugänge</h1><p>Spieler anlegen, Zugriffscodes rotieren und aktive Sitzungen zentral widerrufen. Die Liste ist serverseitig paginiert.</p></div><PlayerCreateDialog projectId={projectId}/></div>
    <section className="panel-card"><form className="filter-bar" method="get"><label className="search-box"><span aria-hidden="true">⌕</span><input name="q" defaultValue={search.q??""} placeholder="Spielername, Anzeigename oder Code-Präfix suchen …" aria-label="Spieler durchsuchen"/></label><button type="submit">Filtern</button>{search.q?<Link className="button ghost" href={path}>Zurücksetzen</Link>:null}</form><div className="table-meta"><span><strong>{players.total}</strong> Spieler</span><span>Codes werden ausschließlich gehasht gespeichert.</span></div>{players.items.length===0?<div className="empty-state large"><strong>Keine Spieler gefunden</strong><span>{search.q?"Filter ändern oder zurücksetzen.":"Lege den ersten Spieler für dieses Projekt an."}</span></div>:<div className="table-scroll"><table className="entity-table"><thead><tr><th>Spieler</th><th>Status</th><th>Code</th><th>Letzte Nutzung</th><th>Aktionen</th></tr></thead><tbody>{players.items.map((player)=>{const revokeAction=revokePlayerCodeAction.bind(null,projectId,player.userId);const toggleAction=togglePlayerAction.bind(null,projectId,player.userId,!player.active);return <tr key={player.userId}><td><strong>{player.displayName}</strong><br/><small className="muted">{player.name} · #{player.userId}</small></td><td><span className={`visibility-pill ${player.active?"all_players":"admin_only"}`}>{player.active?"Aktiv":"Deaktiviert"}</span></td><td>{player.codePrefix?<><code>{player.codePrefix}…</code>{player.revokedAt?<small className="muted"> · widerrufen</small>:null}</>:<span className="muted">Kein Code</span>}</td><td>{player.lastUsedAt?player.lastUsedAt.toLocaleString("de-DE"):<span className="muted">Nie</span>}</td><td><div className="stack compact-stack">{player.active?<PlayerCodeControl projectId={projectId} playerId={player.userId}/>:null}{player.codePrefix&&!player.revokedAt?<ConfirmAction action={revokeAction} title={`Code von ${player.displayName} widerrufen?`} description="Der aktive Zugriffscode und bestehende Spieler-Sitzungen werden widerrufen. Der Spieler-Datensatz bleibt bestehen." triggerLabel="Code widerrufen…" confirmLabel="Code widerrufen"/>:null}<ConfirmAction action={toggleAction} title={`${player.displayName} ${player.active?"deaktivieren":"aktivieren"}?`} description={player.active?"Der Spieler kann sich nicht mehr anmelden; aktive Sitzungen werden widerrufen.":"Der Spieler wird wieder aktiv. Ein neuer Zugriffscode kann anschließend ausgegeben werden."} triggerLabel={player.active?"Spieler deaktivieren…":"Spieler aktivieren…"} confirmLabel={player.active?"Spieler deaktivieren":"Spieler aktivieren"}/></div></td></tr>;})}</tbody></table></div>}<Pagination pathname={path} searchParams={{q:search.q}} page={players.page} pageSize={players.pageSize} total={players.total} totalPages={players.totalPages}/></section>
  </AdminShell>;
}
