import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { Pagination } from "@/components/pagination";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { listMediaPaginated } from "@/lib/media";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";
import { deleteMediaAction, updateMediaMetadataAction, uploadMediaAction } from "./actions";

type Search=Promise<{q?:string;entityType?:string;page?:string;pageSize?:string}>;
export default async function MediaPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [{projectId:raw},search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const pagination=parsePagination(search);const [project,media]=await Promise.all([getProject(projectId),listMediaPaginated(projectId,{query:search.q,entityType:search.entityType},pagination)]);if(!project)notFound();const path=`/admin/projects/${projectId}/media`;const hasFilters=Boolean(search.q||search.entityType);
  return <AdminShell projectId={projectId} projectName={project.name} section="media" eyebrow={`${project.name} / Wissen`} title="Media">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Media</strong></div><h1>Medienbibliothek</h1><p>Dateityp und Bilddimensionen werden aus dem tatsächlichen Dateiinhalt geprüft; interne Dateinamen sind zufällig. Bilder, die noch von einer Entity verwendet werden, können nicht gelöscht werden.</p></div><details className="create-dropdown"><summary className="button primary">＋ Bild hochladen</summary><div className="create-popover"><form action={uploadMediaAction.bind(null,projectId)} className="stack"><label>Datei<input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/gif" required/></label><label>Titel<input name="title"/></label><label>Alt-Text<input name="altText"/></label><div className="field-grid two"><label>Entity Type<input name="entityType" placeholder="person, group, location …"/></label><label>Entity ID<input name="entityId" type="number" min="1"/></label></div><SubmitButton className="primary" pendingLabel="Bild wird hochgeladen …">Sicher hochladen</SubmitButton></form></div></details></div>
    <section className="panel-card"><form className="filter-bar" method="get"><label className="search-box"><span aria-hidden="true">⌕</span><input name="q" defaultValue={search.q??""} placeholder="Titel, Alt-Text oder Dateiname suchen …"/></label><input name="entityType" defaultValue={search.entityType??""} placeholder="Entity Type"/><button>Filtern</button>{hasFilters?<Link className="button ghost" href={path}>Zurücksetzen</Link>:null}</form><div className="table-meta"><span><strong>{media.total}</strong> Medien</span><span>Standardlimit 10 MB · Bilder werden in der Liste lazy geladen</span></div>{media.items.length===0?<div className="empty-state large"><strong>Keine Medien gefunden</strong><span>{hasFilters?"Filter ändern oder zurücksetzen.":"Lade das erste Bild hoch."}</span></div>:<div className="entity-card-grid">{media.items.map((item)=><article className="panel-card nested-card" key={item.media_id}><img src={`/api/media/${item.media_id}`} alt={item.alt_text??""} loading="lazy" decoding="async" style={{maxWidth:"100%",maxHeight:240,objectFit:"contain"}}/><strong>{item.title||item.original_filename||`Media #${item.media_id}`}</strong><small>{item.mime_type} · {item.size_bytes?`${Math.ceil(Number(item.size_bytes)/1024)} KB`:"extern"}</small><small>{item.entity_type?`${item.entity_type} #${item.entity_id}`:"Galerie"}</small><details><summary className="button ghost">Metadaten bearbeiten…</summary><form action={updateMediaMetadataAction.bind(null,projectId,Number(item.media_id))} className="stack"><label>Titel<input name="title" defaultValue={item.title??""}/></label><label>Alt-Text<textarea name="altText" defaultValue={item.alt_text??""}/></label><SubmitButton pendingLabel="Metadaten werden gespeichert …">Speichern</SubmitButton></form></details><ConfirmAction action={deleteMediaAction.bind(null,projectId,Number(item.media_id))} title={`${item.title||item.original_filename||`Media #${item.media_id}`} löschen?`} description="Das Bild wird nur gelöscht, wenn keine Entity es mehr über image_media_id referenziert. Referenzierte Bilder bleiben geschützt." triggerLabel="Löschen…" confirmLabel="Bild löschen"/></article>)}</div>}<Pagination pathname={path} searchParams={{q:search.q,entityType:search.entityType}} page={media.page} pageSize={media.pageSize} total={media.total} totalPages={media.totalPages}/></section>
  </AdminShell>;
}
