import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { getTimelineEvent } from "@/lib/entities/timeline";
import { listLocations } from "@/lib/entities/locations";
import { getProject } from "@/lib/projects";
import { archiveTimelineEventAction, updateTimelineEventAction } from "../actions";

export default async function TimelineDetailPage({params}:{params:Promise<{projectId:string;eventId:string}>}){
 await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);const eventId=Number.parseInt(raw.eventId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(eventId)||projectId<=0||eventId<=0)notFound();const [project,event,locations]=await Promise.all([getProject(projectId),getTimelineEvent(projectId,eventId),listLocations(projectId)]);if(!project||!event)notFound();
 return <AdminShell projectId={projectId} projectName={project.name} title={String(event.name)} eyebrow={`${project.name} / Timeline`}>
  <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/timeline`}>Timeline</Link><span>/</span><strong>{String(event.name)}</strong></div>
  <form action={updateTimelineEventAction.bind(null,projectId,eventId)} className="npc-detail-grid"><div className="stack detail-main"><section className="panel-card edit-section"><div className="field-grid two"><label>Name<input name="name" defaultValue={String(event.name)} required/></label><label>Display Date<input name="displayDate" defaultValue={event.display_date?String(event.display_date):""}/></label><label>Sort Value<input name="sortValue" type="number" step="0.000001" defaultValue={event.sort_value?String(event.sort_value):""}/></label><label>Ära<input name="era" defaultValue={event.era?String(event.era):""}/></label><label>Jahr<input name="fantasyYear" type="number" defaultValue={event.fantasy_year!=null?String(event.fantasy_year):""}/></label><label>Monat<input name="fantasyMonth" type="number" defaultValue={event.fantasy_month!=null?String(event.fantasy_month):""}/></label><label>Tag<input name="fantasyDay" type="number" defaultValue={event.fantasy_day!=null?String(event.fantasy_day):""}/></label><label>Location<select name="locationId" defaultValue={event.loc_id?String(event.loc_id):""}><option value="">—</option>{locations.map((l)=><option key={l.loc_id} value={l.loc_id}>{l.name}</option>)}</select></label><label>Kategorie<input name="category" defaultValue={event.category?String(event.category):""}/></label><label>Wichtigkeit<input name="importance" type="number" min="0" max="10" defaultValue={String(event.importance)}/></label><label>Bild<input name="image" defaultValue={String(event.image)==="noimage"?"":String(event.image)}/></label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={String(event.visibility_mode)}><option value="admin_only">Admin only</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div><label>Beschreibung<textarea name="notes" className="large-textarea" defaultValue={String(event.notes)}/></label></section><div className="sticky-savebar"><div><strong>Event speichern</strong><span>Fantasy-Sortierung bleibt unabhängig vom Anzeigetext.</span></div><button className="primary">Speichern</button></div></div></form>
  <section className="danger-zone"><div><h2>Event archivieren</h2><p>Keine harte Löschung.</p></div><form action={archiveTimelineEventAction.bind(null,projectId,eventId)}><button className="danger">Archivieren</button></form></section>
 </AdminShell>;
}
