import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityPicker } from "@/components/entity-picker";
import { FantasyDateInput } from "@/components/fantasy-date-input";
import { ImageSourceInput } from "@/components/image-source-input";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { calendarStatus, getProjectCalendar } from "@/lib/calendar";
import { getTimelineEvent } from "@/lib/entities/timeline";
import type { FantasyDate } from "@/lib/fantasy-calendar";
import { getProject } from "@/lib/projects";
import { listResolvedTimelineLinks } from "@/lib/timeline-links";
import { archiveTimelineEventAction, linkTimelineEntityAction, unlinkTimelineEntityAction, updateTimelineEventAction } from "../actions";

function validImage(value:string|null){return Boolean(value&&value.trim()&&value!=="noimage");}
export default async function TimelineDetailPage({params}:{params:Promise<{projectId:string;eventId:string}>}){
 await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);const eventId=Number.parseInt(raw.eventId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(eventId)||projectId<=0||eventId<=0)notFound();const [project,event,calendar,links]=await Promise.all([getProject(projectId),getTimelineEvent(projectId,eventId),getProjectCalendar(projectId),listResolvedTimelineLinks(projectId,eventId)]);if(!project||!event)notFound();const ready=calendar?calendarStatus(calendar).ready:false;const value:FantasyDate|null=event.era&&event.fantasy_year!=null&&event.date_precision?{era:String(event.era)==="before"?"before":"after",year:Number(event.fantasy_year),month:event.fantasy_month==null?null:Number(event.fantasy_month),day:event.fantasy_day==null?null:Number(event.fantasy_day),precision:String(event.date_precision) as FantasyDate["precision"]}:null;
 return <AdminShell projectId={projectId} projectName={project.name} section="timeline" title={String(event.name)} eyebrow={`${project.name} / Timeline`}>
  <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/timeline`}>Timeline</Link><span>/</span><strong>{String(event.name)}</strong></div>
  <section className="entity-hero"><div className="entity-avatar hero-avatar">{String(event.image)!=="noimage"?<img src={String(event.image)} alt="" loading="lazy"/>:String(event.name).slice(0,1).toUpperCase()}</div><div className="entity-hero-main"><span className="page-kicker">EVENT #{eventId}</span><h1>{String(event.name)}</h1><div className="hero-tags"><span className="soft-label">{event.display_date?String(event.display_date):"Datum unbekannt"}</span><span className="soft-label">{event.category?String(event.category):"Event"}</span></div></div></section>
  <form action={updateTimelineEventAction.bind(null,projectId,eventId)} className="npc-detail-grid"><div className="stack detail-main"><section className="panel-card edit-section"><div className="field-grid two"><label>Name<input name="name" defaultValue={String(event.name)} required/></label><EntityPicker projectId={projectId} name="locationId" types={["location"]} label="Location" placeholder="Location suchen …" initialValue={event.loc_id?String(event.loc_id):""} initialLabel={event.location_name?String(event.location_name):""} initialKind="Location"/><label>Kategorie<input name="category" defaultValue={event.category?String(event.category):""}/></label><label>Wichtigkeit<input name="importance" type="number" min="0" max="10" defaultValue={String(event.importance)}/></label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={String(event.visibility_mode)}><option value="admin_only">Admin only</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div>{calendar&&ready?<FantasyDateInput prefix="event" label="Event-Datum" months={calendar.months} beforeEraLabel={calendar.beforeEraLabel} afterEraLabel={calendar.afterEraLabel} hasYearZero={calendar.hasYearZero} value={value} allowUnknown={false}/>:<div className="notice warning">Der Weltkalender ist noch nicht gültig. Legacy-Datum: {String(event.display_date??"—")}. <Link href={`/admin/projects/${projectId}/settings/calendar`}>Kalender öffnen</Link></div>}<ImageSourceInput current={String(event.image)} label="Event-Bild"/><label>Beschreibung<textarea name="notes" className="large-textarea" defaultValue={String(event.notes)}/></label></section><div className="sticky-savebar"><div><strong>Event speichern</strong><span>Anzeige und Sortierung werden aus dem Fantasy-Datum berechnet.</span></div><SubmitButton className="primary" pendingLabel="Speichere Event …">Speichern</SubmitButton></div></div></form>
  <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">VERKNÜPFUNGEN</span><h2>Event-Bezüge</h2></div><strong>{links.length}</strong></div><details className="create-dropdown"><summary className="button primary">＋ Verknüpfen</summary><div className="create-popover"><form action={linkTimelineEntityAction.bind(null,projectId,eventId)} className="stack"><EntityPicker projectId={projectId} name="entityRef" types={["person","group","location"]} label="Person, Gruppe oder Location" placeholder="Entität suchen …" required allowClear={false} includeTypeInValue/><label>Rolle / Bedeutung<input name="role"/></label><SubmitButton pendingLabel="Verknüpfe …">Verknüpfen</SubmitButton></form></div></details>{links.length?<div className="stack">{links.map((link)=><div className="row panel-card nested-card" key={`${link.entity_type}-${link.entity_id}`}><span className="entity-cell"><span className="entity-avatar">{validImage(link.image)?<img src={link.image!} alt="" loading="lazy"/>:link.name.slice(0,1).toUpperCase()}</span><span><strong>{link.name}</strong><small>{link.kind}{link.link_role?` · ${link.link_role}`:""}</small></span></span><ConfirmAction action={unlinkTimelineEntityAction.bind(null,projectId,eventId,link.entity_type,Number(link.entity_id))} title={`${link.name} vom Event lösen?`} description="Nur diese Event-Verknüpfung wird entfernt. Die verknüpfte Entität bleibt unverändert." triggerLabel="Entfernen…" confirmLabel="Verknüpfung entfernen"/></div>)}</div>:<div className="empty-state">Noch keine Bezüge.</div>}</section>
  <section className="danger-zone"><div><h2>Event archivieren</h2><p>Keine harte Löschung.</p></div><ConfirmAction action={archiveTimelineEventAction.bind(null,projectId,eventId)} title={`${String(event.name)} archivieren?`} description="Das Event verschwindet aus aktiven Timeline-Listen, wird aber nicht hart gelöscht." triggerLabel="Archivieren…" confirmLabel="Event archivieren" triggerClassName="button danger"/></section>
 </AdminShell>;
}
