import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityImageFrame } from "@/components/entity-image-frame";
import { EntityPicker } from "@/components/entity-picker";
import { FantasyDateInput } from "@/components/fantasy-date-input";
import { FormRequiredLegend } from "@/components/form-ui";
import { ImageSourceInput } from "@/components/image-source-input";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { calendarStatus, getProjectCalendar } from "@/lib/calendar";
import { getTimelineEvent } from "@/lib/entities/timeline";
import type { FantasyDate } from "@/lib/fantasy-calendar";
import { getProject } from "@/lib/projects";
import { listResolvedTimelineLinks } from "@/lib/timeline-links";
import { archiveTimelineEventAction, unlinkTimelineEntityAction, updateTimelineEventAction } from "../actions";
import { TimelineLinkDialog } from "./timeline-link-dialog";

function validImage(value:string|null){return Boolean(value&&value.trim()&&value!=="noimage"&&value!=="/noimg.jpg");}
export default async function TimelineDetailPage({params}:{params:Promise<{projectId:string;eventId:string}>}){
 await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);const eventId=Number.parseInt(raw.eventId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(eventId)||projectId<=0||eventId<=0)notFound();const [project,event,calendar,links]=await Promise.all([getProject(projectId),getTimelineEvent(projectId,eventId),getProjectCalendar(projectId),listResolvedTimelineLinks(projectId,eventId)]);if(!project||!event)notFound();const ready=calendar?calendarStatus(calendar).ready:false;const value:FantasyDate|null=event.era&&event.fantasy_year!=null&&event.date_precision?{era:String(event.era)==="before"?"before":"after",year:Number(event.fantasy_year),month:event.fantasy_month==null?null:Number(event.fantasy_month),day:event.fantasy_day==null?null:Number(event.fantasy_day),precision:String(event.date_precision) as FantasyDate["precision"]}:null;const name=String(event.name);
 return <AdminShell projectId={projectId} projectName={project.name} section="timeline" title={name} eyebrow={`${project.name} / Timeline`}>
  <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/timeline`}>Timeline</Link><span>/</span><strong>{name}</strong></div>
  <section className="entity-hero"><EntityImageFrame className="entity-avatar hero-avatar" src={validImage(String(event.image))?String(event.image):null} fallback={name.slice(0,1).toUpperCase()} alt={`${name} – Ereignisbild`}/><div className="entity-hero-main"><span className="page-kicker">EREIGNIS #{eventId}</span><h1>{name}</h1><div className="hero-tags"><span className="soft-label">{event.display_date?String(event.display_date):"Datum unbekannt"}</span><span className="soft-label">{event.category?String(event.category):"Ereignis"}</span></div></div></section>
  <form action={updateTimelineEventAction.bind(null,projectId,eventId)} className="npc-detail-grid"><div className="stack detail-main"><FormRequiredLegend/><section className="panel-card edit-section"><div className="field-grid two"><label>Name<input name="name" maxLength={100} defaultValue={name} required/></label><EntityPicker projectId={projectId} name="locationId" types={["location"]} label="Ort" placeholder="Optionalen Ort suchen …" initialValue={event.loc_id?String(event.loc_id):""} initialLabel={event.location_name?String(event.location_name):""} initialKind="Ort" hint="Optional · eine unveränderte historische Ortsreferenz bleibt erhalten."/><label>Kategorie <span className="muted">optional</span><input name="category" maxLength={80} defaultValue={event.category?String(event.category):""}/></label><label>Wichtigkeit<input name="importance" type="number" min="0" max="10" step="1" defaultValue={String(event.importance)}/></label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={String(event.visibility_mode)}><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte Spieler</option></select></label></div>{calendar&&ready?<FantasyDateInput prefix="event" label="Ereignisdatum" months={calendar.months} beforeEraLabel={calendar.beforeEraLabel} afterEraLabel={calendar.afterEraLabel} hasYearZero={calendar.hasYearZero} value={value} allowUnknown={false}/>:<div className="notice warning">Der Weltkalender ist noch nicht gültig. Legacy-Datum: {String(event.display_date??"—")}. <Link href={`/admin/projects/${projectId}/settings/calendar`}>Kalender öffnen</Link></div>}<ImageSourceInput current={String(event.image)} label="Ereignisbild"/><label>Beschreibung <span className="muted">optional</span><textarea name="notes" className="large-textarea" maxLength={100000} defaultValue={String(event.notes)}/></label></section><div className="sticky-savebar"><div><strong>Ereignisdaten speichern</strong><span>Anzeige und Sortierung werden aus dem Fantasy-Datum berechnet.</span></div><SubmitButton className="primary" pendingLabel="Ereignis wird gespeichert …">Ereignisdaten speichern</SubmitButton></div></div></form>
  <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">VERKNÜPFUNGEN</span><h2>Ereignis-Bezüge</h2></div><div className="row"><strong>{links.length}</strong><TimelineLinkDialog projectId={projectId} eventId={eventId}/></div></div>{links.length?<div className="stack">{links.map((link)=><div className="row panel-card nested-card" key={`${link.entity_type}-${link.entity_id}`}><span className="entity-cell"><EntityImageFrame className="entity-avatar" mode="thumbnail" src={validImage(link.image)?link.image:null} fallback={link.name.slice(0,1).toUpperCase()} alt=""/><span><strong>{link.name}</strong><small>{link.kind}{link.link_role?` · ${link.link_role}`:""}</small></span></span><ConfirmAction action={unlinkTimelineEntityAction.bind(null,projectId,eventId,link.entity_type,Number(link.entity_id))} title={`${link.name} vom Ereignis lösen?`} description="Nur diese Ereignis-Verknüpfung wird entfernt. Die verknüpfte Entität bleibt unverändert." triggerLabel="Entfernen…" confirmLabel="Verknüpfung entfernen"/></div>)}</div>:<div className="empty-state">Noch keine Bezüge.</div>}</section>
  <section className="danger-zone"><div><h2>Ereignis archivieren</h2><p>Der Datensatz wird nicht hart gelöscht.</p></div><ConfirmAction action={archiveTimelineEventAction.bind(null,projectId,eventId)} title={`${name} archivieren?`} description="Das Ereignis verschwindet aus aktiven Timeline-Listen, wird aber nicht hart gelöscht." triggerLabel="Archivieren…" confirmLabel="Ereignis archivieren" triggerClassName="button danger"/></section>
 </AdminShell>;
}
