import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityPicker } from "@/components/entity-picker";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { getFamilyTreeGraph } from "@/lib/entities/family-trees";
import { entityListImageUrl } from "@/lib/entity-image-url";
import { getProjectEntityOption } from "@/lib/entity-search";
import { familyChronologyWarnings, getFamilyChronology } from "@/lib/family-chronology";
import { getProject } from "@/lib/projects";
import { FamilyTreeCanvas } from "../family-tree-canvas";
import { addFamilyTreeMemberAction, deleteFamilyTreeAction, refreshFamilyTreeAction, updateFamilyTreeAction } from "../actions";
import styles from "../family-trees.module.css";

type Search=Promise<{personId?:string}>;
export default async function FamilyTreeDetailPage({params,searchParams}:{params:Promise<{projectId:string;treeId:string}>;searchParams:Search}){
  await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);const treeRef=raw.treeId==="all"?"all" as const:Number.parseInt(raw.treeId,10);if(!Number.isSafeInteger(projectId)||projectId<=0||(treeRef!=="all"&&(!Number.isSafeInteger(treeRef)||treeRef<=0)))notFound();
  const requested=Number.parseInt(search.personId??"",10);const requestedPromise=Number.isSafeInteger(requested)&&requested>0?getProjectEntityOption(projectId,"person",requested):Promise.resolve(null);
  const [project,graph,requestedPerson]=await Promise.all([getProject(projectId),getFamilyTreeGraph(projectId,treeRef),requestedPromise]);if(!project||!graph)notFound();
  const chronology=await getFamilyChronology(projectId,graph.people.map((person)=>person.personId));const warnings=familyChronologyWarnings(graph.edges,chronology);const people=graph.people.map((person)=>{const entry=chronology.get(person.personId);const life=entry?.lifeLabel;const birthYear=entry?.birth?entry.birth.era==="before"?-entry.birth.year:entry.birth.year:null;return{...person,image:entityListImageUrl(projectId,"person",person.personId,person.image)??"noimage",birthYear,title:[person.title,life].filter(Boolean).join(" · ")||null};});const rootPersonId=Number(graph.tree.root_person_id)||null;const rootPerson=rootPersonId?graph.people.find((person)=>person.personId===rootPersonId):null;const named=treeRef!=="all";
  return <AdminShell projectId={projectId} projectName={project.name} section="family-trees" eyebrow={`${project.name} / Stammbäume`} title={graph.tree.name||`Stammbaum #${treeRef}`}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/family-trees`}>Stammbäume</Link><span>/</span><strong>{graph.tree.name||`Stammbaum #${treeRef}`}</strong></div>
    <div className="page-heading compact-heading"><div><h1>{graph.tree.name||`Stammbaum #${treeRef}`}</h1><p>{graph.tree.subtitle||graph.tree.description||"Genealogischer Stammbaum. Parent→Child bleibt die Hierarchie; Fantasy-Lebensdaten ergänzen Anzeige und Plausibilitätsprüfung."}</p></div><div className="heading-actions"><Link className="button primary" href={`/admin/projects/${projectId}/relationships?create=1`}>＋ Familienbeziehung</Link><Link className="button" href={`/admin/projects/${projectId}/relationships`}>Beziehungen verwalten</Link></div></div>
    {warnings.length?<div className="notice warning"><strong>{warnings.length} Chronologie-Warnung{warnings.length===1?"":"en"}</strong><ul>{warnings.slice(0,12).map((warning,index)=><li key={`${warning.parentId}-${warning.childId}-${index}`}>{warning.message}</li>)}</ul>{warnings.length>12?<p>Weitere {warnings.length-12} Warnungen ausgeblendet.</p>:null}<p>Es wird nichts automatisch korrigiert.</p></div>:null}
    {named?<div className={styles.toolbar}>
      <section className={`panel-card ${styles.toolCard}`}><h2>Stammbaum bearbeiten</h2><form action={updateFamilyTreeAction.bind(null,projectId,treeRef)} className="stack"><label>Name<input name="name" defaultValue={graph.tree.name??""}/></label><label>Untertitel<input name="subtitle" defaultValue={graph.tree.subtitle??""}/></label><label>Beschreibung<textarea name="description" defaultValue={graph.tree.description??""}/></label><EntityPicker projectId={projectId} name="rootPersonId" types={["person"]} label="Root-Person" placeholder="Person suchen …" initialValue={rootPersonId?String(rootPersonId):""} initialLabel={rootPerson?.name??(rootPersonId?`Person #${rootPersonId}`:"")} initialKind={rootPerson?.kind??""}/><label>Sichtbarkeit<select name="visibilityMode" defaultValue={graph.tree.visibility_mode??"admin_only"}><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label><SubmitButton pendingLabel="Definition wird gespeichert …">Definition speichern</SubmitButton></form></section>
      <section className={`panel-card ${styles.toolCard}`}><h2>Familienzweig synchronisieren</h2><p>Übernimmt alle über Family-Relationships verbundenen Verwandten der Root-Person.</p><form action={refreshFamilyTreeAction.bind(null,projectId,treeRef)}><SubmitButton className="primary" pendingLabel="Familie wird synchronisiert …">↻ Verbundene Familie ergänzen</SubmitButton></form></section>
      <section className={`panel-card ${styles.toolCard}`}><h2>Person hinzufügen</h2><form action={addFamilyTreeMemberAction.bind(null,projectId,treeRef)} className="stack"><EntityPicker projectId={projectId} name="personId" types={["person"]} label="Person" placeholder="Person suchen …" required allowClear={false} excludeFamilyTreeId={treeRef} initialValue={requestedPerson?String(requestedPerson.entityId):""} initialLabel={requestedPerson?.name??""} initialKind={requestedPerson?.kind??""}/><div className="field-grid two"><input name="roleLabel" placeholder="Rolle im Tree"/><input name="branchLabel" placeholder="Branch / Linie"/></div><SubmitButton pendingLabel="Person wird hinzugefügt …">Hinzufügen</SubmitButton></form></section>
    </div>:null}
    <div className={styles.legend}><span><i className={styles.mainLegend}/> Hauptlinie</span><span><i/> Eltern / Kinder</span><span><i className={styles.partner}/> Partner</span><span>{people.length} Personen · {graph.edges.length} Familienkanten</span><span>Geburtsjahre beeinflussen die Generationsausrichtung, wenn genügend Chronologiedaten vorhanden sind</span></div>
    {people.length===0?<div className={`panel-card ${styles.empty}`}>Dieser Stammbaum enthält noch keine Personen.</div>:<FamilyTreeCanvas projectId={projectId} people={people} edges={graph.edges} rootPersonId={rootPersonId} named={named} treeId={treeRef} savedMainLinePersonIds={graph.mainLinePersonIds}/>} 
    {named?<section className="danger-zone"><div><h2>Stammbaum löschen</h2><p>Nur die benannte Tree-Definition und Memberships werden gelöscht. Kanonische Relationships bleiben erhalten.</p></div><ConfirmAction action={deleteFamilyTreeAction.bind(null,projectId,treeRef)} title={`${graph.tree.name||`Stammbaum #${treeRef}`} löschen?`} description="Nur die benannte Tree-Definition und ihre Memberships werden entfernt. Kanonische Relationships und Personen bleiben erhalten." triggerLabel="Stammbaum löschen…" confirmLabel="Stammbaum löschen" triggerClassName="button danger"/></section>:null}
  </AdminShell>;
}