import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { calendarStatus, getProjectCalendar, legacyCalendarAudit } from "@/lib/calendar";
import { currentFantasyDate, formatFantasyDate } from "@/lib/fantasy-calendar";
import { getProject } from "@/lib/projects";
import { addMonthAction, deleteMonthAction, migrateLegacyAgesAction, moveMonthAction, saveCalendarAction, updateMonthAction } from "./actions";

export default async function CalendarSettingsPage({params}:{params:Promise<{projectId:string}>}){
  await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();
  const [project,calendar,audit]=await Promise.all([getProject(projectId),getProjectCalendar(projectId),legacyCalendarAudit(projectId)]);if(!project)notFound();
  const status=calendarStatus(calendar);const months=calendar?.months??[];
  return <AdminShell projectId={projectId} projectName={project.name} section="calendar" eyebrow={`${project.name} / Einstellungen`} title="Weltkalender">
    <div className="page-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Weltkalender</strong></div><h1>Fantasy-Zeitrechnung</h1><p>Projektweite Zeitquelle für Alter, Geburtsdaten, Timeline und Stammbäume. Keine Gregorian-Date-Annahmen.</p></div>{calendar?<span className={`soft-label ${status.ready?"success":"warning"}`}>{status.ready?"Kalender aktiv":"Konfiguration unvollständig"}</span>:null}</div>

    {!calendar?<section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">ERSTEINRICHTUNG</span><h2>Weltkalender anlegen</h2></div></div><p>Zum Start wird ein neutraler Monat „Jahreslauf“ mit allen Jahrestagen angelegt. Danach kannst du ihn in beliebige Fantasy-Monate aufteilen.</p><form action={saveCalendarAction.bind(null,projectId)} className="stack"><div className="field-grid two"><label>Name<input name="name" defaultValue="Weltkalender" required/></label><label>Tage pro Jahr<input name="daysPerYear" type="number" min="1" defaultValue="360" required/></label><label>Vor-Epoche<input name="beforeEraLabel" defaultValue="v.Z." required/></label><label>Nach-Epoche<input name="afterEraLabel" defaultValue="n.Z." required/></label><label><input name="hasYearZero" type="checkbox"/> Jahr 0 verwenden</label><label>Aktuelle Ära<select name="currentEra" defaultValue="after"><option value="before">vor der Epoche</option><option value="after">nach der Epoche</option></select></label><label>Aktuelles Jahr<input name="currentYear" type="number" min="1" defaultValue="1"/></label><input type="hidden" name="currentMonth" value="1"/><input type="hidden" name="currentDay" value="1"/></div><button className="primary">Kalender anlegen</button></form></section>:<>
      <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">KALENDER</span><h2>{calendar.name}</h2></div><span className="record-id">calendar #{calendar.calendarId}</span></div>{status.errors.length?<div className="notice warning"><strong>Kalender noch nicht konsistent</strong><ul>{status.errors.map((error)=><li key={error}>{error}</li>)}</ul></div>:<div className="notice success"><strong>Aktuelles Weltdatum:</strong> {formatFantasyDate(currentFantasyDate(calendar),calendar)}</div>}<form action={saveCalendarAction.bind(null,projectId)} className="stack"><div className="field-grid two"><label>Name<input name="name" defaultValue={calendar.name} required/></label><label>Tage pro Jahr<input name="daysPerYear" type="number" min="1" defaultValue={calendar.daysPerYear} required/></label><label>Vor-Epoche<input name="beforeEraLabel" defaultValue={calendar.beforeEraLabel} required/></label><label>Nach-Epoche<input name="afterEraLabel" defaultValue={calendar.afterEraLabel} required/></label><label><input name="hasYearZero" type="checkbox" defaultChecked={calendar.hasYearZero}/> Jahr 0 verwenden</label><label>Aktuelle Ära<select name="currentEra" defaultValue={calendar.currentEra}><option value="before">{calendar.beforeEraLabel}</option><option value="after">{calendar.afterEraLabel}</option></select></label><label>Aktuelles Jahr<input name="currentYear" type="number" min={calendar.hasYearZero?0:1} defaultValue={calendar.currentYear}/></label><label>Aktueller Monat<select name="currentMonth" defaultValue={calendar.currentMonth}>{months.map((month,index)=><option key={month.monthId??month.sortOrder} value={index+1}>{month.name}</option>)}</select></label><label>Aktueller Tag<input name="currentDay" type="number" min="1" defaultValue={calendar.currentDay}/></label></div><div className="row"><button className="primary">Kalender & Weltdatum speichern</button><span className="muted">Monatssumme: {status.monthDays} / {calendar.daysPerYear} Tage</span></div></form></section>

      <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">MONATE</span><h2>Monatsstruktur</h2></div><span>{months.length} Monate</span></div><p className="section-help">Monate sind frei benennbar. Die Summe muss am Ende exakt den Tagen pro Jahr entsprechen. Änderungen mit bereits verwendeten Datumswerten werden serverseitig geschützt.</p><div className="stack">{months.map((month,index)=><form key={month.monthId} action={updateMonthAction.bind(null,projectId,month.monthId!)} className="panel-card nested-card"><div className="field-grid two"><label>Name<input name="name" defaultValue={month.name} required/></label><label>Tage<input name="days" type="number" min="1" defaultValue={month.days} required/></label></div><div className="row"><button>Speichern</button><button formAction={moveMonthAction.bind(null,projectId,month.monthId!,"up")} disabled={index===0}>↑</button><button formAction={moveMonthAction.bind(null,projectId,month.monthId!,"down")} disabled={index===months.length-1}>↓</button><details><summary className="button ghost">Löschen…</summary><p>Nur möglich, wenn keine gespeicherten Datumswerte diesen Monat verwenden.</p><button className="danger" formAction={deleteMonthAction.bind(null,projectId,month.monthId!)}>Wirklich löschen</button></details></div></form>)}</div><form action={addMonthAction.bind(null,projectId)} className="panel-card nested-card"><strong>＋ Monat hinzufügen</strong><div className="field-grid two"><label>Name<input name="name" placeholder="z. B. Frostmond" required/></label><label>Tage<input name="days" type="number" min="1" defaultValue="30" required/></label></div><button>Hinzufügen</button></form></section>
    </>}

    <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">LEGACY-MIGRATION</span><h2>Alter & Species/Race Audit</h2></div></div><div className="stat-grid"><div><strong>{audit.total}</strong><span>Characters geprüft</span></div><div><strong>{audit.with_age}</strong><span>mit Legacy-Alter</span></div><div><strong>{audit.with_birthday}</strong><span>mit Legacy-Birthday</span></div><div><strong>{audit.conflicts}</strong><span>Race/Species-Konflikte</span></div><div><strong>{audit.migrated}</strong><span>migriert</span></div><div><strong>{audit.pending}</strong><span>offen</span></div></div><p>Automatisch migriert werden nur reine Altersangaben: daraus entsteht ein <code>approximate_year</code>. Ein vorhandener Legacy-Birthday wird nicht als Fantasy-Datum interpretiert und bleibt zur Prüfung offen. Ist <code>charakters.race</code> leer/unknown und <code>npcs.species</code> vorhanden, darf Race sicher daraus befüllt werden; unterschiedliche Werte werden nie überschrieben.</p><form action={migrateLegacyAgesAction.bind(null,projectId)}><details><summary className="button">Legacy-Alter migrieren…</summary><div className="notice warning"><strong>Kein erfundener Geburtstag:</strong> Es werden nur ungefähre Geburtsjahre aus Alter + aktuellem Weltdatum abgeleitet. Legacy-Felder bleiben bestehen.</div><button className="primary" disabled={!calendar||!status.ready}>Migration jetzt ausführen</button></details></form></section>
  </AdminShell>;
}
