import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { FormRequiredLegend } from "@/components/form-ui";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { calendarStatus, getProjectCalendar, legacyCalendarAudit } from "@/lib/calendar";
import { currentFantasyDate, formatFantasyDate } from "@/lib/fantasy-calendar";
import { getProject } from "@/lib/projects";
import { addMonthAction, deleteMonthAction, migrateLegacyAgesAction, moveMonthAction, saveCalendarAction, updateMonthAction } from "./actions";
import { CalendarCurrentDateInput } from "./calendar-current-date-input";

export default async function CalendarSettingsPage({params}:{params:Promise<{projectId:string}>}){
  await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();
  const [project,calendar,audit]=await Promise.all([getProject(projectId),getProjectCalendar(projectId),legacyCalendarAudit(projectId)]);if(!project)notFound();
  const status=calendarStatus(calendar);const months=calendar?.months??[];const monthTotalMatches=Boolean(calendar&&status.monthDays===calendar.daysPerYear);
  return <AdminShell projectId={projectId} projectName={project.name} section="calendar" eyebrow={`${project.name} / Einstellungen`} title="Weltkalender">
    <div className="page-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Weltkalender</strong></div><h1>Fantasy-Zeitrechnung</h1><p>Projektweite Zeitquelle für Alter, Geburtsdaten, Timeline und Stammbäume. Keine Gregorian-Date-Annahmen.</p></div>{calendar?<span className={`soft-label ${status.ready?"success":"warning"}`}>{status.ready?"Kalender aktiv":"Konfiguration unvollständig"}</span>:null}</div>

    {!calendar?<section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">ERSTEINRICHTUNG</span><h2>Weltkalender anlegen</h2></div></div><p>Zum Start wird ein neutraler Monat „Jahreslauf“ mit allen Jahrestagen angelegt. Danach kannst du ihn in beliebige Fantasy-Monate aufteilen.</p><form action={saveCalendarAction.bind(null,projectId)} className="stack"><FormRequiredLegend/><div className="field-grid two"><label>Name<input name="name" maxLength={160} defaultValue="Weltkalender" required/></label><label>Tage pro Jahr<input name="daysPerYear" type="number" min="1" max="1000000" step="1" defaultValue="360" required/></label><label>Vor-Epoche<input name="beforeEraLabel" maxLength={40} defaultValue="v.Z." required/></label><label>Nach-Epoche<input name="afterEraLabel" maxLength={40} defaultValue="n.Z." required/></label><label><input name="hasYearZero" type="checkbox"/> Jahr 0 verwenden</label><label>Aktuelle Ära<select name="currentEra" defaultValue="after"><option value="before">vor der Epoche</option><option value="after">nach der Epoche</option></select></label><label>Aktuelles Jahr<input name="currentYear" type="number" min="1" max="10000000" step="1" defaultValue="1" required/></label><input type="hidden" name="currentMonth" value="1"/><input type="hidden" name="currentDay" value="1"/></div><SubmitButton className="primary" pendingLabel="Kalender wird angelegt …">Kalender anlegen</SubmitButton></form></section>:<>
      <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">KALENDER</span><h2>{calendar.name}</h2></div><span className="record-id">Kalender #{calendar.calendarId}</span></div>{status.errors.length?<div className="notice warning" role="alert"><strong>Kalender noch nicht konsistent</strong><ul>{status.errors.map((error)=><li key={error}>{error}</li>)}</ul></div>:<div className="notice success" role="status"><strong>Aktuelles Weltdatum:</strong> {formatFantasyDate(currentFantasyDate(calendar),calendar)}</div>}<form action={saveCalendarAction.bind(null,projectId)} className="stack"><FormRequiredLegend/><div className="field-grid two"><label>Name<input name="name" maxLength={160} defaultValue={calendar.name} required/></label><label>Tage pro Jahr<input name="daysPerYear" type="number" min="1" max="1000000" step="1" defaultValue={calendar.daysPerYear} required/></label><label>Vor-Epoche<input name="beforeEraLabel" maxLength={40} defaultValue={calendar.beforeEraLabel} required/></label><label>Nach-Epoche<input name="afterEraLabel" maxLength={40} defaultValue={calendar.afterEraLabel} required/></label><label><input name="hasYearZero" type="checkbox" defaultChecked={calendar.hasYearZero}/> Jahr 0 verwenden</label></div><CalendarCurrentDateInput months={months} currentMonth={calendar.currentMonth} currentDay={calendar.currentDay} currentYear={calendar.currentYear} currentEra={calendar.currentEra} hasYearZero={calendar.hasYearZero} beforeEraLabel={calendar.beforeEraLabel} afterEraLabel={calendar.afterEraLabel}/><div className="row"><SubmitButton className="primary" pendingLabel="Kalender wird gespeichert …">Kalender & Weltdatum speichern</SubmitButton><span className={`soft-label ${monthTotalMatches?"success":"warning"}`}>Monatssumme: {status.monthDays} / {calendar.daysPerYear} Tage {monthTotalMatches?"✓":"⚠"}</span></div></form></section>

      <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">MONATE</span><h2>Monatsstruktur</h2></div><span>{months.length} Monate</span></div><p className="section-help">Monate sind frei benennbar. Die Summe muss am Ende exakt den Tagen pro Jahr entsprechen. Änderungen mit bereits verwendeten Datumswerten werden serverseitig geschützt.</p><div className="stack">{months.map((month,index)=><article key={month.monthId} className="panel-card nested-card"><form action={updateMonthAction.bind(null,projectId,month.monthId!)} className="stack"><FormRequiredLegend/><div className="field-grid two"><label>Name<input name="name" maxLength={120} defaultValue={month.name} required/></label><label>Tage<input name="days" type="number" min="1" max="1000000" step="1" defaultValue={month.days} required/></label></div><SubmitButton pendingLabel="Monat wird gespeichert …">Monat speichern</SubmitButton></form><div className="row"><form action={moveMonthAction.bind(null,projectId,month.monthId!,"up")}><SubmitButton disabled={index===0} pendingLabel="↑" aria-label={`${month.name} nach oben verschieben`}>↑</SubmitButton></form><form action={moveMonthAction.bind(null,projectId,month.monthId!,"down")}><SubmitButton disabled={index===months.length-1} pendingLabel="↓" aria-label={`${month.name} nach unten verschieben`}>↓</SubmitButton></form><ConfirmAction action={deleteMonthAction.bind(null,projectId,month.monthId!)} title={`${month.name} löschen?`} description="Der Monat kann nur gelöscht werden, wenn keine gespeicherten Fantasy-Datumswerte seine Kalenderstruktur verwenden. Der Server prüft dies erneut." triggerLabel="Löschen…" confirmLabel="Monat löschen"/></div></article>)}</div><form action={addMonthAction.bind(null,projectId)} className="panel-card nested-card stack"><strong>＋ Monat hinzufügen</strong><FormRequiredLegend/><div className="field-grid two"><label>Name<input name="name" maxLength={120} placeholder="z. B. Frostmond" required/></label><label>Tage<input name="days" type="number" min="1" max="1000000" step="1" defaultValue="30" required/></label></div><SubmitButton pendingLabel="Monat wird hinzugefügt …">Monat hinzufügen</SubmitButton></form></section>
    </>}

    <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">LEGACY-MIGRATION</span><h2>Alter- & Spezies-Audit</h2></div></div><div className="stat-grid"><div><strong>{audit.total}</strong><span>Charaktere geprüft</span></div><div><strong>{audit.with_age}</strong><span>mit Legacy-Alter</span></div><div><strong>{audit.with_birthday}</strong><span>mit Legacy-Geburtstag</span></div><div><strong>{audit.conflicts}</strong><span>Spezies-Konflikte</span></div><div><strong>{audit.migrated}</strong><span>migriert</span></div><div><strong>{audit.pending}</strong><span>offen</span></div></div><p>Automatisch migriert werden nur reine Altersangaben: daraus entsteht ein <code>approximate_year</code>. Ein vorhandener Legacy-Geburtstag wird nicht als Fantasy-Datum interpretiert und bleibt zur Prüfung offen. Ist <code>charakters.race</code> leer/unbekannt und <code>npcs.species</code> vorhanden, darf die Spezies sicher daraus befüllt werden; unterschiedliche Werte werden nie überschrieben.</p><form action={migrateLegacyAgesAction.bind(null,projectId)}><details><summary className="button">Legacy-Alter migrieren…</summary><div className="notice warning"><strong>Kein erfundener Geburtstag:</strong> Es werden nur ungefähre Geburtsjahre aus Alter + aktuellem Weltdatum abgeleitet. Legacy-Felder bleiben bestehen.</div><SubmitButton className="primary" pendingLabel="Legacy-Alter werden migriert …" disabled={!calendar||!status.ready}>Migration jetzt ausführen</SubmitButton></details></form></section>
  </AdminShell>;
}
