import "server-only";

import { getProjectCalendar } from "@/lib/calendar";
import { pool } from "@/lib/db";
import { formatFantasyDate, type FantasyDate } from "@/lib/fantasy-calendar";

export type FamilyChronology = { personId:number; birth:FantasyDate|null; death:FantasyDate|null; birthOrdinal:number|null; deathOrdinal:number|null; lifeLabel:string|null };
type Row={entity_id:string;field_key:string;era:"before"|"after";year:number;month:number|null;day:number|null;precision:FantasyDate["precision"];range_end_era:"before"|"after"|null;range_end_year:number|null;range_end_month:number|null;range_end_day:number|null;ordinal_start:string|null;ordinal_end:string|null};
function date(row:Row):FantasyDate{return{era:row.era,year:row.year,month:row.month,day:row.day,precision:row.precision,rangeEnd:row.range_end_era&&row.range_end_year!=null?{era:row.range_end_era,year:row.range_end_year,month:row.range_end_month,day:row.range_end_day}:null};}
export async function getFamilyChronology(projectId:number,personIds:number[]){const ids=[...new Set(personIds)].filter((id)=>Number.isSafeInteger(id)&&id>0);const result=new Map<number,FamilyChronology>();if(!ids.length)return result;const calendar=await getProjectCalendar(projectId);const rows=await pool.query<Row>(`SELECT entity_id,field_key,era,year,month,day,precision,range_end_era,range_end_year,range_end_month,range_end_day,ordinal_start,ordinal_end FROM fantasy_dates WHERE project_id=$1 AND entity_type='person' AND entity_id=ANY($2::int[]) AND field_key IN ('birth','death')`,[projectId,ids]);const byPerson=new Map<number,{birth?:Row;death?:Row}>();for(const row of rows.rows){const personId=Number(row.entity_id);const entry=byPerson.get(personId)??{};if(row.field_key==='birth')entry.birth=row;if(row.field_key==='death')entry.death=row;byPerson.set(personId,entry);}for(const personId of ids){const entry=byPerson.get(personId)??{};const birth=entry.birth?date(entry.birth):null;const death=entry.death?date(entry.death):null;let lifeLabel:string|null=null;if(calendar){const birthLabel=birth?formatFantasyDate(birth,calendar):null;const deathLabel=death?formatFantasyDate(death,calendar):null;lifeLabel=birthLabel&&deathLabel?`${birthLabel} – ${deathLabel}`:birthLabel?`geb. ${birthLabel}`:deathLabel?`gest. ${deathLabel}`:null;}result.set(personId,{personId,birth,death,birthOrdinal:entry.birth?.ordinal_start==null?null:Number(entry.birth.ordinal_start),deathOrdinal:entry.death?.ordinal_end==null?null:Number(entry.death.ordinal_end),lifeLabel});}return result;}

export function familyChronologyWarnings(edges:Array<{a:number;b:number;code:string;directed:boolean}>,chronology:Map<number,FamilyChronology>){const warnings:Array<{parentId:number;childId:number;message:string}>=[];for(const edge of edges){if(!edge.directed||!["parent","adoptive_parent","step_parent","guardian"].includes(edge.code))continue;const parent=chronology.get(edge.a);const child=chronology.get(edge.b);if(parent?.birthOrdinal!=null&&child?.birthOrdinal!=null&&parent.birthOrdinal>child.birthOrdinal)warnings.push({parentId:edge.a,childId:edge.b,message:`Person #${edge.a} ist laut Geburtsdaten nach Person #${edge.b} geboren.`});if(parent?.deathOrdinal!=null&&child?.birthOrdinal!=null&&parent.deathOrdinal<child.birthOrdinal)warnings.push({parentId:edge.a,childId:edge.b,message:`Person #${edge.a} ist laut Chronologie vor der Geburt von Person #${edge.b} gestorben.`});}return warnings;}
