import "server-only";

import { z } from "zod";
import { pool } from "@/lib/db";

const mapSchema=z.discriminatedUnion("mapType",[
 z.object({mapType:z.literal("tile"),name:z.string().trim().min(1).max(120),tileUrl:z.string().trim().min(1).max(4000),minZoom:z.coerce.number().int().min(-10).max(30).default(0),maxZoom:z.coerce.number().int().min(-10).max(30).default(6),centerLat:z.coerce.number().finite().nullable().optional(),centerLng:z.coerce.number().finite().nullable().optional(),noWrap:z.coerce.boolean().default(true),isPrimary:z.coerce.boolean().default(false)}),
 z.object({mapType:z.literal("image"),name:z.string().trim().min(1).max(120),imagePath:z.string().trim().min(1).max(4000),minZoom:z.coerce.number().int().min(-10).max(30).default(-2),maxZoom:z.coerce.number().int().min(-10).max(30).default(4),width:z.coerce.number().positive(),height:z.coerce.number().positive(),isPrimary:z.coerce.boolean().default(false)})
]);

export async function createProjectMap(projectId:number,input:unknown){const d=mapSchema.parse(input);const client=await pool.connect();try{await client.query("BEGIN");const project=await client.query("SELECT 1 FROM campaigns WHERE camp_id=$1 AND status<>'archived' FOR UPDATE",[projectId]);if(project.rowCount!==1)throw new Error("Project not found or archived.");if(d.isPrimary)await client.query("UPDATE project_maps SET is_primary=false,updated_at=now() WHERE project_id=$1 AND is_primary",[projectId]);const config=d.mapType==="tile"?{no_wrap:d.noWrap}:{width:d.width,height:d.height,crs:"simple"};const r=await client.query<{map_id:string}>(
`INSERT INTO project_maps(project_id,name,map_type,tile_url,image_path,min_zoom,max_zoom,center_lat,center_lng,bounds,config,is_primary)
 VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb,$12) RETURNING map_id`,
[projectId,d.name,d.mapType,d.mapType==="tile"?d.tileUrl:null,d.mapType==="image"?d.imagePath:null,d.minZoom,d.maxZoom,d.mapType==="tile"?(d.centerLat??null):null,d.mapType==="tile"?(d.centerLng??null):null,d.mapType==="image"?JSON.stringify([[0,0],[d.height,d.width]]):null,JSON.stringify(config),d.isPrimary]);const id=Number(r.rows[0].map_id);if(d.isPrimary)await client.query("UPDATE campaigns SET primary_map_id=$2,updated_at=now() WHERE camp_id=$1",[projectId,id]);await client.query("COMMIT");return id;}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}

export async function setPrimaryMap(projectId:number,mapId:number){const client=await pool.connect();try{await client.query("BEGIN");const map=await client.query("SELECT 1 FROM project_maps WHERE project_id=$1 AND map_id=$2 FOR UPDATE",[projectId,mapId]);if(map.rowCount!==1)throw new Error("Map does not belong to this project.");await client.query("UPDATE project_maps SET is_primary=(map_id=$2),updated_at=now() WHERE project_id=$1",[projectId,mapId]);await client.query("UPDATE campaigns SET primary_map_id=$2,updated_at=now() WHERE camp_id=$1",[projectId,mapId]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}

export async function deleteProjectMap(projectId:number,mapId:number){const client=await pool.connect();try{await client.query("BEGIN");const map=await client.query<{is_primary:boolean}>("SELECT is_primary FROM project_maps WHERE project_id=$1 AND map_id=$2 FOR UPDATE",[projectId,mapId]);if(map.rowCount!==1)throw new Error("Map not found in this project.");if(map.rows[0].is_primary)throw new Error("Choose another primary map before deleting this map.");const markers=await client.query("SELECT 1 FROM map_markers WHERE project_id=$1 AND map_id=$2 LIMIT 1",[projectId,mapId]);if(markers.rowCount)throw new Error("Archive or move this map's markers before deleting it.");await client.query("DELETE FROM project_maps WHERE project_id=$1 AND map_id=$2",[projectId,mapId]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
