import "server-only";

import { z } from "zod";
import { pool } from "@/lib/db";

export const PERSON_LOCATION_ROLES=["current","home","birthplace","workplace","seat","origin","temporary","other"] as const;
const inputSchema=z.object({locationId:z.coerce.number().int().positive(),role:z.enum(PERSON_LOCATION_ROLES),isPrimary:z.coerce.boolean().default(false),notes:z.string().trim().max(5000).nullable().optional()});
export type PersonLocationAssignment={assignment_id:string;person_id:number;location_id:number;role:(typeof PERSON_LOCATION_ROLES)[number];is_primary:boolean;notes:string|null;location_name:string;location_kind:string;parent_name:string|null;map_id:string|null;map_feature_id:string|null};

export async function listPersonLocations(projectId:number,personId:number){const result=await pool.query<PersonLocationAssignment>(`SELECT a.assignment_id,a.person_id,a.location_id,a.role,a.is_primary,a.notes,l.name AS location_name,l.location_kind,p.name AS parent_name,l.map_id,l.map_feature_id FROM person_location_assignments a JOIN locations l ON l.loc_id=a.location_id AND l.camp_id=a.project_id LEFT JOIN locations p ON p.loc_id=l.parent_loc_id AND p.camp_id=l.camp_id WHERE a.project_id=$1 AND a.person_id=$2 AND l.archived_at IS NULL ORDER BY CASE a.role WHEN 'current' THEN 0 WHEN 'home' THEN 1 WHEN 'workplace' THEN 2 ELSE 3 END,a.is_primary DESC,l.name`,[projectId,personId]);return result.rows;}

export async function setPersonLocation(projectId:number,personId:number,input:unknown){const data=inputSchema.parse(input);const client=await pool.connect();try{await client.query("BEGIN");const person=await client.query("SELECT 1 FROM npcs WHERE camp_id=$1 AND n_id=$2 AND archived_at IS NULL",[projectId,personId]);const location=await client.query("SELECT 1 FROM locations WHERE camp_id=$1 AND loc_id=$2 AND archived_at IS NULL",[projectId,data.locationId]);if(person.rowCount!==1||location.rowCount!==1)throw new Error("Person or location does not belong to this project.");if(data.isPrimary&&data.role==="current")await client.query("DELETE FROM person_location_assignments WHERE project_id=$1 AND person_id=$2 AND role='current' AND location_id<>$3",[projectId,personId,data.locationId]);else if(data.isPrimary)await client.query("UPDATE person_location_assignments SET is_primary=false,updated_at=now() WHERE project_id=$1 AND person_id=$2 AND role=$3",[projectId,personId,data.role]);const row=await client.query<{assignment_id:string}>(`INSERT INTO person_location_assignments(project_id,person_id,location_id,role,is_primary,notes) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(project_id,person_id,location_id,role) DO UPDATE SET is_primary=EXCLUDED.is_primary,notes=EXCLUDED.notes,updated_at=now() RETURNING assignment_id`,[projectId,personId,data.locationId,data.role,data.isPrimary,data.notes??null]);if(data.role==="current"&&data.isPrimary)await client.query("UPDATE charakters SET loc_id=$2 WHERE n_id=$1",[personId,data.locationId]);await client.query("COMMIT");return Number(row.rows[0].assignment_id);}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}

export async function removePersonLocation(projectId:number,personId:number,assignmentId:number){const result=await pool.query("DELETE FROM person_location_assignments WHERE assignment_id=$1 AND project_id=$2 AND person_id=$3 AND NOT(role='current' AND is_primary)",[assignmentId,projectId,personId]);if(result.rowCount!==1)throw new Error("Assignment not found or primary current location cannot be removed.");}
