import "server-only";

import { createHash, randomInt, timingSafeEqual } from "node:crypto";
import { hash, verify } from "argon2";
import { z } from "zod";
import { pool } from "@/lib/db";
import { clampPagination, paginatedResult, type Pagination } from "@/lib/pagination";

const playerSchema = z.object({name:z.string().trim().min(1).max(120),displayName:z.string().trim().max(120).optional()});
const CODE_ALPHABET="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export type PlayerSummary={userId:number;name:string;displayName:string;active:boolean;codePrefix:string|null;lastUsedAt:Date|null;revokedAt:Date|null};
type PlayerRow={user_id:number;name:string;display_name:string|null;active:boolean;code_prefix:string|null;last_used_at:Date|null;revoked_at:Date|null};
const playerSelect=`SELECT u.user_id,u.name,u.display_name,u.active,c.code_prefix,c.last_used_at,c.revoked_at FROM users u LEFT JOIN LATERAL (SELECT code_prefix,last_used_at,revoked_at FROM player_access_codes WHERE project_id=u.camp_id AND player_id=u.user_id ORDER BY created_at DESC LIMIT 1) c ON true`;
function mapPlayer(row:PlayerRow):PlayerSummary{return{userId:row.user_id,name:row.name,displayName:row.display_name??row.name,active:row.active,codePrefix:row.code_prefix,lastUsedAt:row.last_used_at,revokedAt:row.revoked_at};}
function generateSegment(length:number){let value="";for(let index=0;index<length;index+=1)value+=CODE_ALPHABET[randomInt(0,CODE_ALPHABET.length)];return value;}
export function generatePlayerCode(){return `WR-${generateSegment(4)}-${generateSegment(4)}-${generateSegment(2)}`;}
function normalizePlayerCode(code:string){return code.trim().toUpperCase();}
function codePrefix(code:string){return normalizePlayerCode(code).slice(0,7);}

export async function listPlayers(projectId:number){const result=await pool.query<PlayerRow>(`${playerSelect} WHERE u.camp_id=$1 ORDER BY COALESCE(u.display_name,u.name),u.user_id`,[projectId]);return result.rows.map(mapPlayer);}
export async function listPlayersPaginated(projectId:number,query:string|undefined,pagination:Pagination){const values:unknown[]=[projectId];let search="";if(query?.trim()){values.push(`%${query.trim()}%`);search=` AND (u.name ILIKE $2 OR u.display_name ILIKE $2 OR c.code_prefix ILIKE $2)`;}const count=await pool.query<{total:number}>(`SELECT count(*)::int AS total FROM users u LEFT JOIN LATERAL (SELECT code_prefix FROM player_access_codes WHERE project_id=u.camp_id AND player_id=u.user_id ORDER BY created_at DESC LIMIT 1) c ON true WHERE u.camp_id=$1${search}`,values);const total=count.rows[0]?.total??0;const page=clampPagination(total,pagination);const pageValues=[...values,page.limit,page.offset];const rows=await pool.query<PlayerRow>(`${playerSelect} WHERE u.camp_id=$1${search} ORDER BY COALESCE(u.display_name,u.name),u.user_id LIMIT $${pageValues.length-1} OFFSET $${pageValues.length}`,pageValues);return paginatedResult(rows.rows.map(mapPlayer),total,page);}

export async function createPlayer(projectId:number,input:unknown){const parsed=playerSchema.parse(input);const result=await pool.query<{user_id:number}>(`INSERT INTO users(name,display_name,camp_id,active) SELECT $2,COALESCE(NULLIF($3,''),$2),c.camp_id,true FROM campaigns c WHERE c.camp_id=$1 AND c.status<>'archived' RETURNING user_id`,[projectId,parsed.name,parsed.displayName??""]);if(result.rowCount!==1)throw new Error("Project not found or archived.");await pool.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id) VALUES($1,'admin','player.created','player',$2)`,[projectId,result.rows[0].user_id]);return result.rows[0].user_id;}
export async function setPlayerActive(projectId:number,playerId:number,active:boolean){const result=await pool.query(`UPDATE users SET active=$3,updated_at=now() WHERE user_id=$2 AND camp_id=$1`,[projectId,playerId,active]);if(result.rowCount!==1)throw new Error("Player not found in this project.");if(!active)await pool.query(`UPDATE player_sessions SET revoked_at=now() WHERE project_id=$1 AND player_id=$2 AND revoked_at IS NULL`,[projectId,playerId]);}
export async function issuePlayerCode(projectId:number,playerId:number){const player=await pool.query<{user_id:number}>(`SELECT user_id FROM users WHERE camp_id=$1 AND user_id=$2 AND active=true`,[projectId,playerId]);if(player.rowCount!==1)throw new Error("Active player not found in this project.");const code=generatePlayerCode();const normalized=normalizePlayerCode(code);const codeHash=await hash(normalized,{type:2});const client=await pool.connect();try{await client.query("BEGIN");await client.query(`UPDATE player_access_codes SET active=false,revoked_at=COALESCE(revoked_at,now()) WHERE project_id=$1 AND player_id=$2 AND active=true`,[projectId,playerId]);await client.query(`INSERT INTO player_access_codes(project_id,player_id,code_prefix,code_hash) VALUES($1,$2,$3,$4)`,[projectId,playerId,codePrefix(code),codeHash]);await client.query(`INSERT INTO audit_log(project_id,actor_type,action,entity_type,entity_id,metadata) VALUES($1,'admin','player.code_issued','player',$2,$3::jsonb)`,[projectId,playerId,JSON.stringify({code_prefix:codePrefix(code)})]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}return code;}
export async function revokePlayerCode(projectId:number,playerId:number){await pool.query(`UPDATE player_access_codes SET active=false,revoked_at=COALESCE(revoked_at,now()) WHERE project_id=$1 AND player_id=$2 AND active=true`,[projectId,playerId]);await pool.query(`UPDATE player_sessions SET revoked_at=now() WHERE project_id=$1 AND player_id=$2 AND revoked_at IS NULL`,[projectId,playerId]);}
function verifyLegacySha256(code:string,storedHash:string){const computed=createHash("sha256").update(code).digest();const expected=Buffer.from(storedHash.trim(),"hex");return expected.length===computed.length&&timingSafeEqual(computed,expected);}
export async function authenticatePlayerCode(rawCode:string){const code=normalizePlayerCode(rawCode);if(!/^WR-[A-Z2-9]{4}-[A-Z2-9]{4}-[A-Z2-9]{2}$/.test(code))return null;const candidates=await pool.query<{access_code_id:string;project_id:number;player_id:number;code_hash:string}>(`SELECT c.access_code_id,c.project_id,c.player_id,c.code_hash FROM player_access_codes c JOIN users u ON u.user_id=c.player_id AND u.camp_id=c.project_id JOIN campaigns p ON p.camp_id=c.project_id WHERE c.code_prefix=$1 AND c.active=true AND c.revoked_at IS NULL AND u.active=true AND p.status<>'archived'`,[codePrefix(code)]);for(const candidate of candidates.rows){let valid=false;try{valid=candidate.code_hash.startsWith("$argon2")?await verify(candidate.code_hash,code):verifyLegacySha256(code,candidate.code_hash);}catch{valid=false;}if(!valid)continue;await pool.query(`UPDATE player_access_codes SET last_used_at=now() WHERE access_code_id=$1`,[candidate.access_code_id]);return{projectId:candidate.project_id,playerId:candidate.player_id};}return null;}
