import "server-only";

import { z } from "zod";
import { pool } from "@/lib/db";
import { assertEntityBelongsToProject } from "@/lib/entity-project";

const decoySchema=z.object({name:z.string().trim().min(1).max(200),description:z.string().max(100000).optional(),image:z.string().trim().max(4000).optional(),locationOverride:z.record(z.string(),z.unknown()).optional()});

export async function getBaseVisibility(projectId:number,entityType:string,entityId:number){await assertEntityBelongsToProject(projectId,entityType,entityId);switch(entityType){case"npc":return (await pool.query<{mode:string}>("SELECT visibility_mode AS mode FROM npcs WHERE camp_id=$1 AND n_id=$2",[projectId,entityId])).rows[0].mode;case"god":return (await pool.query<{mode:string}>("SELECT n.visibility_mode AS mode FROM gods g JOIN npcs n ON n.n_id=g.n_id WHERE n.camp_id=$1 AND g.g_id=$2",[projectId,entityId])).rows[0].mode;case"character":return (await pool.query<{mode:string}>("SELECT n.visibility_mode AS mode FROM charakters c JOIN npcs n ON n.n_id=c.n_id WHERE n.camp_id=$1 AND c.char_id=$2",[projectId,entityId])).rows[0].mode;case"location":return (await pool.query<{mode:string}>("SELECT visibility_mode AS mode FROM locations WHERE camp_id=$1 AND loc_id=$2",[projectId,entityId])).rows[0].mode;case"group":return (await pool.query<{mode:string}>("SELECT visibility_mode AS mode FROM groups WHERE camp_id=$1 AND gr_id=$2",[projectId,entityId])).rows[0].mode;case"event":return (await pool.query<{mode:string}>("SELECT visibility_mode AS mode FROM events WHERE camp_id=$1 AND e_id=$2",[projectId,entityId])).rows[0].mode;case"map_marker":return (await pool.query<{mode:string}>("SELECT visibility_mode AS mode FROM map_markers WHERE project_id=$1 AND marker_id=$2",[projectId,entityId])).rows[0].mode;case"relationship":return (await pool.query<{mode:string}>("SELECT visibility_mode AS mode FROM relationships WHERE project_id=$1 AND relationship_id=$2",[projectId,entityId])).rows[0].mode;case"media":return"admin_only";default:return"admin_only";}}

export async function createStandaloneDecoy(args:{projectId:number;playerId:number;entityType:string;input:unknown}){const data=decoySchema.parse(args.input);const player=await pool.query("SELECT 1 FROM users WHERE camp_id=$1 AND user_id=$2 AND active=true",[args.projectId,args.playerId]);if(player.rowCount!==1)throw new Error("Active player does not belong to this project.");const result=await pool.query<{variant_id:string}>(`INSERT INTO player_entity_variants(project_id,player_id,entity_type,entity_id,mode,name_override,description_override,image_override,location_override,metadata) VALUES($1,$2,$3,NULL,'standalone_decoy',$4,$5,$6,$7::jsonb,'{}'::jsonb) RETURNING variant_id`,[args.projectId,args.playerId,args.entityType,data.name,data.description||null,data.image||null,data.locationOverride?JSON.stringify(data.locationOverride):null]);return Number(result.rows[0].variant_id);}

export async function listStandaloneDecoys(projectId:number){const r=await pool.query<{variant_id:string;player_id:number;player_name:string;entity_type:string;name_override:string|null;description_override:string|null;image_override:string|null}>(`SELECT v.variant_id,v.player_id,COALESCE(u.display_name,u.name) AS player_name,v.entity_type,v.name_override,v.description_override,v.image_override FROM player_entity_variants v JOIN users u ON u.user_id=v.player_id AND u.camp_id=v.project_id WHERE v.project_id=$1 AND v.mode='standalone_decoy' ORDER BY u.name,v.entity_type,v.variant_id`,[projectId]);return r.rows;}

export async function deleteStandaloneDecoy(projectId:number,variantId:number){const r=await pool.query("DELETE FROM player_entity_variants WHERE project_id=$1 AND variant_id=$2 AND mode='standalone_decoy'",[projectId,variantId]);if(r.rowCount!==1)throw new Error("Standalone decoy not found in this project.");}
