"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminSession } from "@/lib/auth/session";
import { archiveGroup, createGroup, getGroup, removeGroupMembership, setGroupMembership, updateGroup } from "@/lib/entities/groups";
import { formCheckbox, formOptionalId, formOptionalText, formText } from "@/lib/form-data";
import { resolveEntityImageSource, setEntityImageReference } from "@/lib/media";
import { getProject } from "@/lib/projects";

function values(formData:FormData,image:string){return{name:formData.get("name"),image,notes:formOptionalText(formData,"notes")??undefined,motto:formOptionalText(formData,"motto")??undefined,locationId:formData.get("locationId"),groupType:formOptionalText(formData,"groupType")??undefined,visibilityMode:formText(formData,"visibilityMode")||"admin_only"};}
function refresh(projectId:number,groupId:number){revalidatePath(`/admin/projects/${projectId}/groups/${groupId}`);revalidatePath(`/admin/projects/${projectId}/groups`);}
async function assertProject(projectId:number){if(!Number.isSafeInteger(projectId)||projectId<=0||!(await getProject(projectId)))throw new Error("Die ausgewählte Welt wurde nicht gefunden oder ist archiviert.");}
export async function createGroupAction(projectId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);const source=await resolveEntityImageSource(projectId,formData,{title:String(formData.get("name")??"Gruppe")});const id=await createGroup(projectId,values(formData,source.image));if(source.uploaded)await setEntityImageReference(projectId,"group",id,source);redirect(`/admin/projects/${projectId}/groups/${id}`);}
export async function updateGroupAction(projectId:number,groupId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);const current=await getGroup(projectId,groupId);if(!current)throw new Error("Die Gruppe wurde nicht gefunden oder gehört nicht zu dieser Welt.");const source=await resolveEntityImageSource(projectId,formData,{current:String(current.image??""),entityType:"group",entityId:groupId,title:String(current.name)});await updateGroup(projectId,groupId,values(formData,source.image));if(source.uploaded||source.removed||source.image!==current.image)await setEntityImageReference(projectId,"group",groupId,source);refresh(projectId,groupId);}
async function saveMembership(projectId:number,groupId:number,personId:number,formData:FormData){await assertProject(projectId);await setGroupMembership({projectId,groupId,entityType:"person",entityId:personId,role:formOptionalText(formData,"role")??undefined,rank:formOptionalText(formData,"rank")??undefined,status:formText(formData,"status")||"active",isLeader:formCheckbox(formData,"isLeader"),startDisplay:formOptionalText(formData,"startDisplay")??undefined,endDisplay:formOptionalText(formData,"endDisplay")??undefined,notes:formOptionalText(formData,"membershipNotes")??undefined});refresh(projectId,groupId);}
export async function setGroupMembershipAction(projectId:number,groupId:number,personId:number,formData:FormData){await requireAdminSession();if(!Number.isSafeInteger(personId)||personId<=0)throw new Error("Die ausgewählte Person ist ungültig.");await saveMembership(projectId,groupId,personId,formData);}
export async function addGroupMembershipAction(projectId:number,groupId:number,formData:FormData){await requireAdminSession();const personId=formOptionalId(formData,"personId");if(!personId)throw new Error("Person ist ein Pflichtfeld.");await saveMembership(projectId,groupId,personId,formData);}
export async function removeGroupMembershipAction(projectId:number,groupId:number,personId:number){await requireAdminSession();await assertProject(projectId);await removeGroupMembership({projectId,groupId,entityType:"person",entityId:personId});refresh(projectId,groupId);}
export async function archiveGroupAction(projectId:number,groupId:number){await requireAdminSession();await assertProject(projectId);await archiveGroup(projectId,groupId);redirect(`/admin/projects/${projectId}/groups`);}
