import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { EntityImageFrame } from "@/components/entity-image-frame";
import { Pagination } from "@/components/pagination";
import { requireAdminSession } from "@/lib/auth/session";
import { listGroupsPaginated, type GroupListFilters } from "@/lib/entities/groups";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";
import { GroupCreateDialog } from "./group-create-dialog";
import styles from "./groups.module.css";

type Search=Promise<{q?:string;visibility?:string;page?:string;pageSize?:string;personId?:string}>;
function clean(value:unknown){const text=typeof value==="string"?value.trim():"";return text&&!['unknown','no notes yet'].includes(text.toLowerCase())?text:"";}
function visibilityLabel(value:unknown){return value==="all_players"?"Alle Spieler":value==="selected_players"?"Ausgewählte Spieler":"Nur Admin";}

export default async function GroupsPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){await requireAdminSession();const [{projectId:raw},search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const visibility=["admin_only","all_players","selected_players"].includes(search.visibility??"")?search.visibility as GroupListFilters["visibility"]:undefined;const pagination=parsePagination(search);const [project,groups]=await Promise.all([getProject(projectId),listGroupsPaginated(projectId,{query:search.q,visibility},pagination)]);if(!project)notFound();const path=`/admin/projects/${projectId}/groups`;const hasFilters=Boolean(search.q||search.visibility);return <AdminShell projectId={projectId} projectName={project.name} section="groups" title="Gruppen" eyebrow={`${project.name} / Welt`}>
  <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Gruppen</strong></div><h1>Gruppen & Fraktionen</h1><p>Wappen, Hauptquartier und bekannte Mitglieder sind direkt sichtbar. Ein fehlendes Motto bleibt bewusst leer und wird nicht durch die Beschreibung ersetzt.</p>{search.personId?<p className="notice">Wähle eine Gruppe und füge Person #{search.personId} dort als Mitglied hinzu.</p>:null}</div><GroupCreateDialog projectId={projectId}/></div>
  <section className={`panel-card ${styles.browser}`}><form className={styles.filter} method="get"><input name="q" defaultValue={search.q??""} placeholder="Gruppe, Motto, Typ oder Hauptquartier suchen …" aria-label="Gruppen durchsuchen"/><select name="visibility" defaultValue={visibility??""} aria-label="Sichtbarkeit"><option value="">Alle Sichtbarkeiten</option><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte Spieler</option></select>{search.personId?<input type="hidden" name="personId" value={search.personId}/>:null}<button type="submit">Filtern</button>{hasFilters?<Link className="button ghost" href={search.personId?`${path}?personId=${encodeURIComponent(search.personId)}`:path}>Zurücksetzen</Link>:null}</form><div className="table-meta"><span><strong>{groups.total}</strong> Gruppen</span><span>Geschätzte Gesamtgröße und bekannte Mitgliedschaften bleiben getrennte Werte.</span></div>{groups.items.length===0?<div className="empty-state large"><strong>Keine Gruppen gefunden</strong><span>{hasFilters?"Filter ändern oder zurücksetzen.":"Lege die erste Gruppe an."}</span></div>:<div className={styles.grid}>{groups.items.map((g)=>{const href=`/admin/projects/${projectId}/groups/${g.gr_id}${search.personId?`?personId=${encodeURIComponent(search.personId)}`:""}`;const name=String(g.name);return <Link key={Number(g.gr_id)} href={href} className={styles.card}><div className={styles.crest}><EntityImageFrame mode="thumbnail" src={typeof g.image==="string"?g.image:null} fallback={name.slice(0,1).toUpperCase()} alt={`${name} – Wappen`}/></div><div className={styles.body}><div><h2>{name}</h2>{clean(g.motto)?<p>{clean(g.motto)}</p>:null}</div><div className={styles.chips}><span className={styles.chip}>{clean(g.group_type)||"Gruppe"}</span><span className={styles.chip}>{String(g.location_name)}</span></div><div className={styles.stats}><div className={styles.stat}><strong>{Number(g.estimated_member_count??g.members)}</strong><span>geschätzt</span></div><div className={styles.stat}><strong>{Number(g.known_members??g.relation_members)}</strong><span>bekannt</span></div></div><div className={styles.footer}><span>{visibilityLabel(g.visibility_mode)}</span><strong>{search.personId?"Mitgliedschaft öffnen →":"Details →"}</strong></div></div></Link>;})}</div>}<Pagination pathname={path} searchParams={{q:search.q,visibility:search.visibility,personId:search.personId}} page={groups.page} pageSize={groups.pageSize} total={groups.total} totalPages={groups.totalPages}/></section>
</AdminShell>;}
