import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { Pagination } from "@/components/pagination";
import { requireAdminSession } from "@/lib/auth/session";
import { listGroupsPaginated, type GroupListFilters } from "@/lib/entities/groups";
import { listLocations } from "@/lib/entities/locations";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";
import { createGroupAction } from "./actions";
import styles from "./groups.module.css";

type Search=Promise<{q?:string;visibility?:string;page?:string;pageSize?:string}>;
function validImage(value:unknown){return typeof value==="string"&&Boolean(value.trim())&&value!=="noimage";}
function clean(value:unknown){const text=typeof value==="string"?value.trim():"";return text&&text!=="unknown"&&text!=="no notes yet"?text:"";}

export default async function GroupsPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){await requireAdminSession();const [{projectId:raw},search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const visibility=["admin_only","all_players","selected_players"].includes(search.visibility??"")?search.visibility as GroupListFilters["visibility"]:undefined;const pagination=parsePagination(search);const [project,groups,locations]=await Promise.all([getProject(projectId),listGroupsPaginated(projectId,{query:search.q,visibility},pagination),listLocations(projectId)]);if(!project)notFound();const path=`/admin/projects/${projectId}/groups`;return <AdminShell projectId={projectId} projectName={project.name} section="groups" title="Gruppen" eyebrow={`${project.name} / World`}>
  <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Gruppen</strong></div><h1>Gruppen & Fraktionen</h1><p>Wappen, Hauptquartier und bekannte Mitglieder sind direkt sichtbar. <code>groups.members</code> bleibt die geschätzte Organisationsgröße und wird durch Membership-CRUD nicht verändert.</p></div>{locations.length>0?<details className="create-dropdown"><summary className="button primary">＋ Gruppe</summary><div className="create-popover"><form action={createGroupAction.bind(null,projectId)} className="stack"><label>Name<input name="name" required/></label><label>Typ<input name="groupType"/></label><label>Hauptquartier<select name="locationId" required>{locations.map(l=><option key={l.loc_id} value={l.loc_id}>{l.name}</option>)}</select></label><label>Motto<input name="motto"/></label><label>Beschreibung / Notizen<textarea name="notes"/></label><label>Bild / Wappen<input name="image" placeholder="Bild-URL oder relativer Pfad"/></label><label>Sichtbarkeit<select name="visibilityMode"><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label><button className="primary">Gruppe anlegen</button></form></div></details>:null}</div>
  {locations.length===0?<section className="panel-card empty-state large"><strong>Erst eine Location anlegen</strong></section>:null}
  <section className={`panel-card ${styles.browser}`}><form className={styles.filter} method="get"><input name="q" defaultValue={search.q??""} placeholder="Gruppe, Motto, Typ oder Hauptquartier suchen …"/><select name="visibility" defaultValue={visibility??""}><option value="">Alle Sichtbarkeiten</option><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select><button>Filtern</button></form><div className="table-meta"><span><strong>{groups.total}</strong> Gruppen</span><span>Geschätzt ≠ relational bekannt</span></div>{groups.items.length===0?<div className="empty-state large"><strong>Keine Gruppen gefunden</strong></div>:<div className={styles.grid}>{groups.items.map((g)=><Link key={Number(g.gr_id)} href={`/admin/projects/${projectId}/groups/${g.gr_id}`} className={styles.card}><div className={styles.crest}>{validImage(g.image)?<img src={String(g.image)} alt=""/>:String(g.name).slice(0,1).toUpperCase()}</div><div className={styles.body}><div><h2>{String(g.name)}</h2><p>{clean(g.motto)||clean(g.notes)||"Organisation ohne öffentliche Kurzbeschreibung"}</p></div><div className={styles.chips}><span className={styles.chip}>{clean(g.group_type)||"Gruppe"}</span><span className={styles.chip}>{String(g.location_name)}</span></div><div className={styles.stats}><div className={styles.stat}><strong>{Number(g.estimated_member_count??g.members)}</strong><span>geschätzt</span></div><div className={styles.stat}><strong>{Number(g.known_members??g.relation_members)}</strong><span>bekannt</span></div></div><div className={styles.footer}><span>{String(g.visibility_mode)}</span><strong>Details →</strong></div></div></Link>)}</div>}<Pagination pathname={path} searchParams={{q:search.q,visibility:search.visibility}} page={groups.page} pageSize={groups.pageSize} total={groups.total} totalPages={groups.totalPages}/></section>
</AdminShell>;}
