import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { FantasyDateInput } from "@/components/fantasy-date-input";
import { ImageSourceInput } from "@/components/image-source-input";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { calendarStatus, personChronology } from "@/lib/calendar";
import { getGod } from "@/lib/entities/gods";
import { getProject } from "@/lib/projects";
import { archiveGodAction, updateGodAction } from "../actions";

function visibilityLabel(mode:string){return mode==="all_players"?"Alle Spieler":mode==="selected_players"?"Ausgewählte Spieler":"Nur Admin";}

export default async function GodDetailPage({params}:{params:Promise<{projectId:string;godId:string}>}){
  await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);const personId=Number.parseInt(raw.godId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(personId)||projectId<=0||personId<=0)notFound();
  const [project,god,chronology]=await Promise.all([getProject(projectId),getGod(projectId,personId),personChronology(projectId,personId)]);if(!project||!god)notFound();const calendar=chronology.calendar;const calendarReady=calendar?calendarStatus(calendar).ready:false;
  return <AdminShell projectId={projectId} projectName={project.name} section="gods" title={god.name} eyebrow={`${project.name} / Götter`}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/gods`}>Götter</Link><span>/</span><strong>{god.name}</strong></div>
    <section className="entity-hero"><div className="entity-avatar hero-avatar">{god.image&&god.image!=="noimage"?<img src={god.image} alt="" loading="lazy"/>:god.name.slice(0,1).toUpperCase()}</div><div className="entity-hero-main"><span className="page-kicker">Person #{god.person_id} · God-Subtype #{god.god_id}</span><h1>{god.name}</h1><p>{[god.god_title,god.domain,god.faction].filter((value:string)=>value&&value!=="unknown").join(" · ")||"Gottheit"}</p><div className="hero-tags"><span className="soft-label">God</span>{chronology.lifeLabel?<span className="soft-label">{chronology.lifeLabel}</span>:null}<span className={`visibility-pill ${god.visibility_mode}`}>{visibilityLabel(god.visibility_mode)}</span></div></div></section>
    <form action={updateGodAction.bind(null,projectId,personId)} className="npc-detail-grid"><div className="stack detail-main">
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">GEMEINSAME PERSON · NPCS</span><h2>Identität & Basisprofil</h2></div><span className="record-id">n_id #{god.person_id}</span></div><p className="section-help">Personendaten, die auch Relationships, Gruppen und Stammbäume nutzen.</p><div className="field-grid two"><label>Name<input name="name" defaultValue={god.name} required/></label><label>Personen-Titel<input name="personTitle" defaultValue={god.person_title??""}/></label><label>Spezies<input name="species" defaultValue={god.species??""}/></label><label>Beruf / Rolle<input name="profession" defaultValue={god.profession??""}/></label><label>Geschlecht<input name="gender" defaultValue={god.gender}/></label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={god.visibility_mode}><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div><ImageSourceInput current={god.image} label="Bild / Darstellung"/></section>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">GOD SUBTYPE · GODS</span><h2>Göttliche Eigenschaften</h2></div><span className="record-id">g_id #{god.god_id}</span></div><div className="field-grid two"><label>Göttlicher Titel<input name="godTitle" defaultValue={god.god_title}/></label><label>Domain<input name="domain" defaultValue={god.domain}/></label><label>Fraktion / Pantheon<input name="faction" defaultValue={god.faction}/></label></div></section>
      {calendar&&calendarReady?<section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">WELTZEIT</span><h2>Geburt / Manifestation</h2></div>{chronology.ageLabel?<strong>{chronology.ageLabel}</strong>:null}</div><FantasyDateInput prefix="birth" label="Chronologischer Beginn" months={calendar.months} beforeEraLabel={calendar.beforeEraLabel} afterEraLabel={calendar.afterEraLabel} hasYearZero={calendar.hasYearZero} value={chronology.birth}/></section>:null}
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">SPIELER-WISSEN · NPCS</span><h2>Öffentliche Beschreibung</h2></div></div><textarea name="publicDescription" className="large-textarea" defaultValue={god.public_description??""}/></section>
      <section className="panel-card edit-section secret-section"><div className="panel-heading"><div><span className="panel-kicker">ADMIN ONLY · NPCS</span><h2>Geheime Notizen</h2></div></div><textarea name="adminNotes" className="large-textarea" defaultValue={god.admin_notes??god.notes}/></section>
      <div className="sticky-savebar"><div><strong>Gottheit speichern</strong><span>Person, God-Subtype, Bild und Chronologie werden konsistent gepflegt.</span></div><SubmitButton className="primary" pendingLabel="Speichere Gottheit …">Speichern</SubmitButton></div>
    </div><aside className="stack detail-side"><section className="panel-card profile-summary"><div className="panel-heading"><div><span className="panel-kicker">VERKNÜPFUNGEN</span><h2>Hinzufügen & verwalten</h2></div></div><div className="stack"><Link className="button primary" href={`/admin/projects/${projectId}/relationships?personId=${god.person_id}&create=1`}>＋ Beziehung hinzufügen</Link><Link className="button" href={`/admin/projects/${projectId}/relationships?personId=${god.person_id}`}>Beziehungen verwalten</Link><Link className="button" href={`/admin/projects/${projectId}/groups?personId=${god.person_id}`}>＋ Gruppe zuordnen</Link><Link className="button" href={`/admin/projects/${projectId}/family-trees?personId=${god.person_id}`}>＋ Zu Stammbaum</Link><Link className="button" href={`/admin/projects/${projectId}/family-trees/all`}>Im Gesamtgraph anzeigen</Link></div></section></aside></form>
    <section className="danger-zone"><div><h2>Gottheit archivieren</h2><p>Die Person wird archiviert, nicht physisch gelöscht.</p></div><ConfirmAction action={archiveGodAction.bind(null,projectId,personId)} title={`${god.name} archivieren?`} description="Die Gottheit verschwindet aus aktiven Listen. Person-, God-Subtype- und Legacy-Daten werden nicht physisch gelöscht." triggerLabel="Archivieren…" confirmLabel="Gottheit archivieren" triggerClassName="button danger"/></section>
  </AdminShell>;
}
