import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { MapViewer } from "@/components/map-viewer";
import { requireAdminSession } from "@/lib/auth/session";
import { listMapMarkers, listProjectMaps } from "@/lib/maps";
import { getProject } from "@/lib/projects";

export default async function AdminMapPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{mapId?:string}>}){
 await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const [project,maps]=await Promise.all([getProject(projectId),listProjectMaps(projectId)]);if(!project)notFound();const requested=search.mapId?Number.parseInt(search.mapId,10):null;const selected=maps.find((m)=>Number(m.map_id)===requested)??maps.find((m)=>m.is_primary)??maps[0];if(!selected)return <AdminShell projectId={projectId} projectName={project.name} title="Map"><section className="panel-card empty-state large"><strong>Keine Karte vorhanden</strong><Link className="button primary" href={`/admin/projects/${projectId}/settings`}>Karte anlegen</Link></section></AdminShell>;const markers=await listMapMarkers(projectId,Number(selected.map_id));
 const config={mapId:Number(selected.map_id),mapType:selected.map_type,tileUrl:selected.tile_url,imagePath:selected.image_path,minZoom:selected.min_zoom,maxZoom:selected.max_zoom,centerLat:selected.center_lat,centerLng:selected.center_lng,bounds:selected.bounds,config:selected.config};
 return <AdminShell projectId={projectId} projectName={project.name} eyebrow={`${project.name} / Map`} title={selected.name}><div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Map</strong></div><h1>{selected.name}</h1><p>Klick auf die Karte erstellt einen Marker; Drag & Drop speichert die Position direkt.</p></div><div className="row"><select defaultValue={String(selected.map_id)} onChange={undefined} aria-label="Map Auswahl">{maps.map((map)=><option key={map.map_id} value={map.map_id}>{map.name}{map.is_primary?" · Primary":""}</option>)}</select><Link className="button ghost" href={`/admin/projects/${projectId}/settings`}>Maps verwalten</Link></div></div><section className="panel-card"><MapViewer mapConfig={config} initialMarkers={markers} admin projectId={projectId}/></section><section className="panel-card"><h2>Map wechseln</h2><div className="row wrap-row">{maps.map((map)=><Link key={map.map_id} className="button ghost" href={`/admin/projects/${projectId}/map?mapId=${map.map_id}`}>{map.name}</Link>)}</div></section></AdminShell>;
}
