import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { getCharacter } from "@/lib/entities/characters";
import { listLocations } from "@/lib/entities/locations";
import { getProject } from "@/lib/projects";
import { listPlayers } from "@/lib/players";
import { archiveCharacterAction, assignCharacterAction, updateCharacterAction } from "../actions";

export default async function CharacterDetailPage({params}:{params:Promise<{projectId:string;charId:string}>}){
  await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);const charId=Number.parseInt(raw.charId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(charId)||projectId<=0||charId<=0)notFound();
  const [project,character,locations,players]=await Promise.all([getProject(projectId),getCharacter(projectId,charId),listLocations(projectId),listPlayers(projectId)]);if(!project||!character)notFound();
  return <AdminShell projectId={projectId} projectName={project.name} title={String(character.name)} eyebrow={`${project.name} / Spielercharaktere`}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/characters`}>Spielercharaktere</Link><span>/</span><strong>{String(character.name)}</strong></div>
    <div className="npc-detail-grid"><div className="stack detail-main"><form action={updateCharacterAction.bind(null,projectId,charId)}><section className="panel-card edit-section"><div className="field-grid two"><label>Name<input name="name" defaultValue={String(character.name)} required/></label><label>Location<select name="locationId" defaultValue={String(character.loc_id)}>{locations.map((l)=><option key={l.loc_id} value={l.loc_id}>{l.name}</option>)}</select></label><label>Rasse<input name="race" defaultValue={String(character.race)}/></label><label>Klasse<input name="className" defaultValue={String(character.class)}/></label><label>Geburtstag<input name="birthday" type="date" defaultValue={character.birthday instanceof Date?character.birthday.toISOString().slice(0,10):String(character.birthday).slice(0,10)}/></label><label>Alter<input name="age" type="number" min="0" defaultValue={String(character.age)}/></label><label>Geschlecht<input name="gender" defaultValue={String(character.gender)}/></label><label>Bild<input name="image" defaultValue={String(character.image)==="noimage"?"":String(character.image)}/></label><label><input name="alive" type="checkbox" defaultChecked={Boolean(character.alive)}/> Lebendig</label><label><input name="follower" type="checkbox" defaultChecked={Boolean(character.follower)}/> Follower</label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={String(character.visibility_mode)}><option value="admin_only">Admin only</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div><label>Öffentliche Beschreibung<textarea name="publicDescription" className="large-textarea" defaultValue={character.public_description?String(character.public_description):""}/></label><label>Admin-Notizen<textarea name="adminNotes" className="large-textarea" defaultValue={character.admin_notes?String(character.admin_notes):String(character.notes)}/></label><button className="primary">Änderungen speichern</button></section></form></div>
      <aside className="stack detail-side"><section className="panel-card"><span className="panel-kicker">PLAYER ASSIGNMENT</span><h2>Spieler zuweisen</h2><form action={assignCharacterAction.bind(null,projectId,charId)} className="stack"><select name="playerId" defaultValue={character.player_id?String(character.player_id):""}><option value="">Nicht zugewiesen</option>{players.map((p)=><option key={p.userId} value={p.userId}>{p.displayName}</option>)}</select><button className="button primary">Zuweisung speichern</button></form></section></aside></div>
    <section className="danger-zone"><div><h2>Charakter archivieren</h2><p>NPC- und Character-ID werden nicht gelöscht.</p></div><form action={archiveCharacterAction.bind(null,projectId,charId)}><button className="danger">Archivieren</button></form></section>
  </AdminShell>;
}
