import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { CharacterLifeStatusInput } from "@/components/character-life-status-input";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityPicker } from "@/components/entity-picker";
import { FantasyDateInput } from "@/components/fantasy-date-input";
import { ImageSourceInput } from "@/components/image-source-input";
import { PersonGenderSelect } from "@/components/person-gender-select";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { calendarStatus, personChronology } from "@/lib/calendar";
import { deathCauseLabel } from "@/lib/death-causes";
import { getCharacter } from "@/lib/entities/characters";
import { listRaces, raceHierarchyLabel } from "@/lib/entities/races";
import { personGenderLabel } from "@/lib/person-gender";
import { getProject } from "@/lib/projects";
import { listPlayers } from "@/lib/players";
import { archiveCharacterAction, assignCharacterAction, updateCharacterAction } from "../actions";

export default async function CharacterDetailPage({params}:{params:Promise<{projectId:string;charId:string}>}){
  await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);const charId=Number.parseInt(raw.charId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(charId)||projectId<=0||charId<=0)notFound();
  const [project,character,players,races]=await Promise.all([getProject(projectId),getCharacter(projectId,charId),listPlayers(projectId),listRaces(projectId)]);if(!project||!character)notFound();const personId=Number(character.person_id);const chronology=await personChronology(projectId,personId);const calendar=chronology.calendar;const ready=calendar?calendarStatus(calendar).ready:false;const ageLabel=chronology.ageLabel||(Number(character.age)>0?`${character.age} Jahre (Legacy-Angabe)`:"Alter unbekannt");const causeLabel=deathCauseLabel(character.death_cause_code?String(character.death_cause_code):null);const causeDetail=character.death_cause_detail?String(character.death_cause_detail):null;const causeText=[causeLabel,causeDetail].filter(Boolean).join(" · ")||null;const raceLabel=String(character.race_display??character.race??"Unbekannt");const selectedRace=races.find((race)=>race.raceId===Number(character.race_id));const racePath=selectedRace?raceHierarchyLabel(selectedRace):(character.race_parent_name?`${String(character.race_parent_name)} → ${String(character.race_base_name)}`:String(character.race_base_name??raceLabel));
  return <AdminShell projectId={projectId} projectName={project.name} section="characters" title={String(character.name)} eyebrow={`${project.name} / Spielercharaktere`}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/characters`}>Spielercharaktere</Link><span>/</span><strong>{String(character.name)}</strong></div>
    <section className="entity-hero"><div className="entity-avatar hero-avatar">{String(character.image)!=="noimage"?<img src={String(character.image)} alt="" loading="lazy"/>:String(character.name).slice(0,1).toUpperCase()}</div><div className="entity-hero-main"><span className="page-kicker">PERSON #{personId} · CHARACTER #{charId}</span><h1>{String(character.name)}</h1><p>{raceLabel} · {String(character.class)}</p><div className="hero-tags"><span className="soft-label">{personGenderLabel(String(character.gender))}</span><span className="soft-label">{racePath}</span><span className="soft-label">{Boolean(character.alive)?"Lebendig":"Verstorben"}</span><span className="soft-label">{ageLabel}</span>{chronology.lifeLabel?<span className="soft-label">{chronology.lifeLabel}</span>:null}{!Boolean(character.alive)&&causeText?<span className="soft-label">{causeText}</span>:null}</div></div></section>
    <div className="npc-detail-grid"><div className="stack detail-main"><form action={updateCharacterAction.bind(null,projectId,charId)} className="stack"><section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">PERSON & CHARACTER</span><h2>Character-Daten</h2></div></div><div className="field-grid two"><label>Name<input name="name" defaultValue={String(character.name)} required/></label><EntityPicker projectId={projectId} name="locationId" types={["location"]} label="Location" required allowClear={false} placeholder="Location suchen …" initialValue={String(character.loc_id)} initialLabel={String(character.location_name)} initialKind="Location"/><label>Spezies / Subspezies<select name="raceId" defaultValue={character.race_id?String(character.race_id):""} required><option value="" disabled>Spezies wählen</option>{races.map((race)=><option key={race.raceId} value={race.raceId}>{raceHierarchyLabel(race)}</option>)}</select>{character.race_id?<small><Link href={`/admin/projects/${projectId}/races/${character.race_id}`}>Spezies öffnen →</Link></small>:<small><Link href={`/admin/projects/${projectId}/races`}>Spezies zuordnen →</Link></small>}</label><label>Klasse<input name="className" defaultValue={String(character.class)}/></label><label>Geschlecht<PersonGenderSelect defaultValue={String(character.gender)}/></label><label><input name="follower" type="checkbox" defaultChecked={Boolean(character.follower)}/> Follower</label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={String(character.visibility_mode)}><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div><ImageSourceInput current={String(character.image)} label="Bild / Porträt"/><div className="notice"><strong>Spezies-Pfad:</strong> {racePath}. Wenn die genaue Spezies noch nicht feststeht, kann „Unbekannt“ gewählt werden.</div></section>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">WELTZEIT & LEBENSSTATUS</span><h2>Geburt, Tod & Alter</h2></div><strong>{ageLabel}</strong></div>{calendar&&ready?<FantasyDateInput prefix="birth" label="Geburtsdatum" months={calendar.months} beforeEraLabel={calendar.beforeEraLabel} afterEraLabel={calendar.afterEraLabel} hasYearZero={calendar.hasYearZero} value={chronology.birth}/>:<div className="notice warning">Legacy age/birthday bleiben erhalten, bis der <Link href={`/admin/projects/${projectId}/settings/calendar`}>Weltkalender</Link> konfiguriert ist.</div>}<CharacterLifeStatusInput defaultAlive={Boolean(character.alive)} calendar={calendar&&ready?calendar:null} deathDate={chronology.death} deathCauseCode={character.death_cause_code?String(character.death_cause_code):null} deathCauseDetail={causeDetail}/><p className="section-help">Bei verstorbenen Characters wird das Alter bis zum Todesdatum berechnet und die Lebensspanne automatisch in Stammbäumen verwendet.</p></section>
      <section className="panel-card edit-section"><label>Öffentliche Beschreibung<textarea name="publicDescription" className="large-textarea" defaultValue={character.public_description?String(character.public_description):""}/></label><label>Admin-Notizen<textarea name="adminNotes" className="large-textarea" defaultValue={character.admin_notes?String(character.admin_notes):String(character.notes)}/></label></section><div className="sticky-savebar"><div><strong>Character speichern</strong><span>Geschlecht und Spezies/Subspezies verwenden die zentralen Weltdefinitionen; Legacy age/birthday werden nicht überschrieben.</span></div><SubmitButton className="primary" pendingLabel="Speichere Character …">Änderungen speichern</SubmitButton></div></form></div>
      <aside className="stack detail-side"><section className="panel-card"><span className="panel-kicker">LEBENSSTATUS</span><h2>{Boolean(character.alive)?"Lebendig":"Verstorben"}</h2>{!Boolean(character.alive)&&chronology.deathLabel?<p><strong>Gestorben:</strong> {chronology.deathLabel}</p>:null}{!Boolean(character.alive)&&causeText?<p><strong>Todesursache:</strong> {causeText}</p>:null}</section><section className="panel-card"><span className="panel-kicker">PLAYER ASSIGNMENT</span><h2>Spieler zuweisen</h2><form action={assignCharacterAction.bind(null,projectId,charId)} className="stack"><select name="playerId" defaultValue={character.player_id?String(character.player_id):""}><option value="">Nicht zugewiesen</option>{players.map((p)=><option key={p.userId} value={p.userId}>{p.displayName}</option>)}</select><SubmitButton className="button primary" pendingLabel="Zuweisung wird gespeichert …">Zuweisung speichern</SubmitButton></form></section><section className="panel-card"><span className="panel-kicker">VERKNÜPFUNGEN</span><div className="stack"><Link className="button primary" href={`/admin/projects/${projectId}/relationships?personId=${personId}&create=1`}>＋ Beziehung hinzufügen</Link><Link className="button" href={`/admin/projects/${projectId}/groups?personId=${personId}`}>＋ Gruppe zuordnen</Link><Link className="button" href={`/admin/projects/${projectId}/family-trees?personId=${personId}`}>＋ Zu Stammbaum</Link></div></section></aside></div>
    <section className="danger-zone"><div><h2>Charakter archivieren</h2><p>NPC- und Character-ID werden nicht gelöscht.</p></div><ConfirmAction action={archiveCharacterAction.bind(null,projectId,charId)} title={`${String(character.name)} archivieren?`} description="Die Person verschwindet aus aktiven Character-Listen. NPC- und Character-ID sowie Legacy-Daten bleiben erhalten." triggerLabel="Archivieren…" confirmLabel="Charakter archivieren" triggerClassName="button danger"/></section>
  </AdminShell>;
}
