import assert from "node:assert/strict";
import test from "node:test";
import {
  ENTITY_AVATAR_RENDER_VERSION,
  entityAvatarExtractRect,
  entityAvatarManagedSourceKey,
} from "../src/lib/entity-image-crop-geometry";

test("avatar crop x/y position the square across remaining source overflow", () => {
  assert.deepEqual(entityAvatarExtractRect(600, 900, { x: 50, y: 50, zoom: 1 }), {
    left: 0,
    top: 150,
    width: 600,
    height: 600,
  });
  assert.deepEqual(entityAvatarExtractRect(600, 900, { x: 0, y: 0, zoom: 2 }), {
    left: 0,
    top: 0,
    width: 300,
    height: 300,
  });
  assert.deepEqual(entityAvatarExtractRect(600, 900, { x: 100, y: 100, zoom: 2 }), {
    left: 300,
    top: 600,
    width: 300,
    height: 300,
  });
  assert.deepEqual(entityAvatarExtractRect(600, 900, { x: 25, y: 75, zoom: 2 }), {
    left: 75,
    top: 450,
    width: 300,
    height: 300,
  });
});

test("avatar crop geometry works for landscape sources too", () => {
  assert.deepEqual(entityAvatarExtractRect(1200, 800, { x: 75, y: 25, zoom: 2 }), {
    left: 600,
    top: 100,
    width: 400,
    height: 400,
  });
});

test("render version invalidates derivatives generated by older crop math", () => {
  assert.equal(ENTITY_AVATAR_RENDER_VERSION, 2);
  assert.match(entityAvatarManagedSourceKey(42, "project/42/image.jpg"), /^avatar-v2:media:42:/);
});
