import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { getNpc } from "@/lib/entities/npcs";
import { listLocations } from "@/lib/entities/locations";
import { getProject } from "@/lib/projects";
import { archiveNpcAction, updateNpcAction } from "../actions";

function visibilityLabel(mode:string){return mode==="all_players"?"Alle Spieler":mode==="selected_players"?"Ausgewählte Spieler":"Nur Admin";}

export default async function NpcDetailPage({params}:{params:Promise<{projectId:string;npcId:string}>}){
  await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);const npcId=Number.parseInt(raw.npcId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(npcId)||projectId<=0||npcId<=0)notFound();
  const [project,npc,locations]=await Promise.all([getProject(projectId),getNpc(projectId,npcId),listLocations(projectId)]);if(!project||!npc)notFound();
  return <AdminShell projectId={projectId} projectName={project.name} section="npcs" eyebrow={`${project.name} / NPCs`} title={npc.name}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><Link href={`/admin/projects/${projectId}/npcs`}>NPCs</Link><span>/</span><strong>{npc.name}</strong></div>
    <section className="entity-hero"><div className="entity-avatar hero-avatar">{npc.image&&npc.image!=="noimage"?<img src={npc.image} alt=""/>:npc.name.slice(0,1).toUpperCase()}</div><div className="entity-hero-main"><span className="page-kicker">Person #{npc.nId} · Character row #{npc.charId}</span><h1>{npc.name}</h1><p>{[npc.title,npc.race,npc.className,npc.profession].filter(Boolean).join(" · ")}</p><div className="hero-tags"><span className="soft-label">{npc.alive?"Lebendig":"Tot"}</span><span className={`visibility-pill ${npc.visibilityMode}`}>{visibilityLabel(npc.visibilityMode)}</span></div></div></section>
    <form action={updateNpcAction.bind(null,projectId,npcId)} className="npc-detail-grid"><div className="stack detail-main">
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">PERSON</span><h2>Basisdaten</h2></div><span className="record-id">n_id #{npc.nId}</span></div><div className="field-grid two"><label>Name<input name="name" defaultValue={npc.name} required/></label><label>Titel<input name="title" defaultValue={npc.title??""}/></label><label>Spezies<input name="species" defaultValue={npc.species??""}/></label><label>Beruf<input name="profession" defaultValue={npc.profession??""}/></label><label>Geschlecht<input name="gender" defaultValue={npc.gender}/></label><label>Bild-URL<input name="image" defaultValue={npc.image==="noimage"?"":npc.image}/></label></div></section>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">CHARACTER SUBTYPE</span><h2>Character-Daten</h2></div><span className="record-id">char_id #{npc.charId}</span></div><div className="field-grid two"><label>Ort<select name="locationId" defaultValue={npc.locId} required>{locations.map((l)=><option key={l.loc_id} value={l.loc_id}>{l.name}</option>)}</select></label><label>Race<input name="race" defaultValue={npc.race}/></label><label>Klasse<input name="className" defaultValue={npc.className}/></label><label>Alter<input name="age" type="number" min="0" defaultValue={npc.age}/></label><label>Geburtstag<input name="birthday" type="date" defaultValue={npc.birthday}/></label><label><input name="alive" type="checkbox" defaultChecked={npc.alive}/> Lebendig</label><label><input name="follower" type="checkbox" defaultChecked={npc.follower}/> Follower</label></div><p className="section-help">Alter und Geburtstag bleiben unabhängige Worldbuilding-Felder; der Legacy-Default 2000-01-01 wird nicht zur Altersberechnung verwendet.</p></section>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">SPIELER-WISSEN</span><h2>Öffentliche Beschreibung</h2></div></div><textarea name="publicDescription" className="large-textarea" defaultValue={npc.publicDescription??""}/></section>
      <section className="panel-card edit-section secret-section"><div className="panel-heading"><div><span className="panel-kicker">ADMIN ONLY</span><h2>Geheime Notizen</h2></div></div><textarea name="adminNotes" className="large-textarea" defaultValue={npc.adminNotes??npc.notes}/></section>
      <div className="sticky-savebar"><div><strong>Änderungen speichern</strong><span>n_id bleibt die kanonische Personen-ID.</span></div><button className="primary" type="submit">Speichern</button></div>
    </div><aside className="stack detail-side"><section className="panel-card profile-summary"><div className="panel-heading"><div><span className="panel-kicker">IDENTITÄT</span><h2>Datensatz</h2></div></div><dl className="summary-list"><div><dt>Person-ID</dt><dd>#{npc.nId}</dd></div><div><dt>Character Row</dt><dd>#{npc.charId}</dd></div><div><dt>Ort</dt><dd>{npc.location}</dd></div><div><dt>Sichtbarkeit</dt><dd>{visibilityLabel(npc.visibilityMode)}</dd></div></dl></section><Link className="button primary" href={`/admin/projects/${projectId}/npcs/${npcId}/visibility`}>Spieler-Sichtbarkeit</Link></aside></form>
    <section className="danger-zone"><div><span className="panel-kicker">DANGER ZONE</span><h2>Person archivieren</h2><p>Legacy-Zeilen werden nicht physisch gelöscht.</p></div><form action={archiveNpcAction.bind(null,projectId,npcId)}><button className="danger" type="submit">Archivieren</button></form></section>
  </AdminShell>;
}
