import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { CharacterLifeStatusInput } from "@/components/character-life-status-input";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityImageFrame } from "@/components/entity-image-frame";
import { EntityPicker } from "@/components/entity-picker";
import { FantasyDateInput } from "@/components/fantasy-date-input";
import { FormRequiredLegend } from "@/components/form-ui";
import { PersonGenderSelect } from "@/components/person-gender-select";
import { ProfileImageEditor } from "@/components/profile-image-editor";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { calendarStatus,personChronology } from "@/lib/calendar";
import { deathCauseLabel } from "@/lib/death-causes";
import { getLocationPath } from "@/lib/entities/locations";
import { getNpc } from "@/lib/entities/npcs";
import { listRaces, raceHierarchyLabel } from "@/lib/entities/races";
import { getEntityImageProfile } from "@/lib/entity-image-profiles";
import { personGenderLabel } from "@/lib/person-gender";
import { listPersonLocations } from "@/lib/person-locations";
import { getProject } from "@/lib/projects";
import { archiveNpcAction,updateNpcAction } from "../actions";

function visibilityLabel(mode:string){return mode==="all_players"?"Alle Spieler":mode==="selected_players"?"Ausgewählte Spieler":"Nur Admin";}
function meaningful(value:string|null|undefined){return Boolean(value&&value.trim()&&!['unknown','no notes yet'].includes(value.trim().toLowerCase()));}

export default async function NpcDetailPage({params}:{params:Promise<{projectId:string;npcId:string}>}){
  await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10),npcId=Number.parseInt(raw.npcId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(npcId)||projectId<=0||npcId<=0)notFound();
  const [project,npc,chronology,spatialLocations,races]=await Promise.all([getProject(projectId),getNpc(projectId,npcId),personChronology(projectId,npcId),listPersonLocations(projectId,npcId),listRaces(projectId)]);if(!project||!npc)notFound();const [locationPath,imageProfile]=await Promise.all([getLocationPath(projectId,npc.locId),getEntityImageProfile(projectId,"person",npcId,npc.image)]);
  const calendar=chronology.calendar,calendarReady=calendar?calendarStatus(calendar).ready:false,ageLabel=chronology.ageLabel||(npc.age>0?`${npc.age} Jahre (Legacy-Angabe)`:"Alter unbekannt");const legacySpecies=meaningful(npc.species)&&npc.species?.trim().toLowerCase()!==npc.raceBaseName?.trim().toLowerCase()?npc.species:null;const causeLabel=deathCauseLabel(npc.deathCauseCode),causeText=[causeLabel,npc.deathCauseDetail].filter(Boolean).join(" · ")||null;const spatialPath=locationPath.map(item=>item.name).join(" → ")||npc.location;const mappedCurrent=spatialLocations.find(item=>item.role==="current"&&item.is_primary);const selectedRace=races.find((race)=>race.raceId===npc.raceId);const racePath=selectedRace?raceHierarchyLabel(selectedRace):(npc.raceParentName?`${npc.raceParentName} → ${npc.raceBaseName}`:npc.raceBaseName);
  return <AdminShell projectId={projectId} projectName={project.name} section="npcs" eyebrow={`${project.name} / NPCs`} title={npc.name}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><Link href={`/admin/projects/${projectId}/npcs`}>NPCs</Link><span>/</span><strong>{npc.name}</strong></div>
    <section className="entity-hero"><EntityImageFrame className="entity-avatar hero-avatar" src={npc.image} crop={imageProfile?.crop} fallback={npc.name.slice(0,1).toUpperCase()} alt={`${npc.name} – Porträt`}/><div className="entity-hero-main"><span className="page-kicker">Person #{npc.nId} · Charakter-Untertyp #{npc.charId}</span><h1>{npc.name}</h1><p>{[npc.title,npc.race,npc.className,npc.profession].filter(meaningful).join(" · ")}</p><div className="hero-tags"><span className="soft-label">NPC / Charakter</span><span className="soft-label">{personGenderLabel(npc.gender)}</span><span className="soft-label">{racePath}</span><span className="soft-label">{npc.alive?"Lebendig":"Verstorben"}</span><span className="soft-label">{ageLabel}</span><span className="soft-label">📍 {npc.location}</span>{chronology.lifeLabel?<span className="soft-label">{chronology.lifeLabel}</span>:null}{!npc.alive&&causeText?<span className="soft-label">{causeText}</span>:null}<span className={`visibility-pill ${npc.visibilityMode}`}>{visibilityLabel(npc.visibilityMode)}</span></div></div></section>
    <form action={updateNpcAction.bind(null,projectId,npcId)} className="npc-detail-grid"><div className="stack detail-main"><FormRequiredLegend/>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">GEMEINSAME PERSON · NPCS</span><h2>Identität & Basisprofil</h2></div><span className="record-id">n_id #{npc.nId}</span></div><p className="section-help">Gemeinsame Personendaten. Spezies, Klasse, Ort und Chronologie gehören bewusst nicht hierher.</p><div className="field-grid two"><label>Name<input name="name" maxLength={100} defaultValue={npc.name} required/></label><label>Personen-Titel <span className="muted">optional</span><input name="title" maxLength={120} defaultValue={npc.title??""}/></label><label>Beruf / Profession <span className="muted">optional</span><input name="profession" maxLength={120} defaultValue={npc.profession??""}/></label><label>Geschlecht<PersonGenderSelect defaultValue={npc.gender}/></label></div><ProfileImageEditor current={npc.image} currentCrop={imageProfile?.crop} label="Bild / Porträt"/>{legacySpecies?<div className="notice warning"><strong>Legacy-Spezies:</strong> {legacySpecies}. Der kanonische Charakter verweist jetzt über <code>race_id</code> auf einen Spezies-Datensatz.</div>:null}</section>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">CHARAKTER-UNTERTYP · CHARAKTERS</span><h2>Charakterdaten & aktueller Ort</h2></div><span className="record-id">char_id #{npc.charId}</span></div><p className="section-help">Die Auswahl enthält Haupt-Spezies, Subspezies und den Fallback „Unbekannt“. Subspezies werden als Pfad angezeigt.</p><div className="field-grid two"><EntityPicker projectId={projectId} name="locationId" types={["location"]} label="Aktueller Ort" required allowClear={false} initialValue={String(npc.locId)} initialLabel={npc.location} initialKind="Ort" placeholder="Land, Stadt, Bezirk oder Gebäude suchen …"/><label>Spezies / Subspezies<select name="raceId" required defaultValue={npc.raceId??""}><option value="" disabled>Bitte auswählen …</option>{races.map((race)=><option key={race.raceId} value={race.raceId}>{raceHierarchyLabel(race)}</option>)}</select>{npc.raceId?<small><Link href={`/admin/projects/${projectId}/races/${npc.raceId}`}>Spezies-Datensatz öffnen →</Link></small>:<small><Link href={`/admin/projects/${projectId}/races`}>Spezies anlegen →</Link></small>}</label><label>Klasse <span className="muted">optional</span><input name="className" maxLength={50} defaultValue={npc.className}/></label><label><input name="follower" type="checkbox" defaultChecked={npc.follower}/> Follower</label></div><div className="notice"><strong>Räumlicher Pfad:</strong> {spatialPath}</div></section>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">WELTZEIT & LEBENSSTATUS</span><h2>Geburt, Tod & Alter</h2></div><strong>{ageLabel}</strong></div>{calendar&&calendarReady?<FantasyDateInput prefix="birth" label="Geburtsdatum" months={calendar.months} beforeEraLabel={calendar.beforeEraLabel} afterEraLabel={calendar.afterEraLabel} hasYearZero={calendar.hasYearZero} value={chronology.birth}/>:<div className="empty-state"><strong>Weltkalender zuerst konfigurieren</strong><p>Legacy-Alter: {npc.age||"—"} · Legacy-Geburtstag: {npc.birthday||"—"}</p><Link className="button" href={`/admin/projects/${projectId}/settings/calendar`}>Weltkalender öffnen</Link></div>}<CharacterLifeStatusInput defaultAlive={npc.alive} calendar={calendar&&calendarReady?calendar:null} deathDate={chronology.death} deathCauseCode={npc.deathCauseCode} deathCauseDetail={npc.deathCauseDetail}/><p className="section-help">Bei verstorbenen Personen wird das Alter bis zum Todesdatum berechnet.</p></section>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">SPIELER-WISSEN · NPCS</span><h2>Öffentliche Beschreibung</h2></div></div><label>Öffentliche Beschreibung <span className="muted">optional</span><textarea name="publicDescription" className="large-textarea" maxLength={100000} defaultValue={npc.publicDescription??""}/></label></section>
      <section className="panel-card edit-section secret-section"><div className="panel-heading"><div><span className="panel-kicker">NUR ADMIN · NPCS</span><h2>Geheime Notizen</h2></div></div><label>Admin-Notizen <span className="muted">optional</span><textarea name="adminNotes" className="large-textarea" maxLength={100000} defaultValue={npc.adminNotes??npc.notes}/></label></section>
      <div className="sticky-savebar"><div><strong>NPC-Daten speichern</strong><span>Originalbild und optionaler 1:1-Profilzuschnitt werden getrennt und nicht-destruktiv gespeichert.</span></div><SubmitButton className="primary" pendingLabel="NPC wird gespeichert …">NPC-Daten speichern</SubmitButton></div>
    </div><aside className="stack detail-side">
      <section className="panel-card profile-summary"><div className="panel-heading"><div><span className="panel-kicker">IDENTITÄT</span><h2>Datensatz</h2></div></div><dl className="summary-list"><div><dt>Person-ID</dt><dd>#{npc.nId}</dd></div><div><dt>Charakter-Untertyp</dt><dd>#{npc.charId}</dd></div><div><dt>Geschlecht</dt><dd>{personGenderLabel(npc.gender)}</dd></div><div><dt>Status</dt><dd>{npc.alive?"Lebendig":"Verstorben"}</dd></div>{!npc.alive&&chronology.deathLabel?<div><dt>Gestorben</dt><dd>{chronology.deathLabel}</dd></div>:null}{!npc.alive&&causeText?<div><dt>Todesursache</dt><dd>{causeText}</dd></div>:null}<div><dt>Ort</dt><dd>{npc.location}</dd></div><div><dt>Spezies-Pfad</dt><dd>{racePath}</dd></div><div><dt>Angezeigte Bezeichnung</dt><dd>{npc.race}</dd></div><div><dt>Alter</dt><dd>{ageLabel}</dd></div><div><dt>Profilbild</dt><dd>{imageProfile?"1:1-Zuschnitt":"Original-Fallback"}</dd></div><div><dt>Sichtbarkeit</dt><dd>{visibilityLabel(npc.visibilityMode)}</dd></div></dl></section>
      <section className="panel-card profile-summary"><div className="panel-heading"><div><span className="panel-kicker">RÄUMLICHE VERORTUNG</span><h2>{spatialLocations.length} Orte</h2></div></div><p className="section-help">{spatialPath}</p><div className="stack"><Link className="button primary" href={`/admin/projects/${projectId}/npcs/${npcId}/locations`}>📍 Orte verwalten</Link>{mappedCurrent?.map_id&&mappedCurrent.map_feature_id?<Link className="button" href={`/admin/projects/${projectId}/map?mapId=${mappedCurrent.map_id}&featureId=${mappedCurrent.map_feature_id}`}>Auf Karte anzeigen</Link>:null}</div></section>
      <section className="panel-card profile-summary"><div className="panel-heading"><div><span className="panel-kicker">VERKNÜPFUNGEN</span><h2>Hinzufügen & verwalten</h2></div></div><div className="stack"><Link className="button primary" href={`/admin/projects/${projectId}/relationships?personId=${npc.nId}&create=1`}>＋ Beziehung hinzufügen</Link><Link className="button" href={`/admin/projects/${projectId}/relationships?personId=${npc.nId}`}>Beziehungen verwalten</Link><Link className="button" href={`/admin/projects/${projectId}/groups?personId=${npc.nId}`}>＋ Gruppe zuordnen</Link><Link className="button" href={`/admin/projects/${projectId}/family-trees?personId=${npc.nId}`}>＋ Zu Stammbaum</Link><Link className="button" href={`/admin/projects/${projectId}/family-trees/all`}>Im Gesamtgraph anzeigen</Link></div></section><Link className="button primary" href={`/admin/projects/${projectId}/npcs/${npcId}/visibility`}>Spieler-Sichtbarkeit</Link></aside></form>
    <section className="danger-zone"><div><span className="panel-kicker">GEFAHRENBEREICH</span><h2>Person archivieren</h2><p>Legacy-Zeilen werden nicht physisch gelöscht.</p></div><ConfirmAction action={archiveNpcAction.bind(null,projectId,npcId)} title={`${npc.name} archivieren?`} description="Die Person verschwindet aus aktiven Listen. Legacy-Zeilen und historische Daten bleiben erhalten." triggerLabel="Archivieren…" confirmLabel="Person archivieren" triggerClassName="button danger"/></section>
  </AdminShell>;
}
