import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { Pagination } from "@/components/pagination";
import { requireAdminSession } from "@/lib/auth/session";
import { listTimelineEventsPaginated, type TimelineListFilters } from "@/lib/entities/timeline";
import { listLocations } from "@/lib/entities/locations";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";
import { createTimelineEventAction } from "./actions";

type Search=Promise<{q?:string;category?:string;visibility?:string;page?:string;pageSize?:string}>;
export default async function TimelinePage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [{projectId:raw},search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const visibility=["admin_only","all_players","selected_players"].includes(search.visibility??"")?search.visibility as TimelineListFilters["visibility"]:undefined;const pagination=parsePagination(search);
  const [project,events,locations]=await Promise.all([getProject(projectId),listTimelineEventsPaginated(projectId,{query:search.q,category:search.category||undefined,visibility},pagination),listLocations(projectId)]);if(!project)notFound();const path=`/admin/projects/${projectId}/timeline`;
  return <AdminShell projectId={projectId} projectName={project.name} eyebrow={`${project.name} / Geschichte`} title="Timeline">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Timeline</strong></div><h1>Weltgeschichte</h1><p>Fantasy-Daten werden über Anzeige-Datum und numerischen Sortierwert getrennt gespeichert.</p></div><details className="create-dropdown"><summary className="button primary">＋ Event</summary><div className="create-popover"><form action={createTimelineEventAction.bind(null,projectId)} className="stack"><label>Name<input name="name" required/></label><label>Display Date<input name="displayDate" placeholder="3. Zeitalter, Jahr 81"/></label><label>Sort Value<input name="sortValue" type="number" step="0.000001"/></label><label>Ära<input name="era"/></label><div className="row"><label>Jahr<input name="fantasyYear" type="number"/></label><label>Monat<input name="fantasyMonth" type="number"/></label><label>Tag<input name="fantasyDay" type="number"/></label></div><label>Location<select name="locationId"><option value="">—</option>{locations.map((l)=><option key={l.loc_id} value={l.loc_id}>{l.name}</option>)}</select></label><label>Kategorie<input name="category"/></label><label>Wichtigkeit<input name="importance" type="number" min="0" max="10" defaultValue="0"/></label><label>Beschreibung<textarea name="notes"/></label><label>Sichtbarkeit<select name="visibilityMode"><option value="admin_only">Admin only</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label><button className="primary">Event anlegen</button></form></div></details></div>
    <section className="panel-card"><form className="filter-bar" method="get"><label className="search-box"><span aria-hidden="true">⌕</span><input name="q" defaultValue={search.q??""} placeholder="Event, Ära, Datum oder Location suchen …"/></label><input name="category" defaultValue={search.category??""} placeholder="Kategorie"/><select name="visibility" defaultValue={visibility??""}><option value="">Alle Sichtbarkeiten</option><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select><button>Filtern</button></form><div className="table-meta"><span><strong>{events.total}</strong> Events</span><span>Stabil nach Sort Value / Datum / ID</span></div>{events.items.length===0?<div className="empty-state large"><strong>Noch keine Timeline Events</strong></div>:<div className="timeline-list">{events.items.map((event)=><article className="panel-card nested-card" key={event.e_id}><div className="row"><span className="soft-label">{event.display_date||event.era||"Unbekannt"}</span><span className="soft-label">{event.category||"Event"}</span><span className="muted">Wichtigkeit {event.importance}</span></div><h2>{event.name}</h2><p>{event.notes}</p><div className="row"><span>{event.location_name||"Keine Location"}</span><Link className="button ghost" href={`/admin/projects/${projectId}/timeline/${event.e_id}`}>Bearbeiten</Link></div></article>)}</div>}<Pagination pathname={path} searchParams={{q:search.q,category:search.category,visibility:search.visibility}} page={events.page} pageSize={events.pageSize} total={events.total} totalPages={events.totalPages}/></section>
  </AdminShell>;
}
