import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { EntityPicker } from "@/components/entity-picker";
import { FantasyDateInput } from "@/components/fantasy-date-input";
import { ImageSourceInput } from "@/components/image-source-input";
import { Pagination } from "@/components/pagination";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { calendarStatus, getProjectCalendar } from "@/lib/calendar";
import { listTimelineEventsPaginated, type TimelineListFilters } from "@/lib/entities/timeline";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";
import { createTimelineEventAction } from "./actions";

type Search=Promise<{q?:string;category?:string;visibility?:string;page?:string;pageSize?:string}>;
export default async function TimelinePage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [{projectId:raw},search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const visibility=["admin_only","all_players","selected_players"].includes(search.visibility??"")?search.visibility as TimelineListFilters["visibility"]:undefined;const pagination=parsePagination(search);
  const [project,events,calendar]=await Promise.all([getProject(projectId),listTimelineEventsPaginated(projectId,{query:search.q,category:search.category||undefined,visibility},pagination),getProjectCalendar(projectId)]);if(!project)notFound();const path=`/admin/projects/${projectId}/timeline`;const ready=calendar?calendarStatus(calendar).ready:false;const hasFilters=Boolean(search.q||search.category||search.visibility);
  return <AdminShell projectId={projectId} projectName={project.name} section="timeline" eyebrow={`${project.name} / Geschichte`} title="Timeline">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Timeline</strong></div><h1>Weltgeschichte</h1><p>Events verwenden denselben frei konfigurierbaren Weltkalender wie Geburtsdaten und Stammbäume. Sortierung erfolgt über den normalisierten World Day.</p></div>{ready&&calendar?<details className="create-dropdown"><summary className="button primary">＋ Event</summary><div className="create-popover" style={{minWidth:620}}><form action={createTimelineEventAction.bind(null,projectId)} className="stack"><label>Name<input name="name" required/></label><FantasyDateInput prefix="event" label="Event-Datum" months={calendar.months} beforeEraLabel={calendar.beforeEraLabel} afterEraLabel={calendar.afterEraLabel} hasYearZero={calendar.hasYearZero} allowUnknown={false}/><EntityPicker projectId={projectId} name="locationId" types={["location"]} label="Location" placeholder="Location suchen …"/><label>Kategorie<input name="category"/></label><label>Wichtigkeit<input name="importance" type="number" min="0" max="10" defaultValue="0"/></label><ImageSourceInput label="Event-Bild"/><label>Beschreibung<textarea name="notes"/></label><label>Sichtbarkeit<select name="visibilityMode"><option value="admin_only">Admin only</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label><SubmitButton className="primary" pendingLabel="Event wird angelegt …">Event anlegen</SubmitButton></form></div></details>:<Link className="button primary" href={`/admin/projects/${projectId}/settings/calendar`}>Weltkalender konfigurieren</Link>}</div>
    {!ready?<div className="notice warning"><strong>Timeline-Datenerfassung ist gesperrt, bis der Weltkalender konsistent ist.</strong> Bestehende Legacy-Events bleiben sichtbar und unverändert.</div>:null}
    <section className="panel-card"><form className="filter-bar" method="get"><label className="search-box"><span aria-hidden="true">⌕</span><input name="q" defaultValue={search.q??""} placeholder="Event, Ära, Datum oder Location suchen …"/></label><input name="category" defaultValue={search.category??""} placeholder="Kategorie"/><select name="visibility" defaultValue={visibility??""}><option value="">Alle Sichtbarkeiten</option><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select><button>Filtern</button>{hasFilters?<Link className="button ghost" href={path}>Zurücksetzen</Link>:null}</form><div className="table-meta"><span><strong>{events.total}</strong> Events</span><span>Sortierung: World Day / Legacy Sort Value / ID</span></div>{events.items.length===0?<div className="empty-state large"><strong>Keine Timeline Events gefunden</strong><span>{hasFilters?"Filter ändern oder zurücksetzen.":"Lege das erste Ereignis an."}</span></div>:<div className="timeline-list">{events.items.map((event)=><article className="panel-card nested-card" key={event.e_id}><div className="row"><span className="soft-label">{event.display_date||event.era||"Unbekannt"}</span><span className="soft-label">{event.category||"Event"}</span><span className="muted">Wichtigkeit {event.importance}</span></div><div className="row">{event.image&&event.image!=="noimage"?<span className="entity-avatar"><img src={event.image} alt="" loading="lazy"/></span>:null}<div><h2>{event.name}</h2><p>{event.notes}</p></div></div><div className="row"><span>{event.location_name||"Keine Location"}</span><Link className="button ghost" href={`/admin/projects/${projectId}/timeline/${event.e_id}`}>Bearbeiten</Link></div></article>)}</div>}<Pagination pathname={path} searchParams={{q:search.q,category:search.category,visibility:search.visibility}} page={events.page} pageSize={events.pageSize} total={events.total} totalPages={events.totalPages}/></section>
  </AdminShell>;
}
