import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { listTimelineEvents } from "@/lib/entities/timeline";
import { listLocations } from "@/lib/entities/locations";
import { getProject } from "@/lib/projects";
import { createTimelineEventAction } from "./actions";

export default async function TimelinePage({params}:{params:Promise<{projectId:string}>}){
 await requireAdminSession();const projectId=Number.parseInt((await params).projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const [project,events,locations]=await Promise.all([getProject(projectId),listTimelineEvents(projectId),listLocations(projectId)]);if(!project)notFound();
 return <AdminShell projectId={projectId} projectName={project.name} eyebrow={`${project.name} / Geschichte`} title="Timeline">
  <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Timeline</strong></div><h1>Weltgeschichte</h1><p>Fantasy-Daten werden über Anzeige-Datum und numerischen Sortierwert getrennt gespeichert.</p></div><details className="create-dropdown"><summary className="button primary">＋ Event</summary><div className="create-popover"><form action={createTimelineEventAction.bind(null,projectId)} className="stack"><label>Name<input name="name" required/></label><label>Display Date<input name="displayDate" placeholder="3. Zeitalter, Jahr 81"/></label><label>Sort Value<input name="sortValue" type="number" step="0.000001"/></label><label>Ära<input name="era"/></label><div className="row"><label>Jahr<input name="fantasyYear" type="number"/></label><label>Monat<input name="fantasyMonth" type="number"/></label><label>Tag<input name="fantasyDay" type="number"/></label></div><label>Location<select name="locationId"><option value="">—</option>{locations.map((l)=><option key={l.loc_id} value={l.loc_id}>{l.name}</option>)}</select></label><label>Kategorie<input name="category"/></label><label>Wichtigkeit<input name="importance" type="number" min="0" max="10" defaultValue="0"/></label><label>Beschreibung<textarea name="notes"/></label><label>Sichtbarkeit<select name="visibilityMode"><option value="admin_only">Admin only</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label><button className="primary">Event anlegen</button></form></div></details></div>
  <section className="panel-card"><div className="table-meta"><span><strong>{events.length}</strong> Events</span></div>{events.length===0?<div className="empty-state large"><strong>Noch keine Timeline Events</strong></div>:<div className="timeline-list">{events.map((event)=><article className="panel-card nested-card" key={event.e_id}><div className="row"><span className="soft-label">{event.display_date||event.era||"Unbekannt"}</span><span className="soft-label">{event.category||"Event"}</span><span className="muted">Wichtigkeit {event.importance}</span></div><h2>{event.name}</h2><p>{event.notes}</p><div className="row"><span>{event.location_name||"Keine Location"}</span><Link className="button ghost" href={`/admin/projects/${projectId}/timeline/${event.e_id}`}>Bearbeiten</Link></div></article>)}</div>}</section>
 </AdminShell>;
}
