import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { listRelationships } from "@/lib/entities/relationships";
import { getProject } from "@/lib/projects";

export default async function RelationshipGraphPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{category?:string}>}){
 await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const [project,relations]=await Promise.all([getProject(projectId),listRelationships(projectId)]);if(!project)notFound();const category=search.category?.trim();const visible=category?relations.filter((r)=>r.type_code===category):relations;
 return <AdminShell projectId={projectId} projectName={project.name} eyebrow={`${project.name} / Wissen`} title="Relationship Graph"><div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}/relationships`}>Beziehungen</Link><span>/</span><strong>Graph</strong></div><h1>Beziehungsnetz</h1><p>Gerichtete und ungerichtete Kanten werden aus echten Relationship-Datensätzen dargestellt.</p></div></div><section className="panel-card"><form className="filter-bar"><select name="category" defaultValue={category??""}><option value="">Alle Beziehungen</option><option value="parent">Familie: Parent</option><option value="spouse">Familie: Ehepartner</option><option value="friend">Freunde</option><option value="enemy">Feinde</option><option value="ally">Verbündete</option><option value="member">Gruppen</option><option value="worships">Religion</option></select><button>Filtern</button></form><div className="relationship-graph">{visible.map((r)=><div key={r.relationship_id} className="relationship-edge"><span className="graph-node">{r.entity_a_type}<strong>#{r.entity_a_id}</strong></span><span className="graph-edge-label">{r.directed?"→":"↔"}<small>{r.type_label}</small></span><span className="graph-node">{r.entity_b_type}<strong>#{r.entity_b_id}</strong></span></div>)}</div>{visible.length===0?<div className="empty-state"><strong>Keine Kanten für diesen Filter</strong></div>:null}</section></AdminShell>;
}
