import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { Pagination } from "@/components/pagination";
import { requireAdminSession } from "@/lib/auth/session";
import { listRelationshipTypes, listRelationshipsPaginated } from "@/lib/entities/relationships";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";

export default async function RelationshipGraphPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{type?:string;page?:string;pageSize?:string}>}){
  await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const pagination=parsePagination(search);const typesPromise=listRelationshipTypes();const projectPromise=getProject(projectId);const types=await typesPromise;const selectedType=types.find((type)=>type.code===search.type);const [project,relations]=await Promise.all([projectPromise,listRelationshipsPaginated(projectId,{relationshipTypeId:selectedType?.relationship_type_id},pagination)]);if(!project)notFound();const path=`/admin/projects/${projectId}/relationship-graph`;
  return <AdminShell projectId={projectId} projectName={project.name} section="relationships" eyebrow={`${project.name} / Wissen`} title="Relationship Graph"><div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}/relationships`}>Beziehungen</Link><span>/</span><strong>Graph</strong></div><h1>Beziehungsnetz</h1><p>Die Graph-Ansicht lädt serverseitig nur die aktuelle Seite statt sämtliche Beziehungen des Projekts. Endpunkte werden als echte Namen und Typen aufgelöst.</p></div></div><section className="panel-card"><form className="filter-bar"><select name="type" defaultValue={selectedType?.code??""}><option value="">Alle Beziehungen</option>{types.map((type)=><option key={type.relationship_type_id} value={type.code}>{type.category} · {type.label}</option>)}</select><button>Filtern</button>{selectedType?<Link className="button ghost" href={path}>Zurücksetzen</Link>:null}</form><div className="table-meta"><span><strong>{relations.total}</strong> Beziehungen</span><span>{relations.items.length?`${(relations.page-1)*relations.pageSize+1}–${Math.min(relations.page*relations.pageSize,relations.total)} sichtbar`:"Keine sichtbar"}</span></div><div className="relationship-graph">{relations.items.map((r)=><div key={r.relationship_id} className="relationship-edge"><span className="graph-node"><small>{r.a_kind}</small><strong>{r.a_name}</strong></span><span className="graph-edge-label">{r.directed?"→":"↔"}<small>{r.type_label}</small></span><span className="graph-node"><small>{r.b_kind}</small><strong>{r.b_name}</strong></span></div>)}</div>{relations.items.length===0?<div className="empty-state"><strong>Keine Kanten für diesen Filter</strong></div>:null}<Pagination pathname={path} searchParams={{type:selectedType?.code}} page={relations.page} pageSize={relations.pageSize} total={relations.total} totalPages={relations.totalPages}/></section></AdminShell>;
}
