import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityPicker } from "@/components/entity-picker";
import { ImageSourceInput } from "@/components/image-source-input";
import { WorldMapViewer } from "@/components/map/world-map-viewer";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { getLocation,getLocationPath,LOCATION_KINDS } from "@/lib/entities/locations";
import { getLocationSpatialSummary,listLocationChildren } from "@/lib/location-spatial";
import { locationKindLabel } from "@/lib/location-presentation";
import { listMapFeatures,listMapLayers } from "@/lib/map-features";
import { getProjectMap } from "@/lib/maps";
import { getProject } from "@/lib/projects";
import { archiveLocationAction,updateLocationAction } from "../actions";

function visibilityLabel(value:string){return value==="all_players"?"Alle Spieler":value==="selected_players"?"Ausgewählte Spieler":"Nur Admin";}

export default async function LocationDetailPage({params}:{params:Promise<{projectId:string;locationId:string}>}){
  await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10),locationId=Number.parseInt(raw.locationId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(locationId)||projectId<=0||locationId<=0)notFound();
  const [project,location,path,summary,children]=await Promise.all([getProject(projectId),getLocation(projectId,locationId),getLocationPath(projectId,locationId),getLocationSpatialSummary(projectId,locationId),listLocationChildren(projectId,locationId)]);if(!project||!location)notFound();
  const mapped=Boolean(location.map_id&&location.map_feature_id);const map=mapped?await getProjectMap(projectId,Number(location.map_id)):null;const mapData=map?await Promise.all([listMapLayers(projectId,Number(map.map_id)),listMapFeatures(projectId,Number(map.map_id))]):null;
  const mapConfig=map?{mapId:Number(map.map_id),mapType:map.map_type as "tile"|"image",tileUrl:map.tile_url,imagePath:map.image_path,minZoom:map.min_zoom,maxZoom:map.max_zoom,centerLat:map.center_lat,centerLng:map.center_lng,bounds:map.bounds,config:map.config}:null;
  const childKind=location.location_kind==="country"?"province":location.location_kind==="province"||location.location_kind==="region"?"city":location.location_kind==="city"?"district":location.location_kind==="district"?"building":null;
  return <AdminShell projectId={projectId} projectName={project.name} section="locations" title={String(location.name)} eyebrow={`${project.name} / Orte`}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/locations`}>Orte</Link>{path.map(item=><span key={item.loc_id}>/ {item.loc_id===locationId?<strong>{item.name}</strong>:<Link href={`/admin/projects/${projectId}/locations/${item.loc_id}`}>{item.name}</Link>}</span>)}</div>
    <section className="entity-hero"><div className="entity-avatar hero-avatar">{location.coat_of_arm?<img src={String(location.coat_of_arm)} alt="" loading="lazy"/>:String(location.name).slice(0,1).toUpperCase()}</div><div className="entity-hero-main"><span className="page-kicker">{locationKindLabel(location.location_kind)}</span><h1>{String(location.name)}</h1><p>{location.location_type?String(location.location_type):locationKindLabel(location.location_kind)}</p><div className="row wrap-row">{mapped?<><Link className="button primary" href={`/admin/projects/${projectId}/map?mapId=${location.map_id}&featureId=${location.map_feature_id}`}>Auf Karte anzeigen</Link><Link className="button ghost" href={`/admin/projects/${projectId}/map/studio?mapId=${location.map_id}&featureId=${location.map_feature_id}`}>Grenze / Position bearbeiten</Link></>:<Link className="button primary" href={`/admin/projects/${projectId}/map/studio?tool=${["country","province","region","city"].includes(location.location_kind)?location.location_kind:"place"}`}>Auf Karte platzieren</Link>}{childKind?<Link className="button ghost" href={`/admin/projects/${projectId}/locations?parentId=${locationId}&createKind=${childKind}`}>＋ {locationKindLabel(childKind)} hinzufügen</Link>:null}</div></div></section>

    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:10,marginBottom:14}}>
      <div className="panel-card"><span className="panel-kicker">UNTERORTE</span><strong style={{fontSize:"1.5rem",display:"block"}}>{summary.descendantCount}</strong><span className="muted">{summary.childCount} direkt untergeordnet</span></div>
      <div className="panel-card"><span className="panel-kicker">SIEDLUNGEN</span><strong style={{fontSize:"1.5rem",display:"block"}}>{summary.settlementCount}</strong><span className="muted">Städte, Kleinstädte & Dörfer</span></div>
      <div className="panel-card"><span className="panel-kicker">NPCS</span><strong style={{fontSize:"1.5rem",display:"block"}}>{summary.descendantNpcCount}</strong><span className="muted">{summary.directNpcCount} direkt an diesem Ort</span></div>
      <div className="panel-card"><span className="panel-kicker">KARTE</span><strong style={{fontSize:"1.1rem",display:"block"}}>{mapped?"Verknüpft":"Nicht platziert"}</strong><span className="muted">{map?.name??"Noch keine Geometrie"}</span></div>
    </section>

    {mapConfig&&mapData?<section className="panel-card" style={{marginBottom:14}}><div className="panel-heading"><div><span className="panel-kicker">KARTENVORSCHAU</span><h2>{location.name} in der Welt</h2></div><Link className="button ghost" href={`/admin/projects/${projectId}/map?mapId=${location.map_id}&featureId=${location.map_feature_id}`}>Groß öffnen</Link></div><WorldMapViewer mapConfig={mapConfig} layers={mapData[0]} features={mapData[1]} focusFeatureId={Number(location.map_feature_id)} height="360px" showSearch={false}/></section>:null}

    {children.length?<section className="panel-card" style={{marginBottom:14}}><div className="panel-heading"><div><span className="panel-kicker">HIERARCHIE</span><h2>Direkt untergeordnete Orte</h2></div></div><div className="entity-card-grid">{children.map(child=><article key={child.loc_id} className="panel-card nested-card"><span className="soft-label">{locationKindLabel(child.location_kind)}</span><h3>{child.name}</h3><div className="row wrap-row"><Link className="button ghost" href={`/admin/projects/${projectId}/locations/${child.loc_id}`}>Öffnen</Link>{child.map_id&&child.map_feature_id?<Link className="button ghost" href={`/admin/projects/${projectId}/map?mapId=${child.map_id}&featureId=${child.map_feature_id}`}>Auf Karte</Link>:null}</div></article>)}</div></section>:null}

    <form action={updateLocationAction.bind(null,projectId,locationId)} className="npc-detail-grid"><div className="stack detail-main"><section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">ORT & HIERARCHIE</span><h2>Grunddaten</h2></div></div><div className="field-grid two">
      <label>Name<input name="name" defaultValue={String(location.name)} required/></label><label>Art<select name="locationKind" defaultValue={location.location_kind}>{LOCATION_KINDS.map(kind=><option key={kind} value={kind}>{locationKindLabel(kind)}</option>)}</select></label>
      <label>Beschreibungstyp<input name="locationType" defaultValue={location.location_type?String(location.location_type):""} placeholder="z. B. Königreich, Hafenstadt …"/></label><label>Slug<input name="slug" defaultValue={location.slug??""} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="koenigreich-erigon"/></label>
      <EntityPicker projectId={projectId} name="parentLocId" types={["location"]} label="Gehört zu" placeholder="Übergeordneten Ort suchen …" initialValue={location.parent_loc_id?String(location.parent_loc_id):""} initialLabel={location.parent_name??""} initialKind="Location"/>
      <EntityPicker projectId={projectId} name="ownerNpcId" types={["person"]} label="Besitzer / Herrscher" placeholder="Person suchen …" initialValue={location.owner_n_id?String(location.owner_n_id):""} initialLabel={location.owner_name??""}/>
      <EntityPicker projectId={projectId} name="capitalLocId" types={["location"]} label="Hauptstadt / Hauptort" placeholder="Hauptstadt suchen …" initialValue={location.capital_loc_id?String(location.capital_loc_id):""} initialLabel={location.capital_name??""} initialKind="Location"/>
      <label>Bevölkerung<input name="population" type="number" min="0" defaultValue={location.population?String(location.population):""}/></label>
      <label>Sichtbarkeit<select name="visibilityMode" defaultValue={String(location.visibility_mode)}><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte Spieler</option></select></label>
    </div><ImageSourceInput current={location.coat_of_arm?String(location.coat_of_arm):null} pathName="coatOfArm" fileName="coatOfArmFile" label="Wappen / Bild"/><label>Beschreibung<textarea name="description" className="large-textarea" defaultValue={location.description?String(location.description):""}/></label><details><summary style={{cursor:"pointer",fontWeight:600}}>Erweiterte Kartenbindung</summary><div className="field-grid two" style={{paddingTop:10}}><label>Map ID<input name="mapId" type="number" min="1" defaultValue={location.map_id??""} readOnly={Boolean(location.map_feature_id)}/></label><label>Feature ID<input name="mapFeatureId" type="number" min="1" defaultValue={location.map_feature_id??""} readOnly/></label></div></details></section><div className="sticky-savebar"><div><strong>Änderungen speichern</strong><span>Die Location bleibt die kanonische räumliche Entität für NPCs und Kartenobjekte.</span></div><SubmitButton className="primary" pendingLabel="Speichere Ort …">Speichern</SubmitButton></div></div><aside className="stack detail-side"><section className="panel-card"><span className="panel-kicker">RÄUMLICHER PFAD</span><p>{path.map(item=>item.name).join(" › ")}</p><Link className="button ghost" href={`/admin/projects/${projectId}/npcs?locationId=${locationId}`}>NPCs an diesem Ort</Link></section><section className="panel-card"><span className="panel-kicker">SICHTBARKEIT</span><strong>{visibilityLabel(location.visibility_mode)}</strong></section></aside></form>
    <section className="danger-zone"><div><h2>Ort archivieren</h2><p>Der Lore-Datensatz wird nicht hart gelöscht. Karten-Geometrie und Verknüpfungen sollten vorher geprüft werden.</p></div><ConfirmAction action={archiveLocationAction.bind(null,projectId,locationId)} title={`${String(location.name)} archivieren?`} description="Der Ort verschwindet aus aktiven Listen. Der Datensatz wird nicht hart gelöscht." triggerLabel="Archivieren…" confirmLabel="Ort archivieren" triggerClassName="button danger"/></section>
  </AdminShell>;
}
