import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { EntityPicker } from "@/components/entity-picker";
import { ImageSourceInput } from "@/components/image-source-input";
import { Pagination } from "@/components/pagination";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { LOCATION_KINDS,listLocationsPaginated,type LocationKind,type LocationListFilters } from "@/lib/entities/locations";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";
import { createLocationAction } from "./actions";

type Search=Promise<{q?:string;visibility?:string;kind?:string;page?:string;pageSize?:string}>;
function validImage(value:string|null){return Boolean(value&&value.trim()&&value!=="noimage");}
export default async function LocationsPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [{projectId:raw},search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const visibility=["admin_only","all_players","selected_players"].includes(search.visibility??"")?search.visibility as LocationListFilters["visibility"]:undefined;const kind=LOCATION_KINDS.includes((search.kind??"") as LocationKind)?search.kind as LocationKind:undefined;const pagination=parsePagination(search);
  const [project,locations]=await Promise.all([getProject(projectId),listLocationsPaginated(projectId,{query:search.q,visibility,kind},pagination)]);if(!project)notFound();const path=`/admin/projects/${projectId}/locations`;const hasFilters=Boolean(search.q||search.visibility||search.kind);
  return <AdminShell projectId={projectId} projectName={project.name} section="locations" eyebrow={`${project.name} / World`} title="Locations">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Locations</strong></div><h1>Räumliche Hierarchie</h1><p>Baue Welt → Kontinent → Land → Provinz → Stadt → Bezirk → Gebäude. Karten-Features können Locations direkt aus dem Map Editor erzeugen; NPCs können anschließend bis auf Gebäudeebene lokalisiert werden.</p></div><details className="create-dropdown"><summary className="button primary">＋ Location</summary><div className="create-popover"><form action={createLocationAction.bind(null,projectId)} className="stack"><label>Name<input name="name" required maxLength={100}/></label><label>Strukturtyp<select name="locationKind" defaultValue="city">{LOCATION_KINDS.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>Lore-Typ<input name="locationType" maxLength={80} placeholder="z. B. Freie Handelsstadt"/></label><label>Slug<input name="slug" maxLength={140} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="freie-stadt-erigon"/></label><EntityPicker projectId={projectId} name="parentLocId" types={["location"]} label="Parent" placeholder="Land, Provinz oder Stadt suchen …"/><label>Beschreibung<textarea name="description"/></label><ImageSourceInput pathName="coatOfArm" fileName="coatOfArmFile" label="Wappen / Bild"/><label>Population<input name="population" type="number" min="0"/></label><label>Sichtbarkeit<select name="visibilityMode"><option value="admin_only">Admin only</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label><SubmitButton className="primary" pendingLabel="Location wird angelegt …">Anlegen</SubmitButton></form></div></details></div>
    <section className="panel-card"><form className="filter-bar" method="get"><label className="search-box"><span aria-hidden="true">⌕</span><input name="q" defaultValue={search.q??""} placeholder="Location, Typ, Parent oder Owner suchen …"/></label><select name="kind" defaultValue={kind??""}><option value="">Alle Typen</option>{LOCATION_KINDS.map(value=><option key={value} value={value}>{value}</option>)}</select><select name="visibility" defaultValue={visibility??""}><option value="">Alle Sichtbarkeiten</option><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select><button>Filtern</button>{hasFilters?<Link className="button ghost" href={path}>Zurücksetzen</Link>:null}</form><div className="table-meta"><span><strong>{locations.total}</strong> Locations</span><span>Projekt #{projectId}</span></div>{locations.items.length===0?<div className="empty-state large"><strong>Keine Locations</strong><span>{hasFilters?"Filter ändern oder zurücksetzen.":"Lege die erste Location an oder zeichne sie im Map Editor."}</span></div>:<div className="table-scroll"><table className="entity-table"><thead><tr><th>Name</th><th>Struktur</th><th>Lore-Typ</th><th>Parent</th><th>Karte</th><th>Sichtbarkeit</th><th/></tr></thead><tbody>{locations.items.map(location=><tr key={location.loc_id}><td><Link className="entity-cell" href={`/admin/projects/${projectId}/locations/${location.loc_id}`}><span className="entity-avatar">{validImage(location.coat_of_arm)?<img src={location.coat_of_arm!} alt="" loading="lazy"/>:location.name.slice(0,1).toUpperCase()}</span><strong>{location.name}</strong></Link></td><td><code>{location.location_kind}</code></td><td>{location.location_type||"—"}</td><td>{location.parent_name||"—"}</td><td>{location.map_feature_id?<Link href={`/admin/projects/${projectId}/map/studio?mapId=${location.map_id}`}>Feature #{location.map_feature_id}</Link>:"—"}</td><td>{location.visibility_mode}</td><td><Link className="table-action" href={`/admin/projects/${projectId}/locations/${location.loc_id}`}>→</Link></td></tr>)}</tbody></table></div>}<Pagination pathname={path} searchParams={{q:search.q,visibility:search.visibility,kind:search.kind}} page={locations.page} pageSize={locations.pageSize} total={locations.total} totalPages={locations.totalPages}/></section>
  </AdminShell>;
}
