import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityPicker } from "@/components/entity-picker";
import { ImageSourceInput } from "@/components/image-source-input";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { getCulture, listCultureRaces } from "@/lib/entities/cultures";
import { listRaces, raceHierarchyLabel } from "@/lib/entities/races";
import { getProject } from "@/lib/projects";
import { archiveCultureAction, linkCultureRaceAction, unlinkCultureRaceAction, updateCultureAction } from "../actions";

function visibilityLabel(value: string) { return value === "all_players" ? "Alle Spieler" : value === "selected_players" ? "Ausgewählte Spieler" : "Nur Admin"; }

export default async function CultureDetailPage({ params }: { params: Promise<{ projectId: string; cultureId: string }> }) {
  await requireAdminSession(); const raw = await params; const projectId = Number.parseInt(raw.projectId,10), cultureId = Number.parseInt(raw.cultureId,10);
  if (!Number.isSafeInteger(projectId) || !Number.isSafeInteger(cultureId) || projectId <= 0 || cultureId <= 0) notFound();
  const [project, culture, linkedRaces, races] = await Promise.all([getProject(projectId), getCulture(projectId,cultureId), listCultureRaces(projectId,cultureId), listRaces(projectId)]); if (!project || !culture) notFound();
  const available = races.filter((race) => !race.isUnknown && !linkedRaces.some((linked) => linked.raceId === race.raceId));
  return <AdminShell projectId={projectId} projectName={project.name} section="cultures" eyebrow={`${project.name} / Kulturen`} title={culture.name}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><Link href={`/admin/projects/${projectId}/cultures`}>Kulturen & Völker</Link><span>/</span><strong>{culture.name}</strong></div>
    <section className="entity-hero"><div className="entity-avatar hero-avatar">{culture.image && culture.image !== "noimage" ? <img src={culture.image} alt=""/> : culture.name.slice(0,1).toUpperCase()}</div><div className="entity-hero-main"><span className="page-kicker">Kultur / Volk #{culture.cultureId}</span><h1>{culture.name}</h1><p>{culture.description || "Noch keine Beschreibung."}</p><div className="hero-tags"><span className="soft-label">{linkedRaces.length} Spezies</span>{culture.primaryLocationName ? <span className="soft-label">📍 {culture.primaryLocationName}</span> : null}<span className="soft-label">{visibilityLabel(culture.visibilityMode)}</span></div></div></section>
    <div className="npc-detail-grid"><div className="stack detail-main">
      <form action={updateCultureAction.bind(null, projectId, cultureId)} className="stack">
        <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">IDENTITÄT</span><h2>Kultur & Kerngebiet</h2></div></div><div className="field-grid two"><label>Name<input name="name" defaultValue={culture.name} maxLength={160} required/></label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={culture.visibilityMode}><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte Spieler</option></select></label></div><EntityPicker projectId={projectId} name="primaryLocationId" types={["location"]} label="Kulturelles Kerngebiet" placeholder="Ort suchen …" initialValue={culture.primaryLocationId ? String(culture.primaryLocationId) : ""} initialLabel={culture.primaryLocationName ?? ""} initialKind="Location"/><ImageSourceInput current={culture.image} label="Vorschaubild / Symbol"/><label>Beschreibung<textarea name="description" className="large-textarea" defaultValue={culture.description ?? ""} maxLength={100000}/></label></section>
        <div className="sticky-savebar"><div><strong>Kultur speichern</strong><span>Kultur bleibt von Spezies und politischer Gruppenzugehörigkeit getrennt.</span></div><SubmitButton className="primary" pendingLabel="Kultur wird gespeichert …">Speichern</SubmitButton></div>
      </form>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">BIOLOGISCHE ZUGEHÖRIGKEIT</span><h2>Verknüpfte Spezies</h2></div><strong>{linkedRaces.length}</strong></div>{linkedRaces.length === 0 ? <div className="empty-state"><strong>Noch keine Spezies verknüpft</strong><span>Eine Kultur kann eine oder mehrere Spezies und Subspezies enthalten.</span></div> : <div className="stack">{linkedRaces.map((race) => <div className="row wrap-row" key={race.raceId} style={{justifyContent:"space-between"}}><div><Link href={`/admin/projects/${projectId}/races/${race.raceId}`}><strong>{race.parentName ? `${race.parentName} → ${race.name}` : race.name}</strong></Link>{race.isPrimary ? <span className="soft-label" style={{marginLeft:8}}>Primär</span> : null}{race.notes ? <div className="muted">{race.notes}</div> : null}</div><form action={unlinkCultureRaceAction.bind(null,projectId,cultureId,race.raceId)}><button className="button ghost" type="submit">Entfernen</button></form></div>)}</div>}
        {available.length > 0 ? <form action={linkCultureRaceAction.bind(null,projectId,cultureId)} className="stack" style={{marginTop:16}}><div className="field-grid two"><label>Spezies<select name="raceId" required defaultValue=""><option value="" disabled>Spezies wählen</option>{available.map((race) => <option key={race.raceId} value={race.raceId}>{raceHierarchyLabel(race)}</option>)}</select></label><label>Notiz <span className="muted">optional</span><input name="notes" maxLength={1000} placeholder="z. B. Mehrheitsbevölkerung"/></label></div><label><input type="checkbox" name="isPrimary"/> Primäre Spezies dieser Kultur</label><SubmitButton pendingLabel="Verknüpfe …">Spezies verknüpfen</SubmitButton></form> : null}</section>
    </div><aside className="stack detail-side"><section className="panel-card profile-summary"><span className="panel-kicker">TRENNUNG DER SYSTEME</span><h2>Was gehört wohin?</h2><p><strong>Spezies:</strong> Biologie und vererbbare Merkmale.</p><p><strong>Kultur:</strong> Sprache, Bräuche, Kleidung, Werte und Gesellschaft.</p><p><strong>Gruppe:</strong> konkrete Organisation, Staat, Orden oder Fraktion.</p></section><Link className="button" href={`/admin/projects/${projectId}/races`}>Spezies verwalten</Link></aside></div>
    <section className="danger-zone"><div><span className="panel-kicker">DANGER ZONE</span><h2>Kultur archivieren</h2><p>Verknüpfungen zu Spezies werden nicht als biologische Daten interpretiert.</p></div><ConfirmAction action={archiveCultureAction.bind(null,projectId,cultureId)} title={`${culture.name} archivieren?`} description="Der Datensatz verschwindet aus aktiven Kulturlisten. Die Spezies bleiben unverändert." triggerLabel="Archivieren…" confirmLabel="Kultur archivieren" triggerClassName="button danger"/></section>
  </AdminShell>;
}
