import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { listProjectMaps } from "@/lib/maps";
import { getProject } from "@/lib/projects";
import { createImageMapAction, createTileMapAction, setPrimaryMapAction, updateProjectSettingsAction } from "./actions";

export default async function ProjectSettingsPage({params}:{params:Promise<{projectId:string}>}){
 await requireAdminSession();const projectId=Number.parseInt((await params).projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const [project,maps]=await Promise.all([getProject(projectId),listProjectMaps(projectId)]);if(!project)notFound();
 return <AdminShell projectId={projectId} projectName={project.name} eyebrow={`${project.name} / System`} title="Project Settings">
  <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Settings</strong></div><h1>Projekt & Karten</h1><p>Projektmetadaten, Fantasy-Datum und Primary/Secondary Maps.</p></div></div>
  <div className="npc-detail-grid"><div className="stack detail-main"><section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">PROJECT</span><h2>Allgemein</h2></div></div><form action={updateProjectSettingsAction.bind(null,projectId)} className="stack"><div className="field-grid two"><label>Name<input name="name" required defaultValue={project.name}/></label><label>Status<select name="status" defaultValue={project.status}><option value="active">Active</option><option value="planning">Planning</option><option value="archived">Archived</option></select></label><label>In-World-Datum<input name="inWorldDate" defaultValue={project.in_world_date??""} placeholder="3. Zeitalter, Jahr 81"/></label><label>Logo<input name="logo" defaultValue={project.logo??""}/></label><label>Cover/Bild<input name="image" defaultValue={project.image==="noimage"?"":project.image}/></label></div><label>Beschreibung<textarea name="description" className="large-textarea" defaultValue={project.description}/></label><button className="primary">Projekt speichern</button></form></section>
  <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">MAPS</span><h2>Vorhandene Karten</h2></div></div>{maps.length===0?<div className="empty-state"><strong>Keine Karte</strong></div>:<div className="stack">{maps.map((map)=><div key={map.map_id} className="panel-card nested-card"><div className="row"><strong>{map.name}</strong><span className="soft-label">{map.map_type}</span>{map.is_primary?<span className="visibility-pill all_players">Primary</span>:null}</div><small className="muted">#{map.map_id} · Zoom {map.min_zoom}–{map.max_zoom}</small>{!map.is_primary?<form action={setPrimaryMapAction.bind(null,projectId)}><input type="hidden" name="mapId" value={map.map_id}/><button className="button ghost">Als Primary setzen</button></form>:null}</div>)}</div>}</section></div>
  <aside className="stack detail-side"><section className="panel-card"><span className="panel-kicker">TILE MAP</span><h2>Tile Map hinzufügen</h2><form action={createTileMapAction.bind(null,projectId)} className="stack"><label>Name<input name="name" required/></label><label>Tile URL<input name="tileUrl" placeholder="/tiles/{z}/{x}/{y}.png" required/></label><div className="row"><label>Min Zoom<input name="minZoom" type="number" defaultValue="0"/></label><label>Max Zoom<input name="maxZoom" type="number" defaultValue="6"/></label></div><label><input type="checkbox" name="noWrap" defaultChecked/> No wrap</label><label><input type="checkbox" name="isPrimary"/> Als Primary</label><button className="primary">Tile Map anlegen</button></form></section>
  <section className="panel-card"><span className="panel-kicker">IMAGE MAP</span><h2>Image Map registrieren</h2><p className="muted">Für bereits sicher gespeicherte Kartenbilder; Uploads werden im Media-Bereich verwaltet.</p><form action={createImageMapAction.bind(null,projectId)} className="stack"><label>Name<input name="name" required/></label><label>Storage/Image Path<input name="imagePath" required/></label><label>Breite<input name="width" type="number" min="1" required/></label><label>Höhe<input name="height" type="number" min="1" required/></label><label><input type="checkbox" name="isPrimary"/> Als Primary</label><button className="primary">Image Map anlegen</button></form></section></aside></div>
 </AdminShell>;
}
