"use client";

import { useEffect, useRef, useState } from "react";
import { EntityPicker } from "@/components/entity-picker";
import { FormRequiredLegend } from "@/components/form-ui";
import { SubmitButton } from "@/components/submit-button";
import { addGroupMembershipAction } from "../actions";

type InitialPerson={entityId:number;name:string;kind:string}|null;

export function GroupMemberDialog({projectId,groupId,initialPerson=null,initialOpen=false}:{projectId:number;groupId:number;initialPerson?:InitialPerson;initialOpen?:boolean}){
  const dialogRef=useRef<HTMLDialogElement>(null);const triggerRef=useRef<HTMLButtonElement>(null);const [open,setOpen]=useState(initialOpen);const [dirty,setDirty]=useState(false);
  useEffect(()=>{const dialog=dialogRef.current;if(!dialog)return;if(open&&!dialog.open)dialog.showModal();if(!open&&dialog.open)dialog.close();},[open]);
  function requestClose(){if(dirty&&!window.confirm("Ungespeicherte Eingaben verwerfen?"))return;setOpen(false);setDirty(false);window.requestAnimationFrame(()=>triggerRef.current?.focus());}
  return <><button ref={triggerRef} type="button" className="button primary" onClick={()=>setOpen(true)} aria-haspopup="dialog">＋ Mitglied hinzufügen</button><dialog ref={dialogRef} className="form-dialog" aria-labelledby="group-member-title" onClose={()=>{setOpen(false);setDirty(false);}} onCancel={(event)=>{event.preventDefault();requestClose();}} onClick={(event)=>{if(event.target===event.currentTarget)requestClose();}}>{open?<div className="form-dialog-body"><div className="form-dialog-heading"><div><span className="panel-kicker">NEUE MITGLIEDSCHAFT</span><h2 id="group-member-title">Person zur Gruppe hinzufügen</h2><p>Bestehende Mitglieder werden aus der Suche ausgeschlossen. Nur die Person ist Pflicht; Rolle, Rang und Zeitraum sind optional.</p></div><button type="button" className="button ghost form-dialog-close" onClick={requestClose} aria-label="Dialog schließen">×</button></div><form action={addGroupMembershipAction.bind(null,projectId,groupId)} className="stack" onInput={()=>setDirty(true)}><FormRequiredLegend/><EntityPicker projectId={projectId} name="personId" types={["person"]} label="Person" placeholder="Person suchen …" required allowClear={false} excludeGroupId={groupId} initialValue={initialPerson?String(initialPerson.entityId):""} initialLabel={initialPerson?.name??""} initialKind={initialPerson?.kind??""} hint="Pflichtfeld · bestehende Mitglieder sind ausgeschlossen."/><div className="field-grid two"><label>Rolle <span className="muted">optional</span><input name="role" maxLength={160}/></label><label>Rang <span className="muted">optional</span><input name="rank" maxLength={160}/></label><label>Status<select name="status" defaultValue="active"><option value="active">Aktiv</option><option value="former">Ehemalig</option><option value="pending">Ausstehend</option><option value="honorary">Ehrenmitglied</option><option value="unknown">Unbekannt</option></select></label><label><input name="isLeader" type="checkbox"/> Leitung</label><label>Beginn <span className="muted">optional</span><input name="startDisplay" maxLength={240} placeholder="Fantasy-Datum / Freitext"/></label><label>Ende <span className="muted">optional</span><input name="endDisplay" maxLength={240}/></label></div><label>Notizen <span className="muted">optional</span><textarea name="membershipNotes" maxLength={100000}/></label><div className="form-actions"><button type="button" className="button ghost" onClick={requestClose}>Abbrechen</button><SubmitButton className="primary" pendingLabel="Mitgliedschaft wird gespeichert …">Mitgliedschaft speichern</SubmitButton></div></form></div>:null}</dialog></>;
}
