import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { getGroup } from "@/lib/entities/groups";
import { listLocations } from "@/lib/entities/locations";
import { getProject } from "@/lib/projects";
import { archiveGroupAction, updateGroupAction } from "../actions";

function validImage(value:unknown){return typeof value==="string"&&Boolean(value.trim())&&value!=="noimage";}
function clean(value:unknown){const text=typeof value==="string"?value.trim():"";return text&&text!=="unknown"&&text!=="no notes yet"?text:"";}

export default async function GroupDetailPage({params}:{params:Promise<{projectId:string;groupId:string}>}){
  await requireAdminSession();const raw=await params;const projectId=Number.parseInt(raw.projectId,10);const groupId=Number.parseInt(raw.groupId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(groupId)||projectId<=0||groupId<=0)notFound();
  const [project,group,locations]=await Promise.all([getProject(projectId),getGroup(projectId,groupId),listLocations(projectId)]);if(!project||!group)notFound();
  return <AdminShell projectId={projectId} projectName={project.name} section="groups" title={String(group.name)} eyebrow={`${project.name} / Gruppen`}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/groups`}>Gruppen</Link><span>/</span><strong>{String(group.name)}</strong></div>
    <section className="entity-hero"><div className="entity-avatar hero-avatar">{validImage(group.image)?<img src={String(group.image)} alt=""/>:String(group.name).slice(0,1).toUpperCase()}</div><div className="entity-hero-main"><span className="page-kicker">GRUPPE #{groupId} · {clean(group.group_type)||"Organisation"}</span><h1>{String(group.name)}</h1><p>{clean(group.motto)||`Hauptquartier: ${String(group.location_name)}`}</p><div className="hero-tags"><span className="soft-label">{Number(group.estimated_member_count??group.members)} geschätzt</span><span className="soft-label">{Number(group.known_members??group.relation_members)} bekannt</span></div></div></section>
    <form action={updateGroupAction.bind(null,projectId,groupId)} className="npc-detail-grid"><div className="stack detail-main"><section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">GRUPPENPROFIL</span><h2>Organisation</h2></div><span className="record-id">gr_id #{groupId}</span></div><div className="field-grid two"><label>Name<input name="name" defaultValue={String(group.name)} required/></label><label>Typ<input name="groupType" defaultValue={group.group_type?String(group.group_type):""}/></label><label>Hauptquartier<select name="locationId" defaultValue={String(group.loc_id)}>{locations.map((l)=><option key={l.loc_id} value={l.loc_id}>{l.name}</option>)}</select></label><label>Motto<input name="motto" defaultValue={clean(group.motto)}/></label><label>Bild / Wappen<input name="image" defaultValue={validImage(group.image)?String(group.image):""} placeholder="Bild-URL oder relativer Pfad"/></label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={String(group.visibility_mode)}><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div><label>Beschreibung / Notizen<textarea className="large-textarea" name="notes" defaultValue={clean(group.notes)}/></label></section><div className="sticky-savebar"><div><strong>Gruppe speichern</strong><span>Geschätzte Mitglieder werden durch Membership-CRUD nicht verändert.</span></div><button className="primary">Speichern</button></div></div><aside className="stack detail-side"><section className="panel-card profile-summary"><div className="panel-heading"><div><span className="panel-kicker">MITGLIEDER</span><h2>Größe</h2></div></div><dl className="summary-list"><div><dt>Geschätzt</dt><dd>{Number(group.estimated_member_count??group.members)}</dd></div><div><dt>Relational bekannt</dt><dd>{Number(group.known_members??group.relation_members)}</dd></div><div><dt>Hauptquartier</dt><dd>{String(group.location_name)}</dd></div>{group.parent_group_name?<div><dt>Übergruppe</dt><dd>{String(group.parent_group_name)}</dd></div>:null}</dl></section><Link className="button" href={`/admin/projects/${projectId}/relationships?groupId=${groupId}`}>Gruppen-Beziehungen</Link></aside></form>
    <section className="danger-zone"><div><h2>Gruppe archivieren</h2><p>Keine harte Löschung; Legacy-Daten bleiben erhalten.</p></div><form action={archiveGroupAction.bind(null,projectId,groupId)}><button className="danger">Archivieren</button></form></section>
  </AdminShell>;
}
