import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityPicker } from "@/components/entity-picker";
import { ImageSourceInput } from "@/components/image-source-input";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { getGroup, listGroupMemberships } from "@/lib/entities/groups";
import { getProjectEntityOption } from "@/lib/entity-search";
import { getProject } from "@/lib/projects";
import { addGroupMembershipAction, archiveGroupAction, removeGroupMembershipAction, setGroupMembershipAction, updateGroupAction } from "../actions";

function validImage(value:unknown){return typeof value==="string"&&Boolean(value.trim())&&value!=="noimage";}
function clean(value:unknown){const text=typeof value==="string"?value.trim():"";return text&&!['unknown','no notes yet'].includes(text.toLowerCase())?text:"";}
function personHref(projectId:number,personId:number,kind:string){return kind==="God"?`/admin/projects/${projectId}/gods/${personId}`:`/admin/projects/${projectId}/npcs/${personId}`;}

type Search=Promise<{personId?:string}>;
export default async function GroupDetailPage({params,searchParams}:{params:Promise<{projectId:string;groupId:string}>;searchParams:Search}){
  await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);const groupId=Number.parseInt(raw.groupId,10);if(!Number.isSafeInteger(projectId)||!Number.isSafeInteger(groupId)||projectId<=0||groupId<=0)notFound();
  const requested=Number.parseInt(search.personId??"",10);const requestedPersonPromise=Number.isSafeInteger(requested)&&requested>0?getProjectEntityOption(projectId,"person",requested):Promise.resolve(null);
  const [project,group,members,requestedPerson]=await Promise.all([getProject(projectId),getGroup(projectId,groupId),listGroupMemberships(projectId,groupId),requestedPersonPromise]);if(!project||!group)notFound();
  return <AdminShell projectId={projectId} projectName={project.name} section="groups" title={String(group.name)} eyebrow={`${project.name} / Gruppen`}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}/groups`}>Gruppen</Link><span>/</span><strong>{String(group.name)}</strong></div>
    <section className="entity-hero"><div className="entity-avatar hero-avatar">{validImage(group.image)?<img src={String(group.image)} alt="" loading="lazy"/>:String(group.name).slice(0,1).toUpperCase()}</div><div className="entity-hero-main"><span className="page-kicker">GRUPPE #{groupId} · {clean(group.group_type)||"Organisation"}</span><h1>{String(group.name)}</h1>{clean(group.motto)?<p>{clean(group.motto)}</p>:null}<div className="hero-tags"><span className="soft-label">Hauptquartier: {String(group.location_name)}</span><span className="soft-label">{Number(group.estimated_member_count??group.members)} geschätzt</span><span className="soft-label">{members.length} bekannt</span></div></div></section>
    <form action={updateGroupAction.bind(null,projectId,groupId)} className="npc-detail-grid"><div className="stack detail-main"><section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">GRUPPENPROFIL</span><h2>Organisation</h2></div><span className="record-id">gr_id #{groupId}</span></div><div className="field-grid two"><label>Name<input name="name" defaultValue={String(group.name)} required/></label><label>Typ<input name="groupType" defaultValue={group.group_type?String(group.group_type):""}/></label><EntityPicker projectId={projectId} name="locationId" types={["location"]} label="Hauptquartier" required allowClear={false} initialValue={String(group.loc_id)} initialLabel={String(group.location_name)} initialKind="Location" placeholder="Location suchen …"/><label>Motto<input name="motto" defaultValue={clean(group.motto)}/></label><label>Sichtbarkeit<select name="visibilityMode" defaultValue={String(group.visibility_mode)}><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div><ImageSourceInput current={validImage(group.image)?String(group.image):null} label="Bild / Wappen"/><label>Beschreibung / Notizen<textarea className="large-textarea" name="notes" defaultValue={clean(group.notes)}/></label></section><div className="sticky-savebar"><div><strong>Gruppe speichern</strong><span>Geschätzte Mitglieder werden durch Membership-CRUD nicht verändert.</span></div><SubmitButton className="primary" pendingLabel="Speichere Gruppe …">Speichern</SubmitButton></div></div><aside className="stack detail-side"><section className="panel-card profile-summary"><div className="panel-heading"><div><span className="panel-kicker">GRÖSSE</span><h2>Mitgliederzahlen</h2></div></div><dl className="summary-list"><div><dt>Geschätzt</dt><dd>{Number(group.estimated_member_count??group.members)}</dd></div><div><dt>Relational bekannt</dt><dd>{members.length}</dd></div><div><dt>Hauptquartier</dt><dd>{String(group.location_name)}</dd></div>{group.parent_group_name?<div><dt>Übergruppe</dt><dd>{String(group.parent_group_name)}</dd></div>:null}</dl></section><Link className="button primary" href={`/admin/projects/${projectId}/relationships?groupId=${groupId}&create=1`}>＋ Gruppen-Beziehung</Link><Link className="button" href={`/admin/projects/${projectId}/relationships?groupId=${groupId}`}>Gruppen-Beziehungen verwalten</Link></aside></form>

    <section className="panel-card"><div className="panel-heading"><div><span className="panel-kicker">MEMBERSHIPS</span><h2>Bekannte Mitglieder</h2></div><strong>{members.length}</strong></div><details className="create-dropdown" open={Boolean(requestedPerson)}><summary className="button primary">＋ Mitglied hinzufügen</summary><div className="create-popover"><form action={addGroupMembershipAction.bind(null,projectId,groupId)} className="stack"><EntityPicker projectId={projectId} name="personId" types={["person"]} label="Person" placeholder="Person suchen …" required allowClear={false} excludeGroupId={groupId} initialValue={requestedPerson?String(requestedPerson.entityId):""} initialLabel={requestedPerson?.name??""} initialKind={requestedPerson?.kind??""} hint="Es werden nur passende Treffer geladen; bestehende Mitglieder sind ausgeschlossen."/><div className="field-grid two"><label>Rolle<input name="role"/></label><label>Rang<input name="rank"/></label><label>Status<select name="status" defaultValue="active"><option value="active">Aktiv</option><option value="former">Ehemalig</option><option value="pending">Ausstehend</option><option value="honorary">Ehrenmitglied</option><option value="unknown">Unbekannt</option></select></label><label><input name="isLeader" type="checkbox"/> Leitung</label><label>Beginn<input name="startDisplay" placeholder="Fantasy-Datum / Freitext"/></label><label>Ende<input name="endDisplay" placeholder="optional"/></label></div><label>Notizen<textarea name="membershipNotes"/></label><SubmitButton className="primary" pendingLabel="Mitgliedschaft wird gespeichert …">Mitgliedschaft speichern</SubmitButton></form></div></details>
      {members.length===0?<div className="empty-state"><strong>Noch keine bekannten Mitglieder</strong><span>Über „Mitglied hinzufügen“ serverseitig nach Personen suchen.</span></div>:<div className="stack">{members.map((member)=><article className="panel-card nested-card" key={member.membership_id}><div className="row"><Link className="entity-cell" href={personHref(projectId,member.person_id,member.kind)}><span className="entity-avatar">{validImage(member.image)?<img src={member.image} alt="" loading="lazy"/>:member.name.slice(0,1).toUpperCase()}</span><span><strong>{member.name}</strong><small>{member.kind}{member.is_leader?" · Leitung":""}</small></span></Link><span className="soft-label">{member.membership_status}</span></div><form action={setGroupMembershipAction.bind(null,projectId,groupId,member.person_id)} className="field-grid two"><label>Rolle<input name="role" defaultValue={member.role??""}/></label><label>Rang<input name="rank" defaultValue={member.rank_label??""}/></label><label>Status<select name="status" defaultValue={member.membership_status}><option value="active">Aktiv</option><option value="former">Ehemalig</option><option value="pending">Ausstehend</option><option value="honorary">Ehrenmitglied</option><option value="unknown">Unbekannt</option></select></label><label><input name="isLeader" type="checkbox" defaultChecked={member.is_leader}/> Leitung</label><label>Beginn<input name="startDisplay" defaultValue={member.start_display??""}/></label><label>Ende<input name="endDisplay" defaultValue={member.end_display??""}/></label><label className="full-span">Notizen<textarea name="membershipNotes" defaultValue={member.notes??""}/></label><div className="row"><SubmitButton pendingLabel="Speichere Mitgliedschaft …">Änderungen speichern</SubmitButton></div></form><div className="row end"><ConfirmAction action={removeGroupMembershipAction.bind(null,projectId,groupId,member.person_id)} title={`${member.name} aus ${String(group.name)} entfernen?`} description="Entfernt die kanonische Membership und bei Characters auch den synchronisierten Legacy-is_part_of-Shadow. Die Person selbst bleibt erhalten." triggerLabel="Mitgliedschaft entfernen…" confirmLabel="Mitgliedschaft entfernen"/></div></article>)}</div>}
    </section>
    <section className="danger-zone"><div><h2>Gruppe archivieren</h2><p>Keine harte Löschung; Legacy-Daten bleiben erhalten.</p></div><ConfirmAction action={archiveGroupAction.bind(null,projectId,groupId)} title={`${String(group.name)} archivieren?`} description="Die Gruppe verschwindet aus aktiven Listen. Historische und Legacy-Daten bleiben erhalten." triggerLabel="Archivieren…" confirmLabel="Gruppe archivieren" triggerClassName="button danger"/></section>
  </AdminShell>;
}
