import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { MapViewer } from "@/components/map-viewer";
import { requireAdminSession } from "@/lib/auth/session";
import { getVisibleTimelineEvents } from "@/lib/entities/timeline";
import { getVisibleMapMarkers } from "@/lib/maps";
import { getPlayerContext, listVisibleNpcsForPlayer } from "@/lib/player-view";
import { getMyCharacter, listVisibleGods, listVisibleGroups, listVisibleLocations, listVisibleMaps } from "@/lib/player-world";
import { listPlayers } from "@/lib/players";
import { getProject } from "@/lib/projects";

type View = "home"|"map"|"timeline"|"npcs"|"gods"|"locations"|"groups"|"character";

export default async function PlayerPreviewPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{playerId?:string;view?:string;mapId?:string}>}){
 await requireAdminSession();const [raw,search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw.projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const [project,players]=await Promise.all([getProject(projectId),listPlayers(projectId)]);if(!project)notFound();const selectedPlayerId=search.playerId?Number.parseInt(search.playerId,10):players.find((p)=>p.active)?.userId;const player=players.find((p)=>p.userId===selectedPlayerId);const view=(['home','map','timeline','npcs','gods','locations','groups','character'].includes(search.view??'')?search.view:'home') as View;
 if(!player)return <AdminShell projectId={projectId} projectName={project.name} title="Player Preview"><section className="panel-card empty-state large"><strong>Kein aktiver Spieler für Preview</strong><Link className="button primary" href={`/admin/projects/${projectId}/players`}>Spieler verwalten</Link></section></AdminShell>;
 const context=await getPlayerContext(projectId,player.userId);if(!context)notFound();const href=(next:View)=>`/admin/projects/${projectId}/preview?playerId=${player.userId}&view=${next}`;
 let content:React.ReactNode;
 if(view==='npcs'){const items=await listVisibleNpcsForPlayer(projectId,player.userId);content=<div className="entity-card-grid">{items.map((item)=><article className="panel-card" key={item.id}><strong>{item.name}</strong><p>{item.description||'Keine bekannte Beschreibung.'}</p></article>)}</div>;}
 else if(view==='gods'){const items=await listVisibleGods(projectId,player.userId);content=<div className="entity-card-grid">{items.map((item)=><article className="panel-card" key={item.id}><strong>{item.name}</strong><small>{item.title} · {item.domain}</small><p>{item.description||'Keine bekannte Beschreibung.'}</p></article>)}</div>;}
 else if(view==='locations'){const items=await listVisibleLocations(projectId,player.userId);content=<div className="entity-card-grid">{items.map((item)=><article className="panel-card" key={item.id}><strong>{item.name}</strong><p>{item.description||'Keine bekannte Beschreibung.'}</p></article>)}</div>;}
 else if(view==='groups'){const items=await listVisibleGroups(projectId,player.userId);content=<div className="entity-card-grid">{items.map((item)=><article className="panel-card" key={item.id}><strong>{item.name}</strong><p>{item.notes}</p></article>)}</div>;}
 else if(view==='timeline'){const items=await getVisibleTimelineEvents(projectId,player.userId);content=<div className="timeline-list">{items.map((item)=><article className="panel-card" key={item.e_id}><span className="soft-label">{item.display_date||'Unbekannt'}</span><h2>{item.name}</h2><p>{item.notes}</p></article>)}</div>;}
 else if(view==='character'){const item=await getMyCharacter(projectId,player.userId);content=item?<section className="panel-card"><h2>{item.name}</h2><p>{item.public_description||'Keine öffentliche Beschreibung.'}</p><small>{item.race} · {item.class} · {item.location_name}</small></section>:<div className="empty-state"><strong>Kein Charakter zugewiesen</strong></div>;}
 else if(view==='map'){const maps=await listVisibleMaps(projectId);const requested=search.mapId?Number.parseInt(search.mapId,10):null;const map=maps.find((m)=>Number(m.map_id)===requested)??maps.find((m)=>m.is_primary)??maps[0];if(map){const markers=await getVisibleMapMarkers(projectId,Number(map.map_id),player.userId);content=<><MapViewer mapConfig={{mapId:Number(map.map_id),mapType:map.map_type as 'tile'|'image',tileUrl:map.tile_url,imagePath:map.image_path,minZoom:map.min_zoom,maxZoom:map.max_zoom,centerLat:map.center_lat,centerLng:map.center_lng,bounds:map.bounds,config:map.config}} initialMarkers={markers}/><div className="row wrap-row">{maps.map((m)=><Link className="button ghost" key={m.map_id} href={`${href('map')}&mapId=${m.map_id}`}>{m.name}</Link>)}</div></>;}else content=<div className="empty-state"><strong>Keine Karte</strong></div>;}
 else {const [npcs,gods,locations,groups,events]=await Promise.all([listVisibleNpcsForPlayer(projectId,player.userId),listVisibleGods(projectId,player.userId),listVisibleLocations(projectId,player.userId),listVisibleGroups(projectId,player.userId),getVisibleTimelineEvents(projectId,player.userId)]);content=<section className="stats-grid"><div className="stat-card"><span>NPCs</span><strong>{npcs.length}</strong></div><div className="stat-card"><span>Gods</span><strong>{gods.length}</strong></div><div className="stat-card"><span>Locations</span><strong>{locations.length}</strong></div><div className="stat-card"><span>Groups</span><strong>{groups.length}</strong></div><div className="stat-card"><span>Events</span><strong>{events.length}</strong></div></section>;}
 return <AdminShell projectId={projectId} projectName={project.name} eyebrow={`${project.name} / Player Preview`} title={`PLAYER PREVIEW: ${context.player_name}`}><div className="player-preview-banner"><strong>PLAYER PREVIEW: {context.player_name}</strong><span>Diese Ansicht verwendet dieselben serverseitigen Permission-/Variant-Queries wie der echte Spieler.</span></div><div className="page-heading compact-heading"><form className="row"><select name="playerId" defaultValue={String(player.userId)}>{players.map((p)=><option key={p.userId} value={p.userId}>{p.displayName}{p.active?'':' · inaktiv'}</option>)}</select><input type="hidden" name="view" value={view}/><button>Als Spieler ansehen</button></form></div><nav className="entity-tabs"><Link href={href('home')}>Home</Link><Link href={href('map')}>Map</Link><Link href={href('timeline')}>Timeline</Link><Link href={href('npcs')}>NPCs</Link><Link href={href('gods')}>Gods</Link><Link href={href('locations')}>Locations</Link><Link href={href('groups')}>Groups</Link><Link href={href('character')}>My Character</Link></nav>{content}</AdminShell>;
}
