import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdminSession } from "@/lib/auth/session";
import { getProject } from "@/lib/projects";
import { listTags } from "@/lib/tags";
import { createTagAction, deleteTagAction, tagEntityAction } from "./actions";

export default async function TagsPage({params}:{params:Promise<{projectId:string}>}){await requireAdminSession();const projectId=Number.parseInt((await params).projectId,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const [project,tags]=await Promise.all([getProject(projectId),listTags(projectId)]);if(!project)notFound();return <AdminShell projectId={projectId} projectName={project.name} eyebrow={`${project.name} / Wissen`} title="Tags"><div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Tags</strong></div><h1>Tags & Filter</h1><p>Generische Tags können projektisoliert an beliebige unterstützte Entities gebunden werden.</p></div><details className="create-dropdown"><summary className="button primary">＋ Tag</summary><div className="create-popover"><form action={createTagAction.bind(null,projectId)} className="stack"><label>Name<input name="name" required maxLength={80}/></label><button className="primary">Tag erstellen</button></form></div></details></div><div className="npc-detail-grid"><section className="panel-card"><div className="table-meta"><span><strong>{tags.length}</strong> Tags</span></div><div className="stack">{tags.map((tag)=><div className="panel-card nested-card row" key={tag.tag_id}><strong>#{tag.name}</strong><span className="muted">{tag.usage_count} Verwendungen</span><form action={deleteTagAction.bind(null,projectId,Number(tag.tag_id))}><button className="button ghost">Löschen</button></form></div>)}</div></section><aside className="panel-card"><span className="panel-kicker">ZUORDNUNG</span><h2>Entity taggen</h2><form action={tagEntityAction.bind(null,projectId)} className="stack"><label>Tag<select name="tagId" required>{tags.map((tag)=><option key={tag.tag_id} value={tag.tag_id}>#{tag.name}</option>)}</select></label><label>Entity Type<select name="entityType"><option value="npc">NPC</option><option value="god">God</option><option value="character">Character</option><option value="location">Location</option><option value="group">Group</option><option value="event">Event</option><option value="map_marker">Map Marker</option><option value="media">Media</option><option value="relationship">Relationship</option></select></label><label>Entity ID<input name="entityId" type="number" min="1" required/></label><button className="primary">Tag zuordnen</button></form></aside></div></AdminShell>;}
