import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { FantasyDateInput } from "@/components/fantasy-date-input";
import { ImageSourceInput } from "@/components/image-source-input";
import { Pagination } from "@/components/pagination";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { calendarStatus, getProjectCalendar } from "@/lib/calendar";
import { listGodsPaginated, type GodListFilters } from "@/lib/entities/gods";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";
import { createGodAction } from "./actions";
import styles from "./gods.module.css";

type Search=Promise<{q?:string;visibility?:string;page?:string;pageSize?:string}>;
function validImage(value:string){return Boolean(value&&value.trim()&&value!=="noimage");}
function visibilityLabel(mode:string){return mode==="all_players"?"Alle Spieler":mode==="selected_players"?"Ausgewählte":"Nur Admin";}
function clean(value:string|null|undefined){const text=value?.trim()??"";return text&&!['unknown','no notes yet'].includes(text.toLowerCase())?text:"";}

export default async function GodsPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [{projectId:raw},search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const visibility=["admin_only","all_players","selected_players"].includes(search.visibility??"")?search.visibility as GodListFilters["visibility"]:undefined;const pagination=parsePagination(search);const [project,gods,calendar]=await Promise.all([getProject(projectId),listGodsPaginated(projectId,{query:search.q,visibility},pagination),getProjectCalendar(projectId)]);if(!project)notFound();const path=`/admin/projects/${projectId}/gods`;const calendarReady=calendar?calendarStatus(calendar).ready:false;const hasFilters=Boolean(search.q||search.visibility);
  return <AdminShell projectId={projectId} projectName={project.name} section="gods" eyebrow={`${project.name} / World`} title="Götter">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Götter</strong></div><h1>Pantheon & Gottheiten</h1><p>Götter sind Personen mit eigenem God-Subtype. Bilder können als Upload oder Pfad gepflegt werden; eine Fantasy-Geburt/Manifestation kann optional dieselbe Weltzeit nutzen.</p></div><details className="create-dropdown"><summary className="button primary">＋ Gottheit</summary><div className="create-popover" style={{minWidth:640}}><form action={createGodAction.bind(null,projectId)} className="stack"><div><span className="panel-kicker">GEMEINSAME PERSON</span><div className="field-grid two"><label>Name<input name="name" required/></label><label>Geschlecht<input name="gender" placeholder="unknown"/></label><label>Personen-Titel<input name="personTitle"/></label><label>Spezies<input name="species"/></label><label>Rolle / Beruf<input name="profession"/></label></div><ImageSourceInput label="Bild / Darstellung"/></div><div><span className="panel-kicker">GOD SUBTYPE</span><div className="field-grid two"><label>Göttlicher Titel<input name="godTitle"/></label><label>Domain<input name="domain"/></label><label>Fraktion / Pantheon<input name="faction"/></label><label>Sichtbarkeit<select name="visibilityMode"><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div></div>{calendar&&calendarReady?<FantasyDateInput prefix="birth" label="Geburt / Manifestation (optional)" months={calendar.months} beforeEraLabel={calendar.beforeEraLabel} afterEraLabel={calendar.afterEraLabel} hasYearZero={calendar.hasYearZero}/>:null}<label>Öffentliche Beschreibung<textarea name="publicDescription"/></label><label>Admin-Notizen<textarea name="adminNotes"/></label><SubmitButton className="primary" pendingLabel="Gottheit wird angelegt …">Gottheit anlegen</SubmitButton></form></div></details></div>
    <section className={`panel-card ${styles.browser}`}><form className={styles.filter} method="get"><input name="q" defaultValue={search.q??""} placeholder="Gott, Domain, Titel oder Pantheon suchen …"/><select name="visibility" defaultValue={visibility??""}><option value="">Alle Sichtbarkeiten</option><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select><button>Filtern</button>{hasFilters?<Link className="button ghost" href={path}>Zurücksetzen</Link>:null}</form><div className="table-meta"><span><strong>{gods.total}</strong> Gottheiten</span><span>Person-ID = n_id · God-ID bleibt Subtype-ID</span></div>{gods.items.length===0?<div className="empty-state large"><strong>Keine Gottheiten gefunden</strong><span>{hasFilters?"Filter ändern oder zurücksetzen.":"Lege die erste Gottheit an."}</span></div>:<div className={styles.grid}>{gods.items.map((god)=><Link key={god.person_id} href={`/admin/projects/${projectId}/gods/${god.person_id}`} className={styles.card}><div className={styles.cover}>{validImage(god.image)?<img src={god.image} alt="" loading="lazy" decoding="async"/>:<span className={styles.monogram}>{god.name.slice(0,1).toUpperCase()}</span>}<span className={styles.domain}>{clean(god.domain)||"Unbekannte Domain"}</span></div><div className={styles.body}><div><h2>{god.name}</h2><p>{clean(god.title)||clean(god.person_title)||"Gottheit"}</p></div><div className={styles.meta}><span className={styles.chip}>{clean(god.faction)||"Ohne Pantheon"}</span>{clean(god.species)?<span className={styles.chip}>{god.species}</span>:null}{clean(god.profession)?<span className={styles.chip}>{god.profession}</span>:null}</div>{clean(god.public_description)?<p>{god.public_description}</p>:null}<div className={styles.footer}><span>{visibilityLabel(god.visibility_mode)}</span><strong>Profil öffnen →</strong></div></div></Link>)}</div>}<Pagination pathname={path} searchParams={{q:search.q,visibility:search.visibility}} page={gods.page} pageSize={gods.pageSize} total={gods.total} totalPages={gods.totalPages}/></section>
  </AdminShell>;
}
