import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { Pagination } from "@/components/pagination";
import { requireAdminSession } from "@/lib/auth/session";
import { listGodsPaginated, type GodListFilters } from "@/lib/entities/gods";
import { parsePagination } from "@/lib/pagination";
import { getProject } from "@/lib/projects";
import { createGodAction } from "./actions";
import styles from "./gods.module.css";

type Search=Promise<{q?:string;visibility?:string;page?:string;pageSize?:string}>;
function validImage(value:string){return Boolean(value&&value.trim()&&value!=="noimage");}
function visibilityLabel(mode:string){return mode==="all_players"?"Alle Spieler":mode==="selected_players"?"Ausgewählte":"Nur Admin";}

export default async function GodsPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Search}){
  await requireAdminSession();const [{projectId:raw},search]=await Promise.all([params,searchParams]);const projectId=Number.parseInt(raw,10);if(!Number.isSafeInteger(projectId)||projectId<=0)notFound();const visibility=["admin_only","all_players","selected_players"].includes(search.visibility??"")?search.visibility as GodListFilters["visibility"]:undefined;const pagination=parsePagination(search);const [project,gods]=await Promise.all([getProject(projectId),listGodsPaginated(projectId,{query:search.q,visibility},pagination)]);if(!project)notFound();const path=`/admin/projects/${projectId}/gods`;
  return <AdminShell projectId={projectId} projectName={project.name} section="gods" eyebrow={`${project.name} / World`} title="Götter">
    <div className="page-heading compact-heading"><div><div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><strong>Götter</strong></div><h1>Pantheon & Gottheiten</h1><p>Götter sind Personen mit eigenem God-Subtype: gemeinsame Identität aus <code>npcs</code>, göttliche Eigenschaften aus <code>gods</code>. Die Übersicht zeigt jetzt auch das Personenbild.</p></div><details className="create-dropdown"><summary className="button primary">＋ Gottheit</summary><div className="create-popover" style={{minWidth:560}}><form action={createGodAction.bind(null,projectId)} className="stack"><div><span className="panel-kicker">GEMEINSAME PERSON</span><div className="field-grid two"><label>Name<input name="name" required/></label><label>Geschlecht<input name="gender" placeholder="unknown"/></label><label>Personen-Titel<input name="personTitle"/></label><label>Spezies<input name="species"/></label><label>Rolle / Beruf<input name="profession"/></label><label>Bild / Porträt<input name="image" placeholder="https://… oder relativer Pfad"/></label></div></div><div><span className="panel-kicker">GOD SUBTYPE</span><div className="field-grid two"><label>Göttlicher Titel<input name="godTitle"/></label><label>Domain<input name="domain"/></label><label>Fraktion / Pantheon<input name="faction"/></label><label>Sichtbarkeit<select name="visibilityMode"><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select></label></div></div><label>Öffentliche Beschreibung<textarea name="publicDescription"/></label><label>Admin-Notizen<textarea name="adminNotes"/></label><button className="primary">Gottheit anlegen</button></form></div></details></div>
    <section className={`panel-card ${styles.browser}`}><form className={styles.filter} method="get"><input name="q" defaultValue={search.q??""} placeholder="Gott, Domain, Titel oder Pantheon suchen …"/><select name="visibility" defaultValue={visibility??""}><option value="">Alle Sichtbarkeiten</option><option value="admin_only">Nur Admin</option><option value="all_players">Alle Spieler</option><option value="selected_players">Ausgewählte</option></select><button>Filtern</button></form><div className="table-meta"><span><strong>{gods.total}</strong> Gottheiten</span><span>Person-ID = n_id · God-ID bleibt Subtype-ID</span></div>{gods.items.length===0?<div className="empty-state large"><strong>Keine Gottheiten gefunden</strong></div>:<div className={styles.grid}>{gods.items.map((god)=><Link key={god.person_id} href={`/admin/projects/${projectId}/gods/${god.person_id}`} className={styles.card}><div className={styles.cover}>{validImage(god.image)?<img src={god.image} alt=""/>:<span className={styles.monogram}>{god.name.slice(0,1).toUpperCase()}</span>}<span className={styles.domain}>{god.domain||"Unbekannte Domain"}</span></div><div className={styles.body}><div><h2>{god.name}</h2><p>{god.title&&god.title!=="unknown"?god.title:god.person_title||god.public_description||"Gottheit ohne öffentliche Kurzbeschreibung"}</p></div><div className={styles.meta}><span className={styles.chip}>{god.faction||"Ohne Pantheon"}</span>{god.species?<span className={styles.chip}>{god.species}</span>:null}{god.profession?<span className={styles.chip}>{god.profession}</span>:null}</div><div className={styles.footer}><span>{visibilityLabel(god.visibility_mode)}</span><strong>Profil öffnen →</strong></div></div></Link>)}</div>}<Pagination pathname={path} searchParams={{q:search.q,visibility:search.visibility}} page={gods.page} pageSize={gods.pageSize} total={gods.total} totalPages={gods.totalPages}/></section>
  </AdminShell>;
}
