"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdminSession } from "@/lib/auth/session";
import { savePersonFantasyDate } from "@/lib/calendar";
import { archiveNpc,createNpc,getNpc,updateNpc } from "@/lib/entities/npcs";
import { entityImageCropFromForm } from "@/lib/entity-image-crop";
import { saveEntityImageProfile } from "@/lib/entity-image-profiles";
import { parseFantasyDateFields } from "@/lib/fantasy-calendar";
import { formCheckbox } from "@/lib/form-data";
import { resolveEntityImageSource,setEntityImageReference } from "@/lib/media";
import { removePersonLocation,setPersonLocation } from "@/lib/person-locations";
import { clearPersonDeathDate,savePersonDeathMetadata } from "@/lib/person-death";
import { getProject } from "@/lib/projects";

const npcSchema=z.object({name:z.string().trim().min(1,"Name ist ein Pflichtfeld.").max(100,"Der Name darf höchstens 100 Zeichen enthalten."),gender:z.enum(["unknown","male","female","hermaphrodite"]),image:z.string().trim().max(4000).optional(),publicDescription:z.string().trim().max(100_000).optional(),adminNotes:z.string().trim().max(100_000).optional(),title:z.string().trim().max(120).optional(),profession:z.string().trim().max(120).optional(),locationId:z.coerce.number().int().positive(),raceId:z.coerce.number().int().positive(),alive:z.boolean(),follower:z.boolean(),className:z.string().trim().max(50).optional()});
function readNpcForm(formData:FormData,image:string){return npcSchema.safeParse({name:formData.get("name"),gender:formData.get("gender"),image,publicDescription:formData.get("publicDescription")||undefined,adminNotes:formData.get("adminNotes")||undefined,title:formData.get("title")||undefined,profession:formData.get("profession")||undefined,locationId:formData.get("locationId"),raceId:formData.get("raceId"),alive:formCheckbox(formData,"alive"),follower:formCheckbox(formData,"follower"),className:formData.get("className")||undefined});}
function dateValues(formData:FormData,prefix:string){return Object.fromEntries(["Precision","Era","Year","Month","Day"].map(suffix=>[`${prefix}${suffix}`,formData.get(`${prefix}${suffix}`)]));}
async function saveLifeFields(projectId:number,personId:number,alive:boolean,formData:FormData){await savePersonDeathMetadata(projectId,personId,alive,formData.get("deathCauseCode"),formData.get("deathCauseDetail"));if(alive){await clearPersonDeathDate(projectId,personId);return;}if(formData.has("deathPrecision"))await savePersonFantasyDate(projectId,personId,"death",parseFantasyDateFields(dateValues(formData,"death"),"death"));}
async function assertProject(projectId:number){if(!Number.isSafeInteger(projectId)||projectId<=0||!(await getProject(projectId)))throw new Error("Die ausgewählte Welt wurde nicht gefunden oder ist archiviert.");}
function npcValidationMessage(error:z.ZodError){const issue=error.issues[0];if(issue?.path[0]==="name")return issue.message;if(issue?.path[0]==="locationId")return "Aktueller Ort ist ein Pflichtfeld.";if(issue?.path[0]==="raceId")return "Spezies / Subspezies ist ein Pflichtfeld.";if(issue?.path[0]==="gender")return "Bitte ein gültiges Geschlecht auswählen.";return "Die NPC-Eingabe ist ungültig. Bitte prüfe die markierten Pflichtfelder und Eingaben.";}

export async function createNpcAction(projectId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);const source=await resolveEntityImageSource(projectId,formData,{title:String(formData.get("name")??"NPC")});const parsed=readNpcForm(formData,source.image);if(!parsed.success)throw new Error(npcValidationMessage(parsed.error));const created=await createNpc(projectId,parsed.data);await setPersonLocation(projectId,created.nId,{locationId:parsed.data.locationId,role:"current",isPrimary:true});if(source.uploaded)await setEntityImageReference(projectId,"person",created.nId,source);await saveEntityImageProfile(projectId,"person",created.nId,source.image,entityImageCropFromForm(formData));if(formData.has("birthPrecision"))await savePersonFantasyDate(projectId,created.nId,"birth",parseFantasyDateFields(dateValues(formData,"birth"),"birth"));await saveLifeFields(projectId,created.nId,parsed.data.alive,formData);redirect(`/admin/projects/${projectId}/npcs/${created.nId}`);}

export async function updateNpcAction(projectId:number,npcId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);const current=await getNpc(projectId,npcId);if(!current)throw new Error("Der NPC wurde nicht gefunden oder gehört nicht zu dieser Welt.");const source=await resolveEntityImageSource(projectId,formData,{current:current.image,entityType:"person",entityId:npcId,title:current.name});const parsed=readNpcForm(formData,source.image);if(!parsed.success)throw new Error(npcValidationMessage(parsed.error));const updated=await updateNpc(projectId,npcId,parsed.data);if(!updated)throw new Error("Der NPC wurde zwischenzeitlich archiviert oder gelöscht.");await setPersonLocation(projectId,npcId,{locationId:parsed.data.locationId,role:"current",isPrimary:true});const imageChanged=source.uploaded||source.removed||source.image!==current.image;if(imageChanged)await setEntityImageReference(projectId,"person",npcId,source);if(formData.has("imageCrop")||imageChanged)await saveEntityImageProfile(projectId,"person",npcId,source.image,entityImageCropFromForm(formData));if(formData.has("birthPrecision"))await savePersonFantasyDate(projectId,npcId,"birth",parseFantasyDateFields(dateValues(formData,"birth"),"birth"));await saveLifeFields(projectId,npcId,parsed.data.alive,formData);revalidatePath(`/admin/projects/${projectId}/npcs/${npcId}`);revalidatePath(`/admin/projects/${projectId}/npcs`);revalidatePath(`/admin/projects/${projectId}/family-trees`);}

export async function addNpcLocationAction(projectId:number,npcId:number,formData:FormData){await requireAdminSession();await assertProject(projectId);await setPersonLocation(projectId,npcId,{locationId:formData.get("linkedLocationId"),role:formData.get("locationRole"),isPrimary:formCheckbox(formData,"locationPrimary"),notes:formData.get("locationNotes")||null});revalidatePath(`/admin/projects/${projectId}/npcs/${npcId}`);}
export async function removeNpcLocationAction(projectId:number,npcId:number,assignmentId:number){await requireAdminSession();await assertProject(projectId);await removePersonLocation(projectId,npcId,assignmentId);revalidatePath(`/admin/projects/${projectId}/npcs/${npcId}`);}
export async function archiveNpcAction(projectId:number,npcId:number){await requireAdminSession();await assertProject(projectId);const archived=await archiveNpc(projectId,npcId);if(!archived)throw new Error("Der NPC wurde nicht gefunden oder ist bereits archiviert.");redirect(`/admin/projects/${projectId}/npcs`);}
