import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "@/components/admin/admin-shell";
import { ConfirmAction } from "@/components/confirm-action";
import { EntityPicker } from "@/components/entity-picker";
import { RaceOriginPicker } from "@/components/race-origin-picker";
import { SubmitButton } from "@/components/submit-button";
import { requireAdminSession } from "@/lib/auth/session";
import { listCultures } from "@/lib/entities/cultures";
import {
  RACE_LOCATION_ROLE_OPTIONS,
  RACE_RELATION_OPTIONS,
  getEffectiveRaceWorldbuilding,
  getRace,
  listRaceCultures,
  listRaceGeography,
  listRaceRelations,
  listRaces,
  raceHierarchyLabel,
} from "@/lib/entities/races";
import { listProjectMaps } from "@/lib/maps";
import { getProject } from "@/lib/projects";
import { RACE_BIOLOGY_FIELDS } from "@/lib/race-worldbuilding";
import {
  addRaceGeographyAction,
  addRaceRelationAction,
  archiveRaceAction,
  deleteRaceGeographyAction,
  deleteRaceRelationAction,
  deleteRaceTraitAction,
  linkRaceCultureAction,
  unlinkRaceCultureAction,
  updateRaceAction,
  updateRaceBiologyAction,
  upsertRaceTraitAction,
} from "../actions";
import { RaceImageCropPanel } from "./race-image-crop-panel";

function mapOptions(rows: Awaited<ReturnType<typeof listProjectMaps>>) { return rows.map((row: any) => ({ mapId: Number(row.map_id), name: String(row.name), mapType: row.map_type as "image" | "tile", tileUrl: row.tile_url ? String(row.tile_url) : null, imagePath: row.image_path ? String(row.image_path) : null, minZoom: Number(row.min_zoom ?? 0), maxZoom: Number(row.max_zoom ?? 6), centerLat: row.center_lat == null ? null : Number(row.center_lat), centerLng: row.center_lng == null ? null : Number(row.center_lng), bounds: row.bounds })); }
function geographyLabel(role: string) { return RACE_LOCATION_ROLE_OPTIONS.find((option) => option.value === role)?.label ?? role; }
function relationLabel(type: string) { return RACE_RELATION_OPTIONS.find((option) => option.value === type)?.label ?? type; }

export default async function RaceDetailPage({ params }: { params: Promise<{ projectId: string; raceId: string }> }) {
  await requireAdminSession(); const raw = await params; const projectId = Number.parseInt(raw.projectId, 10), raceId = Number.parseInt(raw.raceId, 10);
  if (!Number.isSafeInteger(projectId) || !Number.isSafeInteger(raceId) || projectId <= 0 || raceId <= 0) notFound();
  const [project, race, allRaces, mapsRaw, worldbuilding, geography, relations, raceCultures, cultures] = await Promise.all([
    getProject(projectId), getRace(projectId, raceId), listRaces(projectId), listProjectMaps(projectId), getEffectiveRaceWorldbuilding(projectId,raceId), listRaceGeography(projectId,raceId), listRaceRelations(projectId,raceId), listRaceCultures(projectId,raceId), listCultures(projectId),
  ]); if (!project || !race || !worldbuilding) notFound();
  const maps = mapOptions(mapsRaw); const parentOptions = allRaces.filter((candidate) => candidate.parentRaceId == null && !candidate.isUnknown && candidate.raceId !== race.raceId); const canChangeParent = !race.isUnknown && race.childCount === 0;
  const originText = race.originCoordinateMode === "xy" && race.originX != null && race.originY != null ? `X ${race.originX} · Y ${race.originY}` : race.originCoordinateMode === "latlng" && race.originLat != null && race.originLng != null ? `${race.originLat.toFixed(5)}°, ${race.originLng.toFixed(5)}°` : "Nicht gesetzt";
  const levelLabel = race.isUnknown ? "Fallback-Spezies" : race.parentName ? `Subspezies von ${race.parentName}` : "Haupt-Spezies";
  const ownTraitIds = new Map(worldbuilding.ownTraits.map((trait) => [trait.traitKey, trait.traitId])); const availableRelations = allRaces.filter((candidate) => candidate.raceId !== race.raceId && !candidate.isUnknown); const availableCultures = cultures.filter((culture) => !raceCultures.some((linked) => linked.cultureId === culture.cultureId));
  return <AdminShell projectId={projectId} projectName={project.name} section="races" eyebrow={`${project.name} / Spezies`} title={race.name}>
    <div className="breadcrumb"><Link href={`/admin/projects/${projectId}`}>{project.name}</Link><span>/</span><Link href={`/admin/projects/${projectId}/races`}>Spezies</Link><span>/</span><strong>{race.name}</strong></div>
    <section className="entity-hero"><div className="entity-avatar hero-avatar">{race.image && race.image !== "noimage" ? <img src={race.image} alt=""/> : race.name.slice(0, 1).toUpperCase()}</div><div className="entity-hero-main"><span className="page-kicker">{levelLabel} · race_id #{race.raceId}</span><h1>{race.name}</h1><p>{race.description || "Noch keine Beschreibung."}</p><div className="hero-tags"><span className="soft-label">{race.characterCount} Characters</span>{race.childCount > 0 ? <span className="soft-label">{race.childCount} Subspezies</span> : null}<span className="soft-label">{worldbuilding.traits.length} Merkmale</span><span className="soft-label">{raceCultures.length} Kulturen</span><span className="soft-label">{geography.length} Gebiete</span>{race.originMapName ? <span className="soft-label">⌖ {race.originMapName} · {originText}</span> : null}</div></div></section>

    <RaceImageCropPanel projectId={projectId} raceId={raceId} raceName={race.name} currentImage={race.image}/>

    <form action={updateRaceAction.bind(null, projectId, raceId)} className="npc-detail-grid"><div className="stack detail-main">
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">TAXONOMIE & BEZEICHNUNGEN</span><h2>Spezies, Subspezies & Geschlechtsformen</h2></div><span className="record-id">race_id #{race.raceId}</span></div><p className="section-help">Ohne Parent ist der Datensatz eine Haupt-Spezies. Subspezies erben Biologie und freie Merkmale ihrer Haupt-Spezies und überschreiben nur eigene Werte.</p><div className="field-grid two"><label>Grundbegriff / Name<input name="name" maxLength={120} defaultValue={race.name} required readOnly={race.isUnknown}/></label><label>Übergeordnete Spezies{canChangeParent ? <select name="parentRaceId" defaultValue={race.parentRaceId ?? ""}><option value="">Keine – Haupt-Spezies</option>{parentOptions.map((candidate) => <option key={candidate.raceId} value={candidate.raceId}>{candidate.name}</option>)}</select> : <><input type="hidden" name="parentRaceId" value=""/><select disabled defaultValue=""><option value="">Keine – Haupt-Spezies</option></select><small className="muted">{race.isUnknown ? "Der Fallback bleibt immer Haupt-Spezies." : "Diese Spezies besitzt bereits Subspezies."}</small></>}</label><label>Männliche Bezeichnung <span className="muted">optional</span><input name="masculineName" maxLength={120} defaultValue={race.masculineName ?? ""}/></label><label>Weibliche Bezeichnung <span className="muted">optional</span><input name="feminineName" maxLength={120} defaultValue={race.feminineName ?? ""}/></label><label>Bezeichnung für Hermaphroditen <span className="muted">optional</span><input name="hermaphroditeName" maxLength={120} defaultValue={race.hermaphroditeName ?? ""}/></label></div></section>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">AUSSEHEN & LORE</span><h2>Beschreibung</h2></div><Link className="button ghost" href={`/admin/projects/${projectId}/races/${raceId}/image`}>Bild & Zuschnitt öffnen</Link></div><p className="section-help">Bildquelle und 1:1-Profilzuschnitt werden im sichtbaren Bildeditor oben auf dieser Seite verwaltet.</p><label>Beschreibung<textarea name="description" className="large-textarea" maxLength={100000} defaultValue={race.description ?? ""}/></label></section>
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">GEOGRAFISCHER URSPRUNG</span><h2>Ungefährer Ursprungspunkt</h2></div></div><p className="section-help">Der Punkt bleibt eine grobe Herkunftsmarkierung. Weiter unten kannst du zusätzlich echte Locations als Heimat- und Verbreitungsgebiete verknüpfen.</p><RaceOriginPicker maps={maps} initial={{mapId:race.originMapId,coordinateMode:race.originCoordinateMode,x:race.originX,y:race.originY,lat:race.originLat,lng:race.originLng}}/></section>
      <div className="sticky-savebar"><div><strong>Basisdaten speichern</strong><span>Biologie, Merkmale, Kulturen und Verbreitung besitzen darunter eigene sichere Aktionen.</span></div><SubmitButton className="primary" pendingLabel="Spezies wird gespeichert …">Speichern</SubmitButton></div>
    </div><aside className="stack detail-side"><section className="panel-card profile-summary"><span className="panel-kicker">CODEX</span><h2>{race.name}</h2><dl className="summary-list"><div><dt>Ebene</dt><dd>{levelLabel}</dd></div>{race.parentName ? <div><dt>Haupt-Spezies</dt><dd>{race.parentName}</dd></div> : null}<div><dt>Subspezies</dt><dd>{race.childCount}</dd></div><div><dt>Characters</dt><dd>{race.characterCount}</dd></div><div><dt>Kulturen</dt><dd>{raceCultures.length}</dd></div><div><dt>Gebiete</dt><dd>{geography.length}</dd></div><div><dt>Verwandtschaft</dt><dd>{relations.length}</dd></div></dl></section>{race.parentRaceId ? <Link className="button" href={`/admin/projects/${projectId}/races/${race.parentRaceId}`}>Haupt-Spezies öffnen</Link> : null}<Link className="button primary" href={`/admin/projects/${projectId}/npcs?raceId=${race.raceId}`}>Characters dieser Spezies</Link></aside></form>

    <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">VERERBBARE BIOLOGIE</span><h2>Biologische Grunddaten</h2></div>{race.parentName ? <span className="soft-label">Erbt von {race.parentName}</span> : null}</div><p className="section-help">Leere Felder einer Subspezies werden automatisch von der Haupt-Spezies geerbt. Sobald du einen eigenen Wert speicherst, überschreibt nur dieses Feld den Parent.</p><form action={updateRaceBiologyAction.bind(null,projectId,raceId)} className="stack"><div className="field-grid two">{RACE_BIOLOGY_FIELDS.map((field) => { const own = race.biology[field.key]; const effective = worldbuilding.biology.effective[field.key]; const inherited = worldbuilding.biology.inheritedKeys.has(field.key); return <label key={field.key}>{field.label}{inherited ? <span className="muted"> · geerbt: {String(effective)}{field.unit ? ` ${field.unit}` : ""}</span> : null}{field.kind === "number" ? <input name={field.key} type="number" min="0" step="any" defaultValue={own == null ? "" : Number(own)} placeholder={inherited ? String(effective) : undefined}/> : <textarea name={field.key} defaultValue={own == null ? "" : String(own)} placeholder={inherited ? String(effective) : undefined}/>} </label>; })}</div><SubmitButton pendingLabel="Biologie wird gespeichert …">Biologie speichern</SubmitButton></form></section>

    <div className="npc-detail-grid"><div className="stack detail-main">
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">FREIE MERKMALE</span><h2>Spezies-Traits</h2></div><strong>{worldbuilding.traits.length}</strong></div><p className="section-help">Für außergewöhnliche Fantasy-Eigenschaften. Eine Subspezies überschreibt ein geerbtes Merkmal, indem sie denselben Merkmal-Schlüssel verwendet.</p>{worldbuilding.traits.length === 0 ? <div className="empty-state"><strong>Noch keine Merkmale</strong><span>Beispiele: Blut, Atmung, Schlaf, Gliedmaßen, Resistenz oder besondere Sinne.</span></div> : <div className="stack">{worldbuilding.traits.map((trait) => <div className="row wrap-row" key={trait.traitKey} style={{justifyContent:"space-between"}}><div><strong>{trait.label}: {trait.value}{trait.unit ? ` ${trait.unit}` : ""}</strong>{trait.inheritedFromRaceName ? <span className="soft-label" style={{marginLeft:8}}>geerbt von {trait.inheritedFromRaceName}</span> : null}{trait.notes ? <div className="muted">{trait.notes}</div> : null}</div>{ownTraitIds.has(trait.traitKey) ? <form action={deleteRaceTraitAction.bind(null,projectId,raceId,ownTraitIds.get(trait.traitKey)!)}><button type="submit" className="button ghost">Eigenen Wert entfernen</button></form> : null}</div>)}</div>}<form action={upsertRaceTraitAction.bind(null,projectId,raceId)} className="stack" style={{marginTop:16}}><div className="field-grid two"><label>Merkmal<input name="label" required maxLength={120} placeholder="z. B. Blut"/></label><label>Wert<input name="value" required maxLength={20000} placeholder="z. B. silbern"/></label><label>Einheit <span className="muted">optional</span><input name="unit" maxLength={40}/></label><label>Schlüssel <span className="muted">optional</span><input name="traitKey" maxLength={80} placeholder="Automatisch aus Merkmal"/></label></div><label>Notiz <span className="muted">optional</span><textarea name="notes" maxLength={20000}/></label><SubmitButton pendingLabel="Merkmal wird gespeichert …">Merkmal hinzufügen / überschreiben</SubmitButton></form></section>

      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">GEOGRAFIE</span><h2>Heimat & Verbreitung</h2></div><strong>{geography.length}</strong></div>{geography.length === 0 ? <div className="empty-state"><strong>Noch keine Gebiete verknüpft</strong><span>Verknüpfe vorhandene Länder, Regionen, Provinzen, Städte oder andere Locations.</span></div> : <div className="stack">{geography.map((item) => <div className="row wrap-row" key={item.linkId} style={{justifyContent:"space-between"}}><div><strong>{geographyLabel(item.role)} · {item.locationName}</strong><div className="muted">{item.locationKind}{item.notes ? ` · ${item.notes}` : ""}</div></div><div className="row">{item.mapId && item.mapFeatureId ? <Link className="button ghost" href={`/admin/projects/${projectId}/map?mapId=${item.mapId}&featureId=${item.mapFeatureId}`}>Auf Karte</Link> : null}<form action={deleteRaceGeographyAction.bind(null,projectId,raceId,item.linkId)}><button type="submit" className="button ghost">Entfernen</button></form></div></div>)}</div>}<form action={addRaceGeographyAction.bind(null,projectId,raceId)} className="stack" style={{marginTop:16}}><div className="field-grid two"><EntityPicker projectId={projectId} name="locationId" types={["location"]} label="Ort / Gebiet" required allowClear={false} placeholder="Land, Region, Provinz oder Ort suchen …"/><label>Rolle<select name="role" defaultValue="distribution">{RACE_LOCATION_ROLE_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div><label>Notiz <span className="muted">optional</span><input name="notes" maxLength={1000}/></label><SubmitButton pendingLabel="Gebiet wird verknüpft …">Gebiet verknüpfen</SubmitButton></form></section>
    </div><aside className="stack detail-side">
      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">VERWANDTSCHAFT</span><h2>Andere Spezies</h2></div></div>{relations.length === 0 ? <p className="section-help">Noch keine biologischen oder historischen Spezies-Beziehungen.</p> : <div className="stack">{relations.map((relation) => <div key={relation.relationId}><Link href={`/admin/projects/${projectId}/races/${relation.relatedRaceId}`}><strong>{relationLabel(relation.relationType)}: {relation.relatedParentName ? `${relation.relatedParentName} → ${relation.relatedRaceName}` : relation.relatedRaceName}</strong></Link>{relation.notes ? <p className="muted">{relation.notes}</p> : null}<form action={deleteRaceRelationAction.bind(null,projectId,raceId,relation.relationId)}><button type="submit" className="button ghost">Entfernen</button></form></div>)}</div>}{availableRelations.length > 0 ? <form action={addRaceRelationAction.bind(null,projectId,raceId)} className="stack" style={{marginTop:14}}><label>Spezies<select name="relatedRaceId" required defaultValue=""><option value="" disabled>Auswählen …</option>{availableRelations.map((candidate) => <option key={candidate.raceId} value={candidate.raceId}>{raceHierarchyLabel(candidate)}</option>)}</select></label><label>Beziehung<select name="relationType" defaultValue="related">{RACE_RELATION_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label>Notiz<input name="notes" maxLength={1000}/></label><SubmitButton pendingLabel="Verknüpfe …">Verknüpfen</SubmitButton></form> : null}</section>

      <section className="panel-card edit-section"><div className="panel-heading"><div><span className="panel-kicker">KULTUREN / VÖLKER</span><h2>Kulturelle Zugehörigkeit</h2></div></div>{raceCultures.length === 0 ? <p className="section-help">Noch keine Kulturen verknüpft. Kultur und Biologie bleiben getrennte Systeme.</p> : <div className="stack">{raceCultures.map((culture) => <div key={culture.cultureId}><Link href={`/admin/projects/${projectId}/cultures/${culture.cultureId}`}><strong>{culture.name}</strong></Link>{culture.isPrimary ? <span className="soft-label" style={{marginLeft:8}}>Primär</span> : null}<form action={unlinkRaceCultureAction.bind(null,projectId,raceId,culture.cultureId)}><button type="submit" className="button ghost">Entfernen</button></form></div>)}</div>}{availableCultures.length > 0 ? <form action={linkRaceCultureAction.bind(null,projectId,raceId)} className="stack" style={{marginTop:14}}><label>Kultur<select name="cultureId" required defaultValue=""><option value="" disabled>Auswählen …</option>{availableCultures.map((culture) => <option key={culture.cultureId} value={culture.cultureId}>{culture.name}</option>)}</select></label><label><input type="checkbox" name="isPrimary"/> Primäre Kultur für diese Spezies</label><label>Notiz<input name="notes" maxLength={1000}/></label><SubmitButton pendingLabel="Verknüpfe …">Kultur verknüpfen</SubmitButton></form> : <Link className="button" href={`/admin/projects/${projectId}/cultures`}>Kulturen verwalten</Link>}</section>
    </aside></div>

    {race.isUnknown ? <section className="notice"><strong>System-Fallback:</strong> „Unbekannt“ bleibt dauerhaft verfügbar und kann nicht archiviert oder in eine Subspezies umgewandelt werden.</section> : <section className="danger-zone"><div><span className="panel-kicker">DANGER ZONE</span><h2>{race.parentRaceId ? "Subspezies archivieren" : "Spezies archivieren"}</h2><p>{race.characterCount > 0 ? "Dieser Datensatz kann erst archiviert werden, wenn kein aktiver Character ihn mehr verwendet." : race.childCount > 0 ? "Diese Haupt-Spezies kann erst archiviert werden, wenn ihre Subspezies verschoben oder archiviert wurden." : "Der Datensatz wird aus aktiven Auswahllisten entfernt."}</p></div><ConfirmAction action={archiveRaceAction.bind(null, projectId, raceId)} title={`${race.name} archivieren?`} description="Bestehende Worldbuilding-Daten werden nicht physisch gelöscht." triggerLabel="Archivieren…" confirmLabel="Spezies archivieren" triggerClassName="button danger"/></section>}
  </AdminShell>;
}
