"use client";

import { useEffect,useMemo,useRef,useState } from "react";

type MapConfig={mapId:number;mapType:"tile"|"image";tileUrl:string|null;imagePath:string|null;minZoom:number;maxZoom:number;centerLat:number|null;centerLng:number|null;bounds:unknown;config:Record<string,unknown>};
type LayerRow={layer_id:string;name:string;layer_type:"raster"|"vector";source_type:"image"|"tile"|"geojson"|"drawn"|"media";source_url:string|null;media_id:string|null;layer_role:string|null;opacity:number;z_index:number;visible_by_default:boolean;style:Record<string,unknown>;config:Record<string,unknown>;locked:boolean};
type FeatureRow={feature_id:string;layer_id:string;geometry:{type:string;coordinates:unknown};entity_type:string|null;entity_id:string|null;label:string;short_description:string|null;visibility_mode:string;style:Record<string,unknown>;metadata:Record<string,unknown>};
type LocationOption={loc_id:number;name:string;location_kind:string;parent_name:string|null};
type OlGlobal=Record<string,any>;
declare global{interface Window{ol?:OlGlobal}}

const OL_JS="https://cdn.jsdelivr.net/npm/ol@10.6.1/dist/ol.js";const OL_CSS="https://cdn.jsdelivr.net/npm/ol@10.6.1/ol.css";
const LOCATION_KINDS=["country","region","province","city","town","village","district","building","landmark","wilderness","other"] as const;
async function ensureOpenLayers(){if(window.ol)return window.ol;if(!document.querySelector(`link[href="${OL_CSS}"]`)){const link=document.createElement("link");link.rel="stylesheet";link.href=OL_CSS;document.head.appendChild(link);}return new Promise<OlGlobal>((resolve,reject)=>{const existing=document.querySelector<HTMLScriptElement>(`script[src="${OL_JS}"]`);const script=existing??document.createElement("script");const loaded=()=>window.ol?resolve(window.ol):reject(new Error("OpenLayers konnte nicht geladen werden."));script.addEventListener("load",loaded,{once:true});script.addEventListener("error",()=>reject(new Error("OpenLayers konnte nicht geladen werden.")),{once:true});if(!existing){script.src=OL_JS;script.crossOrigin="anonymous";document.head.appendChild(script);}});}
function parseBounds(value:unknown):[[number,number],[number,number]]|null{if(!Array.isArray(value)||value.length!==2||!Array.isArray(value[0])||!Array.isArray(value[1]))return null;const a=value[0].map(Number),b=value[1].map(Number);return a.length>=2&&b.length>=2&&a.every(Number.isFinite)&&b.every(Number.isFinite)?[[a[0],a[1]],[b[0],b[1]]]:null;}
function color(value:unknown,fallback:string){return typeof value==="string"&&value.trim()?value:fallback;}
function rgba(hex:string,alpha:number){const clean=hex.replace("#","");if(!/^[0-9a-f]{6}$/i.test(clean))return `rgba(124,110,230,${alpha})`;const n=Number.parseInt(clean,16);return `rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${alpha})`;}

export function OpenLayersMapStudio({projectId,mapConfig,layers,features,locations}:{projectId:number;mapConfig:MapConfig;layers:LayerRow[];features:FeatureRow[];locations:LocationOption[]}){
  const targetRef=useRef<HTMLDivElement>(null),mapRef=useRef<any>(null),drawRef=useRef<any>(null),selectRef=useRef<any>(null),modifyRef=useRef<any>(null);
  const sourceRefs=useRef(new Map<number,any>()),layerRefs=useRef(new Map<number,any>()),rowRefs=useRef(new Map<number,FeatureRow>()),layerSaveTimers=useRef(new Map<number,ReturnType<typeof setTimeout>>());
  const vectorLayers=useMemo(()=>layers.filter(l=>l.layer_type==="vector"),[layers]);
  const [mode,setMode]=useState<"select"|"Point"|"LineString"|"Polygon">("select"),[layerId,setLayerId]=useState(()=>Number(vectorLayers[0]?.layer_id??0));
  const [label,setLabel]=useState(""),[locationKind,setLocationKind]=useState<string>("country"),[createLocation,setCreateLocation]=useState(true),[parentLocationId,setParentLocationId]=useState(""),[fillColor,setFillColor]=useState("#7c6ee6");
  const [locationOptions,setLocationOptions]=useState<LocationOption[]>(locations),[selectedFeatureId,setSelectedFeatureId]=useState<number|null>(null),[status,setStatus]=useState(""),[error,setError]=useState("");

  function scheduleLayerPatch(id:number,patch:Record<string,unknown>){const previous=layerSaveTimers.current.get(id);if(previous)clearTimeout(previous);layerSaveTimers.current.set(id,setTimeout(async()=>{const response=await fetch(`/api/admin/projects/${projectId}/maps/${mapConfig.mapId}/layers/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});if(!response.ok){const body=await response.json().catch(()=>({}));setError(body.error||"Layer-Einstellung konnte nicht gespeichert werden.");}},300));}
  async function persistGeometry(feature:any){const featureId=Number(feature.get("featureId"));if(!featureId)return;const row=rowRefs.current.get(featureId);if(!row)return;const ol=await ensureOpenLayers();const geometry=new ol.format.GeoJSON().writeGeometryObject(feature.getGeometry());const response=await fetch(`/api/admin/projects/${projectId}/maps/${mapConfig.mapId}/features/${featureId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({layerId:Number(row.layer_id),geometry,entityType:row.entity_type,entityId:row.entity_id?Number(row.entity_id):null,label:row.label,shortDescription:row.short_description,visibilityMode:row.visibility_mode,selectedPlayerIds:[],style:row.style??{},metadata:row.metadata??{}})});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"Geometrie konnte nicht gespeichert werden.");}row.geometry=geometry;setStatus(`„${row.label}“ aktualisiert.`);}
  async function persistFeatureRow(row:FeatureRow){const response=await fetch(`/api/admin/projects/${projectId}/maps/${mapConfig.mapId}/features/${row.feature_id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({layerId:Number(row.layer_id),geometry:row.geometry,entityType:row.entity_type,entityId:row.entity_id?Number(row.entity_id):null,label:row.label,shortDescription:row.short_description,visibilityMode:row.visibility_mode,selectedPlayerIds:[],style:row.style??{},metadata:row.metadata??{}})});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"Feature konnte nicht gespeichert werden.");}}

  useEffect(()=>{setLocationOptions(locations);},[locations]);
  useEffect(()=>{let active=true;ensureOpenLayers().then(ol=>{if(!active||!targetRef.current)return;const simple=mapConfig.mapType==="image";const bounds=parseBounds(mapConfig.bounds)??[[0,0],[4096,8192]];const extent=[bounds[0][1],bounds[0][0],bounds[1][1],bounds[1][0]];const projection=simple?new ol.proj.Projection({code:`WORLDREBORN:${mapConfig.mapId}`,units:"pixels",extent}):undefined;const mapLayers:any[]=[];
    if(simple&&mapConfig.imagePath){const url=mapConfig.imagePath.startsWith("/")?mapConfig.imagePath:`/api/media/${mapConfig.imagePath}`;mapLayers.push(new ol.layer.Image({zIndex:-1000,source:new ol.source.ImageStatic({url,projection,imageExtent:extent})}));}else if(mapConfig.tileUrl)mapLayers.push(new ol.layer.Tile({zIndex:-1000,source:new ol.source.XYZ({url:mapConfig.tileUrl,wrapX:false,minZoom:mapConfig.minZoom,maxZoom:mapConfig.maxZoom})}));
    for(const layer of layers.filter(l=>l.layer_type==="raster")){const id=Number(layer.layer_id);const isSatelliteBase=layer.layer_role==="satellite"&&layer.media_id!=null&&String(layer.media_id)===String(mapConfig.imagePath);if(isSatelliteBase)continue;const url=layer.source_type==="media"&&layer.media_id?`/api/media/${layer.media_id}`:layer.source_url;if(!url)continue;let olLayer:any=null;if((layer.source_type==="image"||layer.source_type==="media")&&simple)olLayer=new ol.layer.Image({opacity:layer.opacity,zIndex:layer.z_index,visible:layer.visible_by_default,source:new ol.source.ImageStatic({url,projection,imageExtent:extent})});else if(layer.source_type==="tile")olLayer=new ol.layer.Tile({opacity:layer.opacity,zIndex:layer.z_index,visible:layer.visible_by_default,source:new ol.source.XYZ({url,wrapX:false})});if(olLayer){olLayer.set("worldrebornLayerId",id);layerRefs.current.set(id,olLayer);mapLayers.push(olLayer);}}
    const geojson=new ol.format.GeoJSON();for(const layer of vectorLayers){const id=Number(layer.layer_id),source=new ol.source.Vector();sourceRefs.current.set(id,source);const fill=color(layer.style?.fill,"#7c6ee6"),stroke=color(layer.style?.stroke,"#f3f4f6"),strokeWidth=Number(layer.style?.strokeWidth??2);const vectorLayer=new ol.layer.Vector({source,zIndex:layer.z_index||500,visible:layer.visible_by_default,opacity:layer.opacity,style:(feature:any)=>{const geometryType=feature.getGeometry()?.getType();const featureId=Number(feature.get("featureId"));const row=featureId?rowRefs.current.get(featureId):null;const featureFill=color(row?.style?.fill,fill),featureStroke=color(row?.style?.stroke,stroke);return new ol.style.Style({fill:geometryType?.includes("Polygon")?new ol.style.Fill({color:rgba(featureFill,.32)}):undefined,stroke:new ol.style.Stroke({color:featureStroke,width:Number(row?.style?.strokeWidth??strokeWidth)}),image:new ol.style.Circle({radius:6,fill:new ol.style.Fill({color:featureFill}),stroke:new ol.style.Stroke({color:featureStroke,width:2})}),text:feature.get("label")?new ol.style.Text({text:String(feature.get("label")),offsetY:-12,fill:new ol.style.Fill({color:"#fff"}),stroke:new ol.style.Stroke({color:"#111",width:3})}):undefined});}});vectorLayer.set("worldrebornLayerId",id);layerRefs.current.set(id,vectorLayer);mapLayers.push(vectorLayer);}
    for(const row of features){try{const id=Number(row.feature_id);rowRefs.current.set(id,{...row});const feature=geojson.readFeature({type:"Feature",geometry:row.geometry,properties:{featureId:id,label:row.label,layerId:Number(row.layer_id)}});sourceRefs.current.get(Number(row.layer_id))?.addFeature(feature);}catch{/* malformed legacy geometry is skipped */}}
    const view=simple?new ol.View({projection,center:ol.extent.getCenter(extent),zoom:0,minZoom:mapConfig.minZoom,maxZoom:mapConfig.maxZoom,extent}):new ol.View({center:ol.proj.fromLonLat([mapConfig.centerLng??0,mapConfig.centerLat??0]),zoom:Math.max(mapConfig.minZoom,2),minZoom:mapConfig.minZoom,maxZoom:mapConfig.maxZoom});const map=new ol.Map({target:targetRef.current,layers:mapLayers,view});mapRef.current=map;if(simple)view.fit(extent,{padding:[20,20,20,20]});
    const select=new ol.interaction.Select({layers:(candidate:any)=>Boolean(candidate.get("worldrebornLayerId"))&&sourceRefs.current.has(Number(candidate.get("worldrebornLayerId")))});selectRef.current=select;map.addInteraction(select);select.on("select",(event:any)=>setSelectedFeatureId(event.selected?.[0]?Number(event.selected[0].get("featureId")):null));const modify=new ol.interaction.Modify({features:select.getFeatures(),pixelTolerance:14});modifyRef.current=modify;map.addInteraction(modify);modify.on("modifyend",async(event:any)=>{setError("");try{for(const feature of event.features.getArray())await persistGeometry(feature);}catch(e){setError(e instanceof Error?e.message:"Änderung konnte nicht gespeichert werden.");}});for(const source of sourceRefs.current.values())map.addInteraction(new ol.interaction.Snap({source,pixelTolerance:14}));
  }).catch(e=>setError(e instanceof Error?e.message:"Karte konnte nicht geladen werden."));return()=>{active=false;for(const timer of layerSaveTimers.current.values())clearTimeout(timer);layerSaveTimers.current.clear();mapRef.current?.setTarget(undefined);mapRef.current=null;sourceRefs.current.clear();layerRefs.current.clear();rowRefs.current.clear();};},[mapConfig,layers,features,vectorLayers]);

  useEffect(()=>{const map=mapRef.current;if(!map)return;ensureOpenLayers().then(ol=>{if(drawRef.current){map.removeInteraction(drawRef.current);drawRef.current=null;}if(mode==="select")return;const source=sourceRefs.current.get(layerId);if(!source){setError("Bitte zuerst einen Vector-Layer auswählen.");return;}selectRef.current?.setActive(false);modifyRef.current?.setActive(false);const draw=new ol.interaction.Draw({source,type:mode,snapTolerance:14,trace:mode!=="Point",traceSource:source});drawRef.current=draw;map.addInteraction(draw);draw.on("drawend",async(event:any)=>{setError("");const featureLabel=label.trim();if(!featureLabel){setError("Bitte vor dem Zeichnen einen Namen eingeben.");source.removeFeature(event.feature);return;}try{const geometry=new ol.format.GeoJSON().writeGeometryObject(event.feature.getGeometry());const style={fill:fillColor};const response=await fetch(`/api/admin/projects/${projectId}/maps/${mapConfig.mapId}/features`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({layerId,geometry,label:featureLabel,visibilityMode:"admin_only",selectedPlayerIds:[],style,metadata:{createdIn:"map-editor-v2"},createLocation:createLocation?{kind:locationKind,parentLocationId:parentLocationId?Number(parentLocationId):null,locationType:locationKind}:null})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Feature konnte nicht gespeichert werden.");const row:FeatureRow={feature_id:String(body.featureId),layer_id:String(layerId),geometry,entity_type:body.locationId?"location":null,entity_id:body.locationId?String(body.locationId):null,label:featureLabel,short_description:null,visibility_mode:"admin_only",style,metadata:{createdIn:"map-editor-v2"}};rowRefs.current.set(Number(body.featureId),row);event.feature.set("featureId",Number(body.featureId));event.feature.set("label",featureLabel);event.feature.set("layerId",layerId);if(body.locationId)setLocationOptions(current=>[...current,{loc_id:Number(body.locationId),name:featureLabel,location_kind:locationKind,parent_name:locationOptions.find(l=>l.loc_id===Number(parentLocationId))?.name??null}].sort((a,b)=>a.name.localeCompare(b.name)));setStatus(body.locationId?`„${featureLabel}“ gespeichert und als ${locationKind}-Location #${body.locationId} angelegt.`:`„${featureLabel}“ gespeichert.`);setLabel("");}catch(e){source.removeFeature(event.feature);setError(e instanceof Error?e.message:"Feature konnte nicht gespeichert werden.");}});});return()=>{if(map&&drawRef.current){map.removeInteraction(drawRef.current);drawRef.current=null;}selectRef.current?.setActive(true);modifyRef.current?.setActive(true);};},[mode,layerId,label,createLocation,locationKind,parentLocationId,fillColor,mapConfig.mapId,projectId,locationOptions]);

  async function deleteSelected(){if(!selectedFeatureId)return;const row=rowRefs.current.get(selectedFeatureId);if(!row)return;if(!window.confirm(`„${row.label}“ wirklich von der Karte löschen? Die verknüpfte Location bleibt erhalten.`))return;setError("");const response=await fetch(`/api/admin/projects/${projectId}/maps/${mapConfig.mapId}/features/${selectedFeatureId}`,{method:"DELETE"});const body=await response.json().catch(()=>({}));if(!response.ok){setError(body.error||"Feature konnte nicht gelöscht werden.");return;}const source=sourceRefs.current.get(Number(row.layer_id));for(const feature of source?.getFeatures()??[])if(Number(feature.get("featureId"))===selectedFeatureId)source.removeFeature(feature);rowRefs.current.delete(selectedFeatureId);selectRef.current?.getFeatures().clear();setSelectedFeatureId(null);setStatus(`„${row.label}“ von der Karte gelöscht.`);}
  async function changeSelectedColor(next:string){if(!selectedFeatureId)return;const row=rowRefs.current.get(selectedFeatureId);if(!row)return;row.style={...row.style,fill:next};setError("");try{await persistFeatureRow(row);sourceRefs.current.get(Number(row.layer_id))?.changed();setStatus(`Farbe von „${row.label}“ gespeichert.`);}catch(e){setError(e instanceof Error?e.message:"Farbe konnte nicht gespeichert werden.");}}
  function toggleLayer(id:number,visible:boolean){layerRefs.current.get(id)?.setVisible(visible);scheduleLayerPatch(id,{visibleByDefault:visible});}function setOpacity(id:number,value:number){layerRefs.current.get(id)?.setOpacity(value);scheduleLayerPatch(id,{opacity:value});}
  function choosePreset(preset:"country"|"province"|"city"|"river"|"road"){setError("");if(preset==="country"||preset==="province"){setMode("Polygon");setCreateLocation(true);setLocationKind(preset);const target=vectorLayers.find(l=>l.layer_role==="political")??vectorLayers[0];if(target)setLayerId(Number(target.layer_id));return;}if(preset==="city"){setMode("Point");setCreateLocation(true);setLocationKind("city");const target=vectorLayers.find(l=>l.layer_role==="settlements")??vectorLayers[0];if(target)setLayerId(Number(target.layer_id));return;}setMode("LineString");setCreateLocation(false);const target=vectorLayers.find(l=>l.layer_role==="routes")??vectorLayers[0];if(target)setLayerId(Number(target.layer_id));}
  const selectedRow=selectedFeatureId?rowRefs.current.get(selectedFeatureId):null;
  return <div style={{display:"grid",gridTemplateColumns:"minmax(230px,300px) minmax(0,1fr)",gap:14,alignItems:"start"}}>
    <aside className="stack" style={{maxHeight:"76vh",overflow:"auto",paddingRight:4}}>
      <section className="panel-card stack"><strong>Schnellwerkzeuge</strong><div className="row wrap-row"><button type="button" className="button ghost" onClick={()=>choosePreset("country")}>Land</button><button type="button" className="button ghost" onClick={()=>choosePreset("province")}>Provinz</button><button type="button" className="button ghost" onClick={()=>choosePreset("city")}>Stadt</button><button type="button" className="button ghost" onClick={()=>choosePreset("river")}>Fluss</button><button type="button" className="button ghost" onClick={()=>choosePreset("road")}>Straße</button></div><small className="muted">Bei Polygonen kannst du vorhandene Grenzen nachzeichnen: erster Klick auf eine bestehende Kante startet das Tracing, ein weiterer Klick beendet es. Shift aktiviert Freihandzeichnen.</small></section>
      <section className="panel-card"><strong>Werkzeug</strong><div className="row wrap-row" style={{marginTop:8}}><button type="button" className={mode==="select"?"button primary":"button ghost"} onClick={()=>setMode("select")}>Auswählen</button><button type="button" className={mode==="Point"?"button primary":"button ghost"} onClick={()=>setMode("Point")}>📍 Punkt</button><button type="button" className={mode==="LineString"?"button primary":"button ghost"} onClick={()=>setMode("LineString")}>— Linie</button><button type="button" className={mode==="Polygon"?"button primary":"button ghost"} onClick={()=>setMode("Polygon")}>▱ Polygon</button></div><p className="muted">Im Auswahlmodus kannst du Eckpunkte ziehen. Änderungen werden automatisch gespeichert und an benachbarte Geometrien gesnappt.</p></section>
      <section className="panel-card stack"><strong>Neues Feature</strong><label>Name<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="z. B. Königreich Erigon"/></label><label>Farbe<div className="row"><input type="color" value={fillColor} onChange={e=>setFillColor(e.target.value)}/><code>{fillColor}</code></div></label><label>Vector Layer<select value={layerId||""} onChange={e=>setLayerId(Number(e.target.value))}><option value="">Layer wählen</option>{vectorLayers.map(l=><option key={l.layer_id} value={l.layer_id}>{l.name}</option>)}</select></label><label className="row"><input type="checkbox" checked={createLocation} onChange={e=>setCreateLocation(e.target.checked)}/> als Location anlegen</label>{createLocation?<><label>Location-Typ<select value={locationKind} onChange={e=>setLocationKind(e.target.value)}>{LOCATION_KINDS.map(kind=><option key={kind} value={kind}>{kind}</option>)}</select></label><label>Parent Location<select value={parentLocationId} onChange={e=>setParentLocationId(e.target.value)}><option value="">— keine —</option>{locationOptions.map(location=><option key={location.loc_id} value={location.loc_id}>{location.parent_name?`${location.parent_name} → `:""}{location.name} ({location.location_kind})</option>)}</select></label></>:null}</section>
      <section className="panel-card stack"><strong>Layer</strong>{layers.map(layer=>{const id=Number(layer.layer_id),isBase=layer.layer_role==="satellite"&&layer.media_id!=null&&String(layer.media_id)===String(mapConfig.imagePath);return <div key={layer.layer_id} style={{display:"grid",gap:5,borderTop:"1px solid rgba(127,127,127,.25)",paddingTop:8}}><label className="row"><input type="checkbox" defaultChecked={isBase||layer.visible_by_default} disabled={isBase} onChange={e=>toggleLayer(id,e.target.checked)}/><span>{layer.name}{isBase?" · Basemap":""}</span></label><div className="row"><small className="muted">{layer.layer_role||layer.source_type}</small><input aria-label={`${layer.name} opacity`} type="range" min="0" max="1" step="0.05" defaultValue={layer.opacity} disabled={isBase} onChange={e=>setOpacity(id,Number(e.target.value))}/></div></div>})}</section>
      {selectedRow?<section className="panel-card stack"><strong>Ausgewählt</strong><span>{selectedRow.label}</span><small className="muted">Feature #{selectedFeatureId}{selectedRow.entity_type?` · ${selectedRow.entity_type} #${selectedRow.entity_id}`:""}</small><label>Farbe<input type="color" defaultValue={color(selectedRow.style?.fill,"#7c6ee6")} onChange={e=>void changeSelectedColor(e.target.value)}/></label><button type="button" className="button danger" onClick={deleteSelected}>Von Karte löschen</button></section>:null}
    </aside>
    <div className="stack"><div ref={targetRef} style={{height:"76vh",minHeight:560,borderRadius:12,overflow:"hidden",background:"#10141a"}}/>{status?<div className="muted" aria-live="polite">{status}</div>:null}{error?<div className="error-message" aria-live="assertive">{error}</div>:null}</div>
  </div>;
}
