"use client";

import { useState } from "react";

const STAGES=["ZIP wird gelesen","Rock-3-Karten werden erkannt","Satellite wird als Basiskarte eingerichtet","Klima- und Terrain-Ebenen werden importiert","Karteneditor wird vorbereitet","Weltkarte wurde erfolgreich erstellt"];

export function Rock3MapCreator({projectId,defaultName}:{projectId:number;defaultName:string}){
  const [name,setName]=useState(defaultName),[archive,setArchive]=useState<File|null>(null),[isPrimary,setIsPrimary]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[stage,setStage]=useState(-1),[summary,setSummary]=useState("");
  async function createMap(){if(!name.trim()){setError("Bitte gib der Karte einen Namen.");return;}if(!archive){setError("Bitte wähle deine Rock-3-ZIP aus.");return;}setBusy(true);setError("");setSummary("");setStage(0);const timers=[window.setTimeout(()=>setStage(current=>Math.max(current,1)),450),window.setTimeout(()=>setStage(current=>Math.max(current,2)),1100),window.setTimeout(()=>setStage(current=>Math.max(current,3)),2100),window.setTimeout(()=>setStage(current=>Math.max(current,4)),3400)];try{const form=new FormData();form.append("name",name.trim());form.append("archive",archive,archive.name);form.append("isPrimary",isPrimary?"true":"false");const response=await fetch(`/api/admin/projects/${projectId}/maps/rock3-create`,{method:"POST",body:form});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Weltkarte konnte nicht erstellt werden.");if(typeof body.editorUrl!=="string")throw new Error("Editor-URL fehlt in der Serverantwort.");setStage(5);const imported=Array.isArray(body.imported)?body.imported.length:0,skipped=Array.isArray(body.skipped)?body.skipped.length:0;setSummary(`${imported} Karten importiert${skipped?` · ${skipped} Datei(en) ignoriert`:""}.`);window.setTimeout(()=>window.location.assign(body.editorUrl),850);}catch(cause){setError(cause instanceof Error?cause.message:"Weltkarte konnte nicht erstellt werden.");setStage(-1);setBusy(false);}finally{for(const timer of timers)window.clearTimeout(timer);}}
  return <div className="stack">
    <div className="field-grid two"><label>Name der Weltkarte<input value={name} maxLength={120} onChange={event=>setName(event.target.value)} placeholder="z. B. Aetheris · Weltkarte" disabled={busy}/></label><label>Rock-3-Export<input type="file" accept=".zip,application/zip,application/x-zip-compressed" onChange={event=>setArchive(event.target.files?.[0]??null)} disabled={busy}/></label></div>
    {archive?<div className="notice"><strong>{archive.name}</strong><div className="muted">{Math.max(1,Math.round(archive.size/1024/1024))} MB · bereit zum Import</div></div>:<div className="muted">Wähle die ZIP des kompletten Rock-3-Exportordners. Unterordner sind erlaubt.</div>}
    <label className="row"><input type="checkbox" checked={isPrimary} onChange={event=>setIsPrimary(event.target.checked)} disabled={busy}/> Als Hauptkarte des Projekts verwenden</label>
    {busy&&stage>=0?<div className="panel-card nested-card stack"><span className="panel-kicker">WELTKARTE WIRD ERSTELLT</span>{STAGES.map((label,index)=><div key={label} className="row" style={{opacity:index<=stage?1:.45}}><span aria-hidden="true">{index<stage?"✓":index===stage?"●":"○"}</span><span>{label}</span></div>)}{summary?<strong>{summary}</strong>:null}</div>:null}
    <button type="button" className="button primary" onClick={createMap} disabled={busy||!archive||!name.trim()}>{busy?"Weltkarte wird erstellt …":"Weltkarte aus ZIP erstellen"}</button>
    <p className="muted" style={{margin:0}}>Satellite Color wird automatisch zur Basiskarte. Biome, Niederschlag, Temperatur, Höhenkarten und Land Mask werden als umschaltbare Ebenen angelegt. Länder, Städte, Straßen und Flüsse erhalten eigene Inhaltsebenen.</p>
    {error?<div className="error-message" aria-live="assertive">{error}</div>:null}
  </div>;
}
